### ISSUE TITLE
Tutorial Inadequate for New Players/No Information About Growing Up/Getting Old

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1004]
I've seen it numerous times that new players will try to pick something up, other than a rubber ball, before 3 years old when they get hair. They expect that they can interact with things right away and try to touch something multiple times. There is no information about what players can do as a baby or any information about age restrictions in the tutorial. If a new player tries to eat solid food before 3, they are wasting their time. 

If a player tries to pick up a cart before 12, it's a waste of time. If a player tries to move a stone block before 14, it's a waste of time. If a player tries to use a horse before 13, it's a waste of time. If a player tries to lasso a horse before 15, it's a waste of time. If a player tries to use a truck or drive a car before 16, it's a waste of time. If a player wants to slice bread before 8 it's a waste of time. If a player wants to hunt a turkey before 10, it's a waste of time. Also, I think I've seen new players try to hunt a bear with one arrow, and there's the case of players trying to stab a boar with a knife (which has some logic to it).

**The tutorial also doesn't tell you that you can't feed a child once you reach 40, and there's no way to figure this out purely on the basis of one's own gameplay**.

I recently saw Tux from about 3:00 to 4:30 into his [stream](https://www.twitch.tv/videos/2012454451), an experienced player, get picked up several times by some new player and starve.

This being a one life game with a time limit, players are supposed to have the potential to do things right the first time. 

Perhaps the entire list of age restrictions would be a bit much, but the part about not being able to do anything as a baby definitely would be useful (it's definitely NOT obvious to enough people... so many babies think they can pick something up that I've regularly said "YOU CAN'T PICK ANYTHING UP UNTIL YOU GET HAIR" for probably over a year now).  And the part about not being able to feed once a woman hits 40/has grey hair (I think the tan character going grey isn't clear as the others).

**Comment by Shadie116** [comment]
that is the point of survival, the goal is to survive them, not teach them how to be indoctrinated into a community

**Comment by DougLefelhocz** [comment]
Shadie116,

The problem with players not having any information about age restrictions/changes is confusion.  All sorts of new players get confused that they can't pick up anything until three years old, and honestly, I STILL find it frustrating to see.  A mother who is 40 and tries to feed their child **believes** that she feeds her child, when she does nothing for him or her in reality, and may even prevent someone else from feeding him or her.

Confusion is not an interesting sort of challenge.  Also, challenge by itself is not interesting or at least not interesting enough.  A game where people had to program in Brainfuck, ceteris paribus, would not be more interesting than a game where people had to program in C++, even though it would be more challenging. 

Also, numbers these past few months have been *better* than they were in the past few Decembers and Novembers and Octobers, as evidenced by [this link](https://steamcharts.com/app/595690).   And that was BEFORE the recently influx due to CHRBRG's video.  So, your claim about the "fun" aspect of this game getting ruined say by recent anti-greifing changes, simply doesn't hold water for this game.

**Comment by Shadie116** [comment]
C++ is actually pretty easy. Just like a complicated version of sharp. It's like I made the concepts myself, it feels phlysophical in nature. It's been two days in visual studio smacking code learned. I still don't understand how to make a gui

**Comment by Shadie116** [comment]
I think that just like in politics we should meet in the middle, as all mixtures do.

**Comment by DougLefelhocz** [comment]
Hopelynn writes on discord:

"actually, that would be a suggestion maybe...a popup message that states you can no longer feed children once you hit 40, put it on a cooldown or something so you're not spammed with it"

Twisted also starved a child accidently as a tan woman [here](https://www.youtube.com/watch?v=hX4pJa8LDPg&t=986s) at about 39:40 (I don't consider him putting the child on mosquitoes relevant).

Bluehawk:

"i like the way YaH does it. When you turn old you no longer have bbs but you can still breast feed until you're 43 so if you have bb at the last second you can still feed til they turn 3"

**Comment by path-to-aaru** [comment]
I completely agree that the tutorial has probably contributed the most to low player retention.

Last night I had the opportunity to witness someone streaming the game and their first experience with it. He was very patient and curious, made sure to read every pop-up message, and even spent time exploring different items and their recipes. Yet when he spawned in he was not prepared at all to survive and be useful because of the following problems.

- The game doesn't explain what you can and can't do as a baby and when that changes, so he nearly starved thinking that he just couldn't feed himself even though he was over 3. 
- The tutorial leads players into falsely believing that eating the same food multiple times is viable, because it provides them with a Gen 0 character that has no food decay, and is surrounded by wild foods that have a high pip value such as burdock. When this player finally spawned in, he sat eating berries off the bush constantly, trying to fight off hunger 1 pip at a time because he didn't know better. Yum chains need a better explanation because it is crucial.
- The entire technical setup of the tutorial has a lot of really big issues. Players don't expect there to be two tutorials, and the way you have to click "get reborn" or login again just to get placed in the wilderness tutorial is confusing. It should be an additional option you can load into instead of being forced, because it is honestly a worse introduction to the game than just being born as a baby and being taken care of / taught.
- The tutorial does not show off or offer much potential to make the player even want to slog through all these things. The tutorial area should be better designed to look like a typical town so that players can click around and experiment and see what the game actually looks like instead of wandering out in the wilderness or in an adobe cave.

The level of enjoyment the player was having was hard to watch. There was no visible joy or interest, even though he was patient and trying to give it a shot. But then when he was actually born, he instantly started having a good time. The town looked much better than the tutorial area, there were people running around, and a bear was attacking, it was chaos but the difference in their mood and level of fun was night and day. It makes me sad to think how many people have probably given up on the game because of the tutorial experience.

**Comment by Shadie116** [comment]
Why do you all ride twisted so dam much. Is he your god, your holy father. And YES the tutorial is a bit goofy but they still need a challenge I believe. It's also funny, you paid 20$ so you'd better learn the game or not. Nobody said it would be easy

**Comment by Shadie116** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/23c9d1a6-3045-406d-a189-4591f66d1ca3)
Yeah this is fr ya'll rn. You're on twisted, hop off. Stop glazing
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/2915293e-e2b4-40d9-a137-f65de686d0e4)

**Comment by DougLefelhocz** [comment]
> Why do you all ride twisted so dam much.

This kind of comment is pointless here and also not accurate.  I only referenced his video; I didn't comment on the quality of it.  If I know another *experienced* player in vanilla who had the same thing happen to him or her, that player's video would have equal value to Twisted's (for the purposes of this thread, ceteris paribus).  And even if someone is a fan of Twisted, how does that detract from the issue at all?  Simply put, it wouldn't.

**Comment by Shadie116** [comment]
yeah. yeah whatever. Just saying though🙄

**Comment by jasonrohrer** [comment]
Yeah... the tutorial is already packed to the gills as it is.

Parents are supposed to teach you some things too.  They get a message that you are a brand new player, so they can help explain some of these other important things to you.

Like, "You're too young to touch that." Or... "Your aunt is too old to nurse you."  That kind of thing.

The tutorial is mostly just supposed to teach you the controls.  Like that you can click, right-click, click yourself to eat, click to remove clothing, tab through the crafting hints, etc.
