### ISSUE TITLE
Make /die not effect your gene score because you go to donkey town if you do it too much.

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLife#1008]

**Comment by DougLefelhocz** [comment]
Gene score indicates the intended way to play.  I note also that /die wasn't originally part of the game.  It only got invented, because players would sometimes kill themselves other ways (Twisted did this so that he could show off advanced towns in his YouTube videos years ago).  The intended way to play involves trying to survive for 60 minutes and playing for the survival and enjoyment of your family.  Using /die is neither.  In fact, there have existed many reports by players on discord and reddit over time that /die annoys players, and it's not inconceivable that it has caused some player to quit mid-life.

Sometimes I want to play in some other family than the one that I get born into (I can check which families are alive via YumLife mod OR by using the family trees page).  But, since I want to keep my gene score up so that I might be Eve later, and have a few more pips for hungry work at the end of a life, I generally don't do so.  However, if there were no penalty to gene score to doing so, I might use /die.

However, again, /die doesn't fit.  It's supposed to be a survival game.  In other words, you try to get your character to survive.  If you use /die, you're not trying to survive.  You're deliberately dying.

So, NO.  Gene score should get penalized for a player using /die as it stands.

**Comment by Shadie116** [comment]
Well how about a twos rule, you /die more than two times you get penalized. Because I'm not trying to play 1 hour one life for 1 more hour because I clicked the be born button by mistake. Hope you understand that
