### ISSUE TITLE
Why you should not unsplit the servers.

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLife#1010]
I really think it makes the game feel more natural. The less veterans the more you can see how the game would naturally progress without all the hacks and cheats being projected on to the player base. And yes ofc there will always be people trying to advertise cheats and whatever, blablabla, but for a well aired amount of time you could see the natural development of players who aren't given cheats that pretty much make them super human. Like a find function???? I can't even find my own phone half the dam time. 😂

**Comment by DougLefelhocz** [comment]
When there was a bug and more server split intentionally, families end up with low population at some time during the early morning American hours.  A new Eve, generally at least, needs the opportunity to start a new place, since the game concept involves rebuilding from scratch.  Low population hours can doom families.  I saw many, many times that families would die out when bs2 population got down to 20-25 or so, and I remember someone else commenting on this before.  There have been numerous complaints on the no baby issue killing off families, and I don't think that families dying out to no babies on a non-custom server is intended.

Also, the effect can be (and Tarr reported this), that the result for people playing during those times can be nothing but Eve runs.

Even runs can be great.  But, if you play 4-6 times and that's all you do, variety ends up lost.  The technology tree doesn't get climbed.  And there wouldn't be any planning or thinking ahead for developing towns.  And more.  

So, there do exist reasons for the servers to merge at some point.

**Comment by Shadie116** [comment]
well we'll see I guess
