### ISSUE TITLE
New Eve Spawn Check/Simulation?

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1016]
> To keep things fresh, we force-spawn a new Eve when everyone on the server is part of a family that is over generation 40 (every family at least roughly 10 hours old).

[Link](https://github.com/jasonrohrer/OneLife/commit/4dad367f3d1e2103dc87fc89598412ceaf78f575)

> Kotryna — Today at 5:55 PM

> Another Eve does not spawn from what I've seen.

Ace said that he wondered if that had forced another recent Ginger family, since they are two currently.

Eve though in error, in response to Ace's comment the impression of the following might be relevant:

> TheGeniusPhoenix — Today at 7:00 PM

> It was supposed to force an eve after every 50 generations, however I've never seen a consistant number before it forces a second eve.

I've felt suspicious that new Eve spawns worked as intended, believing that if the new Eve hugs a wolf, that's it, no new family will be around.

Any way to test this sort of condition, via a simulation, likely works as intended?

**Comment by cordy-123** [comment]
Every family in the server must be over **100** generations.

Mr. Rohrer changed it on August 2020.

"forceEveAfterGenerationNumber pushed up to 100 (about 1 new town a day). Was 40 (about 1 new town every 9 hours)."

https://github.com/jasonrohrer/OneLife/commit/5c9cb26382ce0592587082341858711f75f2f2b8

**Comment by cordy-123** [comment]
It's quite hard to notice if the forced eve spawn is working. 
 
Mostly because it is quite rare that all families are over 100 gens.

---

Generally, OHOL population... 

1. over 1000 players per day have logged in
- viral tiktok/youtube video/steam sale
- server splits into server1 so **you won't get all high gen fams on bs2**

2. around 300-450 players per day have logged in
- last viral vid/sale was a longtime ago
- low OHOL bs2 population so plenty of fams die of no fertiles, **you won't get all high gen fams**

3. around 550-700 players per day have logged in
- viral vid/sale has died down somewhat
- middle ground
- this is the **most probable time that you will see all fams at high gens**

**Comment by DougLefelhocz** [comment]
> Every family in the server must be over **100** generations.
> 
> Mr. Rohrer changed it on August 2020.
> 
> "forceEveAfterGenerationNumber pushed up to 100 (about 1 new town a day). Was 40 (about 1 new town every 9 hours)."
> 
> [5c9cb26](https://github.com/jasonrohrer/OneLife/commit/5c9cb26382ce0592587082341858711f75f2f2b8)

Thanks Cordy.  This didn't appear when I searched 'Eve' in live-dev-changes, and I can see how it wouldn't.

**Comment by jasonrohrer** [comment]
The code that does this is pretty simple, and it looks correct to me:

https://github.com/jasonrohrer/OneLife/blob/9505c8cb5a044e1fab80cafcf5a36dfe741cb0d9/server/server.cpp#L9720

But you're right that it's rare.
