### ISSUE TITLE
Updates Kicking People Off Of Servers

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1022]
Maybe I missed a change?

Last I knew updates were only suppose to render characters currently on a server infertile, as in "children of men" mode.

But, the most recent two (and maybe more) have disconnected people from their living characters.

**Comment by cordy-123** [comment]
The lifelog confirms everyone in bs2 died at 1705515123 (unix). 

Source: http://publicdata.onehouronelife.com/publicLifeLogData/lifeLog_bigserver2.onehouronelife.com/2024_01January_17_Wednesday.txt

=====

It was probably done because of the introduction of the 1% chance of becoming a ghost.

As some players spend a couple of IRL days as ghosts.

=====

In my opinion, the old way (where non-pro/vet players were quite often sad and confused about why they weren't getting babies in bs2 and then just waiting out their deaths) was not that great.

Also, it makes the developer (and the players) wait up to 59 minutes for the game to finish updating.

Usually, it would be near nighttime for Mr. Rohrer and he would just be waiting out those minutes before he could log-off for the night. Not a very pragmatic approach to a healthy work schedule.

**Comment by DougLefelhocz** [comment]
Thanks for the information about ghosts Cordy.

I did a search after that for around the ghost time, though, and didn't find any notes about this changing.  So, I'm leaving this up.  I don't think I agree about the traditional way of how update worked.  I even remember one time I was Eve, and had one of my daughters rushing rabbit fur clothing, and I jumped into the supply she was having to make a pouch for bellows.  Later I learned that we had an update going on.  But, such a period has an advantage in that closer interaction seems reasonable, and teaching can be more in depth, since there's not pressure from babies and fewer people over time.

That said, 100% for sure, there's a clash between servers shutting down and waiting for players to get old, and ghosts living past 60.  Those two things are not compatible.

But, I'm not clear that players dropping from servers in an instant is intentional or not, so I'm leaving this up.

**Comment by Shadie116** [comment]
don't updates kill everybody to make room for the new order?

**Comment by DougLefelhocz** [comment]
> don't updates kill everybody to make room for the new order?

Historically, and by design at least in the past, it has worked such that updates would not kill any characters.  Instead, they would just render characters infertile.

But now, updates are removing people from bigserver2, locking people out of bigserver2 until the update completes, and thus kills off characters.  The purpose of this issue lies in either making that clear as a bug, or if it's intentional, getting closed so that we know that the developer has changed his mind on how updates should work.

**Comment by Shadie116** [comment]
I think that's fine

**Comment by Shadie116** [comment]
and a single ghost could lock the server

**Comment by DougLefelhocz** [comment]
Can we have all ghosts exorcized first, and then have a gradual transition process like we use to?

In addition to how jarring getting kicked off of a server can be to new players on bs2, low pop players can lose their Eve spawn.  I just got informed that someone lost their Eve spawn sadly yesterday.
