### ISSUE TITLE
Issue with editor

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#1028]
who would like to report a bug on github regarding inaccuracies in displaying sprites for number of uses in the Objects and Scene tab in the editor ?

I’m at work and 100% trust the person who said this. Worth looking at when able

**Comment by Jinbaili83** [comment]
Vanishing sprites that are less numerous than #of uses are not properly displayed when previewed in Objects page of Editor.
In example in partial water bucket hides water level at 5 uses on Objects page but on Scene page(and in game) its gone at 8 uses.
Vanishing sprites got changed because of https://github.com/jasonrohrer/OneLifeData7/issues/869.
