### ISSUE TITLE
ONELIFE : Chat | Message update.

### ISSUE THREAD

**Issue by is52hertz** [jasonrohrer/OneLife#1029]
> First of all, thank you for your detailed reply to my issues (#998)!
> Because I was busy with my studies during that time, I couldn't reply in time, sorry.
> In order to make `OneLife` **better**, I am here to contribute again!

**This `issues` is about `OneLife Chat`.**

![image](https://github.com/jasonrohrer/OneLife/assets/144510573/e21de8b2-046a-422f-a5b4-a740264122b1)

- [ ] Chat messages can be copied.
 - **Question**: Many OneLife players are non-native English speakers (including me), and OneLife only allows communication using English letters, so we will use a translator. But OneLife's message cannot be copied, which leads to a problem - we have to copy its message, or use OCR. This is quite troublesome. When the text of the other party's message is too long, we have no time to copy it, and using OCR will lead to inaccurate recognition (some OCR even requires payment.)
 - **Desired function**: Very simple, the message box can be copied by right-clicking the mouse!
 ![image](https://github.com/jasonrohrer/OneLife/assets/144510573/ea920e41-02a2-4a54-ac2e-1257c5ea7a57)
 - **Additionally**: If you have time, you can add a display effect [highlight text when the mouse is hovering over the message box. ]

- [ ] Chat messages are displayed in multiple lines.
 - **Question**: After OneLife sends a message, if you send another one, the previous one (which has not yet expired) will disappear directly.
 - **Desired function**: When the current message has not yet expired and the next message has been sent, move the previous message up.
 ![image](https://github.com/jasonrohrer/OneLife/assets/144510573/883398bd-12fc-42ea-a3ad-946b38d89e2e)
 - **Additionally**: If you have time, you can add a maximum value, `MaxMessageLine.ini` (can be adjusted on the client side.)

- [ ] Change the disappearing time based on the chat message word count.
 - **Question**: Messages can be longer or shorter, so they shouldn't have the same disappearing time!
 - **Desired function**: Calculate the number of words in the message `n`, the disappearance time `t` `(n<=7)t = 3.5s, (n>7)t = n/2, tmax = 15s` (these should be set on the server Medium can be adjusted.)

That's all!

**Comment by Shadie116** [comment]
Man you are smart

**Comment by jasonrohrer** [comment]
So... longer messages are already shown for a longer time.  See:

https://github.com/jasonrohrer/OneLife/blob/master/gameSource/LivingLifePage.cpp#L20016


I don't want to make messages move up like you're suggesting.  I'm really trying to keep a "cartoon" aesthetic.  It's not supposed to look digital, like a log of messages moving up.


So... maybe it would be better...  instead of clicking one message, what if there's a key you can press... maybe CTRL-C, which will copy all recent message history to your clipboard, complete with labels for speakers?

Like:

Eve Smith:  HELLO THERE
Bob Smith:  MOM, WE NEED TO FEED THE FIRE
SALLY SMITH:  I'LL GO CHOP WOOD


So then you could feed the whole thing into the translator, or copy it into a text editor, and get whatever you need.

So then...  you wouldn't need to worry about missing anything.  All recent text would be included.

**Comment by jasonrohrer** [comment]
Working on this... it currently copies speech to the clipboard from the last 30 seconds, and it looks like this:

```
ALLIE WAMPLER:  MOM

ALLIE WAMPLER:  U STILL HAVE KIDS!?

TRISHA WAMPLER:  APPARENTLY

TRISHA WAMPLER:  LOL
```

**Comment by is52hertz** [comment]
> Working on this... it currently copies speech to the clipboard from the last 30 seconds, and it looks like this:
> 
> ```
> ALLIE WAMPLER:  MOM
> 
> ALLIE WAMPLER:  U STILL HAVE KIDS!?
> 
> TRISHA WAMPLER:  APPARENTLY
> 
> TRISHA WAMPLER:  LOL
> ```

Ok, Thanks!
