### ISSUE TITLE
make better swamps

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLife#1031]
swamps look like not swamps with no fallen trees nor logs and all that yada yada yada geese in every pond

**Comment by DougLefelhocz** [comment]
The Github is for bugs, inconsistencies, issues, or problems.

The above post does not have any bugs, inconsistencies, issues, or problems.  Consequently, it would make sense if the author closed this issue immediately.

**Comment by Shadie116** [comment]
i don't care

**Comment by DougLefelhocz** [comment]
> i don't care

Since you don't care about the purposes of the Github, you would do best to close all your issues until you can muster up the motivation to care about it's purposes and also understand it's purposes.

**Comment by Shadie116** [comment]
I just don't care about you. It would be less stressing to disregard you

**Comment by Shadie116** [comment]
From an evolutionary standpoint its better to not care for people you don't care about surprisingly.

**Comment by DougLefelhocz** [comment]
> I just don't care about you. It would be less stressing to disregard you

I'm not what I write.  I'm not asking for you to care about me.

I'm telling you that it would be in your better interest to just close this issue, and other ones.  See how I've now typed out another message shadie116?  If you had just closed this issue, there wouldn't have existed this message.  That's one benefit.  Another benefit would consist in your peace of mind, since then you don't have to wonder "will this get closed without a comment by Jason?"  Which somehow you seem uncertain of.

**Comment by Shadie116** [comment]
Unless I try nothing will happen so I'll stand my ground.
