### ISSUE TITLE
Prolific Cursing Account using Curses Maliciously

### ISSUE THREAD

**Issue by SoloAceMouse** [jasonrohrer/OneLife#1034]
![Prolific cursing issue](https://github.com/jasonrohrer/OneLifeData7/assets/147592460/8bd24bfa-704c-4696-9b84-bcf29ff46fd3)

Well the bad apples are back trying to spoil things, again. Looks like there is an attempt by a malicious player to use the curse system to target the community, at large.

My proposal would be to set a limit of 100 active curses on an account, which is far more than a non-malicious player should ever need to use. If someone tries to curse literally every single player, then just have the oldest curses on the list auto-remove, making their crusade against the community futile.

**Comment by SoloAceMouse** [comment]
This account is typically averaging around a dozen curses per day, and they just keep logging in solely to farm curses and try to kill off fams by preventing people from being born there.

Tracking their curses, we can see that they fire the curse off at anyone in range who isn't already cursed every 15 minutes when the curse token regenerates. This behavior is damaging and should be nullified by preventing a single account from becoming the living incarnate of infertility and dooming a fam to extinction simply by being alive.

**Comment by MrMendeleev2** [comment]
People will accumulate more curses send in the following years to come. we are less than 8 months in 5 year curse time period to come.

There are 6 people with 100+ active curses send in the period 2023_07_28 - 2024_02_26
```
792c15e30fe0993f113ca2b6dc1a7d462afbec7b 107
1194746f435928ec80e445c95afd0b0435f688fb 134
8b08db38f3e716c573e12577fbd1f9ffe285f0fd 136
eaf01551f45575e9caa07ee7b6529005bf074f0a 143
afdb39bc9198116007f90ec98164fff64eca0d8a 153
41d769bf9ed3ca57b57e4ad11e3f1b97bafd36b4 202
```
Honestly only the last one seems to be malicious in intent others just play a lot

If we assume people will continue to play for the next 5 years and will keep cursing at the same rate as they did since 2023_07_28
suggested change might affect anyone with 11+ curses send. there are currently 255 players like that. 
It is 11% of 2300 people who used Curse feature. 

I have no hard opinion about that, but i think suggested change might affect badly players who are not "bad apples"

PS
File with hashes and number of active curses send
[curses_counted_withall.txt](https://github.com/jasonrohrer/OneLifeData7/files/14412629/curses_counted_withall.txt)

**Comment by SoloAceMouse** [comment]
Yeah, there are some accounts with over 100 active outgoing curses at this point, most of which are accounts with 500-1000 lives. In spite of this, I believe the damage of a singular bad actor outweighs this concern [even worse if others begin following the trend].

The account in question was activated 20 days ago and has more than double the curse count of the others. It is a clear attempt to use the system as a weapon against the community to make a troll account. It has fired off an average of 11 curses per day since that time, and seems likely to continue cursing indiscriminately.

I'm open to suggestions about how else to combat this, but frankly having a limit with a rolling list seems the least harmful, as the curse limit would affect the oldest active curses at any given time.

An attempt to use the curse system solely to attack the community at large is still a problem and I believe the solution would have a minimal negative impact.

**Comment by jasonrohrer** [comment]
So, to understand the problem here....

When one of these mega-curse-ers is living in a town, they effectively block most active players from being born in that town?

Where each of these "good" people will only have a few curses, and thus a small radius, the radius will be enough to prevent them from being born into the town where the mega-curse-er is living?

But also, the reciprocal nature of curses isn't preventing the Mega-curse-er from being born in most places?

I can't remember how it works... you won't be born as a baby to someone that you yourself have cursed, but I think you can still get born in their town, right?

**Comment by jasonrohrer** [comment]
Actually, it looks like curses only affect your birth location if others are cursing you.

If you have them cursed, you can still be born to them.... at least from my brief dive into the code just now.

**Comment by jasonrohrer** [comment]
So...we don't want to limit each person to some number of curses, because then someone with multiple accounts can just have enough accounts to swamp this.  So if each person only gets 100 curses, then a griefer can just have 110 accounts... you can't curse them all!

It seems like the best solution here is to shrink the starting curse radius quite a bit.  If you're only cursed by a few people, it should be impossible to stop you from being born in a given town.
