### ISSUE TITLE
The most problematic issue (what a doozy)

### ISSUE THREAD

**Issue by CommunityExile** [jasonrohrer/OneLife#1046]
I know you're tired of me spewing out issues like a flooded storm drain but this one is by far the most important one of all so I'm not going to joke around on this one. 

One more thing before we start: (This has nothing to do griefing)

Open-source rights respected.

**Comment by 3x2xShady** [comment]
So what I want to tell you is about the imbalance between Yumlife/Phex/Hetuw client users. I noticed this and came up with a theory about it. So what here is what I'm thinking summarized.

**Comment by 3x2xShady** [comment]
(Just to make things easier for myself I'm going to call Yumlife/Phex/Hetuw users modified client users, the principles do not relate to every client user. I've temporarily blocked everybody just so I can hear what you have to say about the issue)

So the subject I'd like to discuss with you is the imbalance between normal players and Client Users. Over the years most clients have been very lightly changed from the main game, an example I'd use is milkweed's mod or abwz mod but over the years they've just been getting better and better so that's where this issue arises. 

With the improvement of mods like Yumlife client users have very quickly been getting an unfair advantage against the rest of the player base. Yumlife users are a minority and this minority in power no doubt has the ability to survive better than everybody else without a client. Here is an image that shows the types of advantages that they have, I can't explain them all. 
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/eed6c00a-27a1-4700-991a-e075290306ad)
These Client Users always live to 60 and as a result their genescore is always higher than the clientless users. The chances of a Yumlife player compared to a normal player dying due to a wolf is a pretty steep ratio. When you look at the toolkit a normal player has it almost seems unfair, because it is. The main player base of people who don't use mods is affected very heavily by those who do which as I already said is a minority of the player base. Here is about everything that normal players have to survive with: ![Screenshot 2024-03-25 001706](https://github.com/jasonrohrer/OneLife/assets/126846097/3f835d06-071c-4200-85dd-c7c8b7f90412)

**Comment by 3x2xShady** [comment]
I feel an inequality that the normal player base can't see, they always have a greater chance of dying compared to a Client User so I was hoping that there may be something you can do to counteract this problem because all of the client users have a higher genescore and its not based off of purely the skill of a player anymore, but it's based off of if that player has a Modified Client or not. that very much affects the gene score mechanic. Why not give the newer players a turn on the marry go round?

**Comment by 3x2xShady** [comment]
Or what I should really say is why not give the clientless players a go at it?

**Comment by olliez-mods** [comment]
Good post, nicely done :D

**Comment by DopiePanda** [comment]
People live to 60 cause they know how to yum properly, if you know about this mechanic.

I cant see you mentioning anything about the exploits and game bugs the griefers abuse, also known as the entire reason other users use a modded game client.

There is also little to nothing Jason can do to help you ruin the fun for others, as the game client is open source.

**Comment by Meeeeparoni** [comment]
Yumlife does not guarantee that one lives until 60. It definitely has tools which make it easier to do so, most notably zoom, which are shared by the other mods which were mentioned in this post. There is also absolutely nothing stopping anyone from taking advantage of these tools should they choose to as it is free to use and open to everyone.

I'd also like to address the "unfair advantage" as you put it. As this is a cooperative game, any "unfair advantage" is surely shared at a minimum by everyone who is a part of the yumlife user's family, if not everyone who is playing the server. The majority of people who supply the server with oil, for example, are yumlife users. I am not sure how the advantages that a player does get through yumlife could be used over another player, unless that player is griefing and/or seeking to ruin others gameplay... the bottom line is that the general effect of players using yumlife is only one that benefits others on the server who are playing the vanilla client.

Plus there's the fact that Jason has supported mod use in the past and has made adjustments to the game in order to make mods easier to manage for those that manage them.

**Comment by Butterbraugh** [comment]
It's a cooperative game, an advantage for one player is an advantage for all. This post is nonsensical 😆

**Comment by Luniatji** [comment]
Mods like Yumlife, Hetuw and AWBZ are made because the game is lacking in some places. Playing in Vanilla is annoying because of the way the game is zoomed in. People have told Jason over and over, but he does not want to zoom because of how the game is looking visual. That is his right. But, other People have the right to want zoom. The game is open source and everybody can make changes.

There are enough players that even with ita installed die before they turn 60. There are also enough People that don't have mods that live till sixty. The question is not "Are mod players better than others because of the mods?". The question you should ask is "Why are so many players using mods instead of Vanilla?". What makes players choose one over the other? What makes them, and Shady yourself, using these mods?

I myself use it because a myriad of reasons, a couple I will share here.

1. It is utterly annoying dealing with a griefer- who most times uses mods themselves,  mostly new players that are annoying dont use it- to have someone see where you are while they are outside of your radius. 
2. It is very, very annoying to find a weapon or arrow, or make one, when you have a tiny view.
3. You can see relatives easy because of the color of their name.
4. Working in the jungle for rubber and don't see the mosquitos.
5. Working on something avances and can't find a tool you need. Like the tarry spot, or the wolf you killed but can not find anymore.
6. A dangerous animal that suddenly turns up and bites you.

All those things can be deadly and/or annoying when playing Vanilla. Beside those points, yes, you could say that it is"unfair " that players with mods will survive more situations like those. It is however the wrong way to look at it. Like I said at the start, players made those mods for a reason.

Just banning them for using it, would be foolish. Because the players that use them are most likely the players who played this game longer and if you turn them away, you will be left with a bunch of new players that will have alot of problems making high tech and kerosene. 

The mods are there for a reason, change OHOL so those reasons are not longer there and they will stop existing.

**Comment by CommunityExile** [comment]
So what I'm suggesting is adaptation, and I want to hear what Jason has to say.

**Comment by CommunityExile** [comment]
> This is obviously not true. Shady is a child and doesn't understand any of the concepts he blabbers about.

Very very **blocked**

**Comment by CommunityExile** [comment]
> People live to 60 cause they know how to yum properly, if you have heard about this mechanic before.
> 
> I cant see you mentioning anything about the exploits and game bugs the griefers abuse, also known as the entire reason other users use a modded game client.
> 
> There is also little to nothing Jason can do to help you ruin the fun for others, as the game client is open source.

Doesn't balancing the game affect griefers, this doesn't even concern griefers. Jesus

**Comment by CommunityExile** [comment]
> Yumlife does not guarantee that one lives until 60. It definitely has tools which make it easier to do so, most notably zoom, which are shared by the other mods which were mentioned in this post. There is also absolutely nothing stopping anyone from taking advantage of these tools should they choose to as it is free to use and open to everyone.
> 
> I'd also like to address the "unfair advantage" as you put it. As this is a cooperative game, any "unfair advantage" is surely shared at a minimum by everyone who is a part of the yumlife user's family, if not everyone who is playing the server. The majority of people who supply the server with oil, for example, are yumlife users. I am not sure how the advantages that a player does get through yumlife could be used over another player, unless that player is griefing and/or seeking to ruin others gameplay... the bottom line is that the general effect of players using yumlife is only one that benefits others on the server who are playing the vanilla client.
> 
> Plus there's the fact that Jason has supported mod use in the past and has made adjustments to the game in order to make mods easier to manage for those that manage them.

The unfair advantage is in the leaderboard just to better clarify.

**Comment by CommunityExile** [comment]
This is between me and Jason, read the note. It's not abusing, I just don't want you near me. You'll only credit yourself.

**Comment by CommunityExile** [comment]
So just to summarize, people do not want new players to be given the slightest advantage in survival because this game is open source??? Shady is totally going to use the concept of giving new players a more balanced advantage to grief??? Just read

**Comment by dreamypearl** [comment]
It is not an unfair advantage to play with a mod that is available for anyone to download, learn and use. If you want to be good at this game it is not using mods that will guarantee it, it is practice, patience and cooperation.

**Comment by CommunityExile** [comment]
Think of this situation in your most advanced state of mind. We maximize what we have to it's fullest potential, as I said they're a minority.

**Comment by CommunityExile** [comment]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/6071ca05-38e2-4f1d-9bda-109cf5f0bad8)
This guy knew what would happen.

**Comment by CommunityExile** [comment]
https://www.onehouronelife.com/forums/viewtopic.php?id=10548 this aged well
