### ISSUE TITLE
AHAP: Implement Single Transferable Voting

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/OneLife#1056]
Content leader voting appears not far off being released. Please consider making some changes to the way these elections appear to have been implemented.

The current implementation appears to award the Content Leader role to the person with the most votes. Given the example where one person gets 40% of the vote and three other people get 20% each: the candidate with 40% of the vote will be elected and 60% of voters will be dissatisfied.

Given there is not yet detail on how someone is nominated, I believe this is a likely scenario where votes are split between many candidates.

STV resolves this.
While this resource focuses on general elections where several candidates will be elected, the learnings still apply.
https://www.youtube.com/watch?v=l8XOZJkozfI

Also consider:
- Compulsory voting
  - Potentially, you get only one life token per voting period until you vote and then you return to the default tokens OHOL uses.
- Nominations
  - As above, vote splitting, and how does someone simply choose who to vote for?
- Candidate campaigns/advertising
  - Why should I vote for one of these candidates? Maybe they can each have a 50 word blurb.
- Lesser frequency of leader change
  - How much can one person achieve in a week?
  - Of course this should be balanced for the case where a "bad" leader is put in place

**Comment by MrMendeleev2** [comment]
I have a feeling something like a Rated voting would work better. 
Since we most likely will be voting for directions for game development to take. And we have 'winner takes all' situation.
STV is used in Proportional representation (not our case). What you recomend is most likely [Condorcet methods](https://en.wikipedia.org/wiki/Condorcet_method) - ranked system with single winner.

I would suggest [Combined approval voting](https://en.wikipedia.org/wiki/Combined_approval_voting). I see it more suited for given circumstances.

**Comment by jasonrohrer** [comment]
Yeah, we will cross this bridge if it ever becomes a problem.

For now, we're going to be lucky to get someone who even wants to be Content Leader, since the job involves a ton of work.
