### ISSUE TITLE
AHAP: Content lead moderation

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/OneLife#1057]
How do you intend to moderate the Content Leader. Will you step in when they remove all git history, content and make a release? How much copyrighted, NSFW or hateful content will you permit?

**Comment by ShadyInExile** [comment]
idk if nsfw even exists in this game.

**Comment by jasonrohrer** [comment]
Content leader can't remove the git history... they don't have that power on github (as far as I can tell... they can't force push).

So we can always roll-back... or the next Content Leader can roll-back.

In terms of copyrighted stuff, or otherwise illegal stuff... I'll leave it up to the community to vote that content leader out and roll back the history as needed.

Why would you vote for a malevolent content leader in the first place?  And if they take a surprise turn, just vote them out.

Votes are only counted for players who log into the AHAP main game servers within the past week, so you won't be able to have a leader lasting long based on "stale" votes from players who are no longer paying attention.
