### ISSUE TITLE
No Way For Players to Take Everything Back to Zero

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#1069]
>  And what if, Edmund suggested, players [emphasis added] were in control of taking _everything_ [emphasis added] back to zero? 

[Link](http://www.onehouronelife.com/forums/viewtopic.php?id=4877)

It does not say that "being naked with no technology".  Not just those things.  It says _everything_.  

Location on the map is a thing.

There is no way for players to take Eve spawns back to where they first started on the map.

**Comment by jasonrohrer** [comment]
Right... but the apocalypse is cool in it's own way, where everyone is just standing there naked, exactly where they were standing, but the world goes back to nature.  I really like that moment in the game.

I just looked into maybe resetting the Eve position after the apocalypse, even if the living people don't move, and the problem is that Eve is always placed to the West of homelands, so as soon as the living people start making homelands again, even if Eve goes back to 0,0 for a bit, she will start pushing West of the new homelands again.

**Comment by jasonrohrer** [comment]
Actually, I will experiment with "leaping" everyone back to 0,0 around the apocalypse.

I do like everyone standing where they were standing but suddenly naked with no town.

But it seems like they could all be "shifted" back to around 0,0, without adjusting their positions relative to each other.

**Comment by jasonrohrer** [comment]
Okay, these changes are in place.

**Comment by teliot** [comment]
is lastEveLocation.txt safe to ignore in all of this?
