### ISSUE TITLE
My issues with the current state of the rockets

### ISSUE THREAD

**Issue by Mosolas** [jasonrohrer/OneLife#1074]
First let me say that I do love the rockets and they are fun to build, but the current state of them is causing some issues that really bother me.

1. Constant drain of resources from towns.
This one sounds rather obvious but its actually a bigger issue than I thought it would be, people are constantly using up water and iron for rockets, but they're also taking trucks and horses and putting them in their own prop fences (which they give access to friends or alts before they die) or they just hide them.
Not to mention you can't even build a radio without it being looted for rocket parts and that there's never any paper in town, even if you make a large batch it will be taken/ used up very quickly.

2. The need to move everything to the specific spots where the launch which is a lot less fun than building the rocket in town like it was when it came out.

3. This one is a smaller issue but I dislike the launch pad notifaction as it ends up very distracting for newbies when you teach, they start asking about rockets and stuff.
This also goes for the rocket cutscene.

As for a solution, I suggest making the rocket launch pad possible for a family to make every 100 generations or something around that number.
That would reduce the resource drain while making sure the town can atually handle building a rocket, there would also be no need to hide/ fence trucks and players would build the rockets in town too.
It would remove the need for a launch pad notifaction as well.
As an added bonus it would add an incentive for players to keep towns alive so they would get to build rockets.

**Comment by jasonrohrer** [comment]
Yes, these are good suggestions.

The way it currently works, with the orbital alignment thing, was kinda just a place-holder to stop the bleeding until a better solution was discovered.

I avoided tying it to generation number.... because that's tough to integrate and solve for edge cases (who is the lucky one who gets to build the rocket?  What if they die?  How long does this rocket-building period last?  etc.)

But yeah, with the way it currently works, every family feels like they need to be "ready" at all times, so they are probably storing a lot of resources in rocket-ready form....

**Comment by Mosolas** [comment]
Thank you for taking your time to respond I do appreciate it.

> I avoided tying it to generation number.... because that's tough to integrate and solve for edge cases (who is the lucky one who gets to build the rocket? What if they die? How long does this rocket-building period last? etc.)
> I got a few ideas on how it could be done.
You could have it so the launch pad spawns somewhere within 500ish tiles of the family well, which does mean if a family moves into a different town the launch pad won't spawn near them, though that might be a positive as it gives players an incentive to build up and live in their Eve town.
you can also make so it's not a set number like 100, but have it so after 100 generations the launch pad *can* spawn but it's not in a set genenration, it could be at 100 or 125 or 160 and no one will know it spanwed untill someone runs into it.
After it spawns you would need to wait something like another 50 generations before it spawns again.

> But yeah, with the way it currently works, every family feels like they need to be "ready" at all times, so they are probably storing a lot of resources in rocket-ready form....
> Rather than each family getting "ready", it's specific groups of people (which I have nothing agaist) that want to give the rocket to themselves or thier friends, the family's don't get access to those recources/ rocket parts.

**Comment by Mosolas** [comment]
Thank you for taking your time to respond I do appreciate it.

> I avoided tying it to generation number.... because that's tough to integrate and solve for edge cases (who is the lucky one who gets to build the rocket? What if they die? How long does this rocket-building period last? etc.)

I got a few ideas on how it could be done.

You could have it so the launch pad spawns somewhere within 500ish tiles of the family well, which does mean if a family moves into a different town the launch pad won't spawn near them, though that might be a positive as it gives players an incentive to build up and live in their Eve town.
You can also make so it's not a set number like 100, but have it so after 100 generations the launch pad *can* spawn but it's not in a set generation, it could be at 100 or 125 or 160 and no one will know it spanwed untill someone runs into it.
After it spawns you would need to wait something like another 50 generations before it spawns again.
> But yeah, with the way it currently works, every family feels like they need to be "ready" at all times, so they are probably storing a lot of resources in rocket-ready form....

Rather than each family getting "ready", it's specific groups of people (which I have nothing against) that want to give the rocket to themselves or their friends, the family's don't get access to those resources/ rocket parts.

**Comment by Tarr-OHOL** [comment]
Honestly, I think it’s kind of nice having an actual resource drain like a rocket. Instead of something like nerfing numbers having some sort of object like the rocket gives iron a meaningful (I mean at least to one person lol) use besides just being another truck. 

I agree I think it’s cool to have the rockets in town for people to see. Maybe have the landing pad require 6 hours of prep time to be used once created in town? This stops people from at least hiding all the trucks and horses behind areas fenced far away from town. You’ll still never get access without an old person sneaking you through fences or being in the cool kids club of who is making the rocket but at least everyone gets to see the progress.

**Comment by jasonrohrer** [comment]
Yeah, I still want to space them out in a forced way somehow.

It's not great to have 5 rockets go off in a single hour.

So it can't just "take 6 hours to mature", because that could mean that you start 10 rocket pads at the same time, wait 6 hours, and then launch them all together.

Any kind of maturation time, no matter how long, doesn't control the FLOW of rockets into the game.

Currently, there are like 5 a day.  That's a good rate.

So... what I'm thinking is that the "orbital alignment" thing will be a star-chart or something, that you can go to the X in the woods with a piece of paper, and bring back a star chart.

But then... maybe you MUST build it in a tight radius near other people, somehow.  So you have the star chart, but the you can only build the pad if 10+ people are nearby.


So I can still limit the flow of rockets into the game by only allowing one star chart to be made every 5 hours or whatever is appropriate.

But they will be built in towns and launch from towns.


Regarding "wasting" town resources on rockets..... well, a town that really cares about survival might outlaw rocket production!

**Comment by jasonrohrer** [comment]
My attempt at fixing this is here:

https://github.com/jasonrohrer/OneLifeData7/commit/d45ac7357316cd845a4ef828733df22c12b5541f
