### ISSUE TITLE
Server numbering logic confusing

### ISSUE THREAD

**Issue by GnihtonSeodYdahs** [jasonrohrer/OneLife#1092]
![image](https://github.com/jasonrohrer/OneLife/assets/171100996/4214d3e5-029c-4523-8ab2-63d7b2c8ff49)
Why not give bigserver big numbers, why is server bigger than big server????

**Comment by GnihtonSeodYdahs** [comment]
Not like it really matters though

**Comment by jasonrohrer** [comment]
Yeah... this is vestigial...

BigServer2 is actually a high-memory and high-performance server node, which was an experiment in testing how many players a server could actually support with better hardware. It's "big" because of the hardware.

The other servers are all running on the same low-end hardware... they had different numbers of max players for no good reason.  I just fixed that.

And BigServer2 is called "2" because it was actually the second BigServer experiment.

**Comment by GnihtonSeodYdahs** [comment]
oh

**Comment by GnihtonSeodYdahs** [comment]
That makes sense

**Comment by GnihtonSeodYdahs** [comment]
Do you got one of the fat servers? Or do you got a Microserver like the one my computer runs on?
![image](https://github.com/jasonrohrer/OneLife/assets/171100996/3863e7cb-8fa8-447f-85c4-7b09e8f038ef)
