### ISSUE TITLE
we don't have  OneLifeServer file

### ISSUE THREAD

**Issue by xiy2** [jasonrohrer/OneLife#1097]
I want to create custom server. When I execute  serverPullAndBuildLinux.sh 
The follow word come out:
 
echo
echo
echo "Done building server with version v$serverVersion"

echo
echo "To run your server, do this:"
echo
echo "cd OneLife/server"
echo "./OneLifeServer"
echo

but we don't have OneLifeServer file, Please check if it lost

**Comment by Lonick32** [comment]
+1

**Comment by jasonrohrer** [comment]
So... the OneLifeServer is created down inside the "server" folder.

That's why you need to do "cd server" after building to get into the server folder.

I just tested it, and it's working for me on Linux.

If that file doesn't exist down inside the server folder, are you seeing some kind of compile error during building?

**Comment by xiy2** [comment]
Thanks for your reply.
The OneLifeServer file exists now. And server start successfully!
But it's true OneLifeServer file doesn't exist two weeks ago, even in github.

**Comment by jasonrohrer** [comment]
Yes, that file needs to be built from source code.  It does not exist in Github.
