### ISSUE TITLE
Waystones post apoc doing funny stuff

### ISSUE THREAD

**Issue by teliot** [jasonrohrer/OneLife#1103]
[Stones kinda not working](https://cdn.discordapp.com/attachments/498293923576283146/1261168102998147102/image.png?ex=6691f9d3&is=6690a853&hm=856c8df55271c9690a9f1076ddb3ce6aab8f5d0d2dff81f8ea47a58552e19ac9&)

**Comment by teliot** [comment]
[Brown fam points the other way. will have to check logs to see if not everyone got teleported](https://cdn.discordapp.com/attachments/498293923576283146/1261179878900764767/image.png?ex=669204ca&is=6690b34a&hm=44d5e4a19ee9eae7cd1c999bd7723342a4a86eb083c5d83dfd92eeea519f3029&)
this brown fam was was a post apoc eve

**Comment by DougLefelhocz** [comment]
Conversation between Reformed and Spoonwood:

"New2PC — Yesterday at 10:14 PM
tell jason his code is fucked
it didnt reset spawns to 0

Spoonwood — Yesterday at 10:14 PM
huh?

New2PC — Yesterday at 10:14 PM
just tped us to 0

Spoonwood — Yesterday at 10:15 PM
seriously?

New2PC — Yesterday at 10:15 PM
the apoc
yea tell him
im banned from discord

Spoonwood — Yesterday at 10:15 PM
it teleported you, but didn't reset Eve spawns."

I tried to tell you the content of that message [shortly before](https://discord.com/channels/328215300279500800/328215300279500800/1261143908407054336) you logged off also... although admittedly trusting the source makes for another matter, since I didn't have any observations.

You put in a fix so that Eve spawns [would](https://github.com/jasonrohrer/OneLife/issues/1077) [reset](https://github.com/jasonrohrer/OneLife/commit/e8e3e67f725b0823dad28148421cd883b042c43a) after an apocalypse.

**Comment by DougLefelhocz** [comment]
> this brown fam was was a post apoc eve

There was another one before that which lived through the apocalypse.  [Hawk family](http://lineage.onehouronelife.com/server.php?action=character_page&id=10565052).  But, when I got born there, the spot where we had a ready well site made, but it had no iron unlocked by that.  I theorized at the time that such happened, because they had already had their iron unlock.  But, I'm not sure, as it's possible that maybe someone else just unlocked iron elsewhere.

**Comment by DougLefelhocz** [comment]
Also, is this the stones not working... or Eve spawns not resetting?

**Comment by teliot** [comment]
logs will tell all

**Comment by Tarr-OHOL** [comment]
Not reading spoons post. Jason made it so when apocalypse would happen people would be teleported to the center of the map. Issue is the Eve spawns didn’t move so when new families spawned they just went back where they were lol.

**Comment by jasonrohrer** [comment]
Yes, Eve spawns are broken, fixing now.
