### ISSUE TITLE
Tutorial confusion about tips on /recipes

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#129]
I've been watching streamers play the game and i systematically see them use the /recipe for example /axe
thinking that they will get the recipe without holding an object related to the recipe

I replayed tutorial and this part is confusing and doesnt specify that you have to actually hold an object related to that crafting recipe for the /recipe to be shown

also there is bugs in the recipes for example using /hatchet and holding a leaf gives a match to make hatchet which doesnt make sense since hatchet doesnt need a leaf to make it (probably because it has the word "shaft" in "emmber shaft" which is related to the short shaft in the hatchet making or maybe because the ember shaft is on the long straight shaft which is used to make short shaft, but ember shaft is not related to hatchet making)

**Comment by Dodg-e** [comment]
I've also seen a streamer,light up the fire but  not light up the torch and go to the next part of the tutorial, getting stuck in a loop without being able to be born out of tutorial

**Comment by swallis21** [comment]
The biggest problem with the /recipe helper IMO is bone needles. It's very difficult to get the tutorial to tell you how to make them (particularly because /needle matches with needle and thread before 'bone needle'), and the bellows are extremely difficult for new players because of it. A new player also has no idea snares are how you kill rabbits, and /axe doesn't give any results for clicking on a family rabbit hole even though it should say something like Snare + Hole -> Snared Rabbit, just like it would on onetech.info.

**Comment by jasonrohrer** [comment]
The filter thing was dramatically improved a few updates back.

I also did some work on the the tutorial to really make people aware that lighting the torch is the way out.
