### ISSUE TITLE
[Feature Request]  Anchored Ghosts

### ISSUE THREAD

**Issue by rannmann** [jasonrohrer/OneLife#134]
After death, stay spawned as a "ghost" with an option to leave this world (to the current menu).  Allow the ghost to travel N squares in any direction from their corpse to avoid cheating with multiple players.  They cannot interact with anything nor speak as a ghost.

In the future, allowing ghosts to communicate with one another could be cool, and might help extend the social aspect of the game since you can chat with former players in the area without worrying about starving to death.

**Comment by swallis21** [comment]
I had a similar idea, except that you could live up to 1 hour after your death as a ghost (mostly to see if your children carry on your legacy and whatnot) and could "ghostly whisper" 60 characters before you're silenced forever. The whisper would be especially helpful when some griefer puts a knife in you just outside a busy town and no one pays any attention when you drag your screaming, bleeding corpse through the town center. If you can't get their attention and get them to curse your killer in 30 seconds then they get away with it scott free. Being able to haunt them as a ghost and tell them to curse your murderer would help punish people who deserve it. (And it's important, especially with the new more lenient curses, because the only time I've seen someone get mass cursed for their wanton murdering was when they stabbed a bunch of people in the middle of a busy farm.)

HOWEVER it would also allow griefers to spread FUD after they die so take it as you will.

Adding ghosts would be really nice because it increases the chance you might see your descendants building something to honor you after you pass. I've made quite elaborate graves for my mother before, and it's too bad they'll likely never see it.

**Comment by jasonrohrer** [comment]
Yeah, this is an excellent idea.

However, I decided against it a while back for a few reasons.

1.  I don't really want supernatural stuff in the game (this is a game that's about real life, mostly, except reincarnation, which is an necessary evil in a game that sells for $20).

2.  I want your LIFE to be special, and the mystery about what happens after you die to be preserved.  Your only window into the worl is by living in there.  Dead is dead.

**Comment by swallis21** [comment]
Fair enough!
