### ISSUE TITLE
Snowballs

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#176]
Snowballs according to onetech are coded as deadly

**Comment by ryanb** [comment]
I looked into it and I don't think this is a bug in OHOL. The snowball object has a `deadlyDistance`, but this may be intentional as a way to add the splat emote.

Looks like the [Splat Emote](https://edge.onetech.info/2405-Snowball-Splat-sick-emot_8_10) has "sick" in the title, just like the [Yellow Fever emote](https://edge.onetech.info/2155-Yellow-Fever-sick-emot_7_35-food_0-3) does. I assume this defines if the object is actually deadly.

I'll need to update onetech to do that.

**Comment by ryanb** [comment]
This has been fixed in onetech, so you might want to close this @Stylingirl.

https://onetech.info/2407-Snowball

**Comment by jasonrohrer** [comment]
Yeah, this is a hack, but it works.

Thanks, ryanb!
