### ISSUE TITLE
Disconnect on malformed MOVE message instead of insta-killing

### ISSUE THREAD

**Issue by thundersen** [jasonrohrer/OneLife#194]
...to prevent using malformed MOVE messages as an exploit.

Awbz uses this for his insta-death command and some players use this even if they are a baby in their mothers' arms. I have had babies collapsing from my arms into bone piles, which is very unfortunate in some situations, because it doesn't reset the birth cooldown.

I agree with awbz that people will suicide no matter what, but this exploit is just annoying for some mothers.

CrazyEddie has already suggested it in a comment [here](https://github.com/jasonrohrer/OneLife/issues/181), but that was after you closed the issue, so I'm opening a new one.
I have also [asked awbz to disable the command for babies](https://github.com/Awbz/OneLife/issues/51) and he is considering to at least send /die instead of malformed MOVE, if /die preconditions apply.

**Comment by CrazyEddieTK** [comment]
Before you fix this, let me add that perhaps it shouldn't be fixed, and you should instead consider officially allowing instant suicide even outside the current conditions for /die. I originally mentioned this as a potential bug because it seemed like an oversight, inconsistent with your intentions. But perhaps you could consider your intentions further here.

I see the core of the issue being that someone who wants to suicide will do so no matter what by eventually running away and starving. Preferably they will use /die, but there are situations where /die can't be used. In those cases, players will use the (unintentional?) insta-death, and if that is not available they will simply run away and wait to starve. Formally supporting insta-death would be a benefit in those situations.

A counter-argument is that sometimes players are using insta-death when they could /die instead, and are thereby putting their mother on baby cooldown unnecessarily. An officially supported insta-death (or rather, a /die that was usable under wider circumstances) would address that concern.

This issue was argued at great length [here](https://onehouronelife.com/forums/viewtopic.php?id=4990). That particular thread was much more contentious than informative, but if you skim it you can get some perspective on the complaints from all sides.
