### ISSUE TITLE
client issues

### ISSUE THREAD

**Issue by laccy** [jasonrohrer/OneLife#203]
sometimes client writes the email with all big letters
if you make an error writing the email address, it will say error each time you land on login screen
the playback will record any movement of mouse between games, even outside ohol, and with new family trees button it can even open the website which i guess it's a flag for a lot of antiviruses, i don't know if it can actually click something else but its weird anyway
also pretty bad, to replay them as you cannot control or fast forward it, so essentially people need to exit game after each game if they want the recordings, and things only happen when they didn't expect it 
if i find a bug, i wont wait that long to find the recording of it 

and sorry for my other topics, i think i put them in the wrong directory

**Comment by jasonrohrer** [comment]
Well... the recording system is a true simulation of recorded events, so this makes it very powerful (an actual sim of exactly what happened, including any triggered bugs), but also limited (you can't fast forward because no game state is recorded).

I don't think it records mouse events that occur outside of the game window...

If you are using capslock for your email, probably turn capslock off, right?
