### ISSUE TITLE
Tweak to curse algorithm to address minmaxers

### ISSUE THREAD

**Issue by CrazyEddieTK** [jasonrohrer/OneLife#204]
The current curse algorithm, described [here](https://onehouronelife.com/forums/viewtopic.php?pid=36345#p36345), was intended to more heavily punish repeat offenders while giving new players lighter punishment in hopes that they will reform:

> So you can see that the repeat offender, who keeps bothering people as a way of life, will eventually serve 5 hours every time they bother people.  A brand new player who tries something once will spend a half hour in Donkey Town.

But what actually happens is that repeat offenders know that they can do things that will earn them curses, without consequence, as long as they keep their curse rate below one per hour on average. There are a few highly-skilled, long-term players that constantly do things that they know will earn them curses. They know exactly what earns them curses and exactly how many curses they have at any point in time. They temper their anti-social actions when they start approaching the 8-curse threshold, but take larger risks when their curse count is low.

I don't believe the curse system was intended to allow people to bother other people at a constant rate, forever, as long as they stay just barely under the trigger threshold. But that is exactly what some players do. Their playstyle includes bothering people as a way of life, they just know to temper it just enough to stay below the threshold.

I suggest that as people's lifetime curse score rises, not only should the length of their sentences increase, but the Donkey Town trigger threshold should also be lowered, so that over time they have less room in their buffer for anti-social actions and have to live with a greater risk that at any time they could be sent to Donkey Town should they do something that bothers other people.

**Comment by laccy** [comment]
in my perspective is quite reverse
new players curse randomly, mostly because someone has clothes on him and knife
doesn't matter if he made it, doesn't matter if you work your ass off
killings are fine, cursing doesn't solve anything
i would be totally fine if people try to kill me
but don't even expect that you curse me and frame me and i let you live
curses cost nothing, except 2 hours of played, so people curse on slightest offense and they are way too sensitive, and nothing prevents you from cursing if you are the one who made a mistake/lost a duel
you don't even understand what you did wrong and if someone tells your mistake you just tell fuck off and continue ruining the camp, you totally deserve to be killed

killing was invented, allowed and kept as anti griefing, as it stops griefers ruining camps

being antisocial isn't inferior to social behaviour
logical thinking and problem solving keeps people alive
keeping all kids, feeding everyone pie, who is sick and everything based on feelings and roleplay is a waste of others work, time and therefore more annoying to a select few who spends his time working for community rather than walking around, talking and plotting. it requires a lot of self restrain to ignore or tolerate this people. also if you do nothing, you got more time to frame others who happen to mention that you ruin their work.

this famous cursers tend to be the one who start this arguments and keep it up for the whole 120 minutes until the other person can be cursed. they tend to never play as male, and die at 40 and other life, other family try to blackmail kids into cursing.

just for example me and tarr kill minimum 20 people weekly, and never for fun, mostly because they tend to be big mouthed new players who want to ruin the camp either by accident or intent, and refuse to learn or think logically.

every long lineage so far had us at some point and that's a lot of advanced buildings, long lineages, and ordered cities, so if this takes a few sacrifices, its still better than poor newbees killing off lineages and ruining others fun.

its not a good system and doesn't guarantee that negative behavior gets punished, the ones who curse on sight, don't even consider the situation and overpower others who got reason to get rid of griefers. the most common reason to curse  that you do or say anything to someone related to them ingame. i tend to not believe 8 year old kids with weapon over productive members, but more than 90% of time daughters back up their griefer mother, or mothers their griefer kids.
don't pretend that you don't bother others, higher skill means better fow, faster actions, better judgement.

**Comment by ghost** [comment]
Actively remade my github account to reply to this. You do know anywhere from 1/3 to 1/5 of my total curse score comes from that apocalypse run right? I don't think anyone has been trying to game the system in the first place like you are implying people do. At some point players have to step up and remove bad eggs from the camp/village at the price of a curse here and there which I'm totally fine with in the end due to how the current system works. You either let people grief the village and ruin it for all the new/intermediate players or you remove the troll/uncooperative person. You can't keep someone around who refuses to change a bad behavior (shearing all the sheep, force feeding pies, etc) as it screws everyone around them.

As stated above because curses come so frequently people will throw them around almost needlessly. Uh oh someone ate MY berry! CURSE HIM. On the other hand we do have an issue with random trolls absorbing some amount of curses as almost every life one to three people will do a random murder either claiming accident, or not even speaking at all. While the system isn't perfect by any means its much better than the marked system.

**Comment by Leonard2** [comment]
> I don't think anyone has been trying to game the system in the first place like you are implying people do.

This is quite the irony.
Read this paragraph very carefully.

>But what actually happens is that repeat offenders know that they can do things that will earn them curses, without consequence, as long as they keep their curse rate below one per hour on average. There are a few highly-skilled, long-term players that constantly do things that they know will earn them curses. They know exactly what earns them curses and exactly how many curses they have at any point in time. They temper their anti-social actions when they start approaching the 8-curse threshold, but take larger risks when their curse count is low.

You might begin to realize that you literally fit into that category.

> At some point players have to step up and remove bad eggs from the camp/village **at the price of a curse here and there which I'm totally fine with in the end due to how the current system works**.

You ever thought that maybe the reason you get cursed is precisely because people know what you're up to?
Maybe, they fundamentally disagree with the way you deal with people whom you deem a "bad egg" through your own personal judgement?
Maybe you deserve those curses in the end.
Maybe all the people see is a self-righteous guy on a crusade to purify towns while playing god.

>As stated above because curses come so frequently people will throw them around almost needlessly. Uh oh someone ate MY berry! CURSE HIM.

From all the hours I've been putting into this game curses are absolutely not abused as much as you make it out to be.
If all the people see is a guy with a knife wound asking for a curse on his murderer you will get at most 2 or 3 curses.
Unless someone is flat out murdered in front of everybody without even an attempt at an explanation by the perpetrator, then you can expect much more.
In fact, I've actually seen the opposite. People would MUCH rather take matters into their own hands and stab people rather than use the curse system for what it was designed for. Even you yourself fall into this category.
It's kinda like a point previously mentioned here, the idea that killing was made as a measure to stop griefing.
This is a very naive idea.
The griefers can and will use knives as much as the people who will use them against them.
It's as much a problem as it is a problem solver.
To put things into perspective, as was already described, there are griefers who will keep under the radar and grief while still being quiet.
They will hide things away, build useless and unremovable buildings, or just kill people who are defenseless and too far away from civilization.
And no amount of self-claimed cops will solve this issue.
Where are the self-claimed cops when I'm killed by a griefer who gets his last kill of the day before meeting his quota?
This isn't how you deal with such a problem.
And the fact is that if Jason himself thought the same way you do, there wouldn't even be a curse system in place today.
Implementing what is being suggested here _would_ actually make it possible to deal with those people in a reliable way.

> You do know anywhere from 1/3 to 1/5 of my total curse score comes from that apocalypse run right? 

This hints at something worth discussing too.
This unfortunately I don't think is addressable.
It's a tradeoff you have to accept as soon as you implement a curse system such as this one.
When you give people a tool to deal with griefers and then you implement a mechanic that a good part consider as bad as griefing, you bet they will use that tool.
I don't think there's any way around this.
To be honest, if you implement a mechanic in your game that a good part of people consider as bad as griefing it should be up to you to find a solution to this.
I don't personally curse people who try to achieve apocalypse but if enough people do it so that it becomes a problem then maybe you should start thinking of a solution.
Something like apocalypse locality, which is way more relevant than ever now with the new bigserver.

**Comment by CrazyEddieTK** [comment]
I didn't intend for this to become a discussion on the merits of the curse system. I wanted to point out what I believe was an oversight in Jason's original intention.

I'm sure Jason has everything he needs to decide whether or not to implement my suggestion.

**Comment by BlueDiamondAvatar** [comment]
> I don't believe the curse system was intended to allow people to bother other people at a constant rate, forever, as long as they stay just barely under the trigger threshold. But that is exactly what some players do. Their playstyle includes bothering people as a way of life, they just know to temper it just enough to stay below the threshold.
> 

I am attaching a link to this forum thread as I think that lu and Bob 101's comments are firm evidence that folks are indeed, continuing to grief at a constant rate to stay just below the DT threshold. 

https://onehouronelife.com/forums/viewtopic.php?id=5200

**Comment by jasonrohrer** [comment]
This is all interesting....

But how do we prevent innocent people from being caught in the same net?

The more someone plays, the more likely they are to accumulate a large total curse score over time.  Lets say that they interact with 100 griefers over time, and each on curses them.  So their curse score is 100.

Well, I guess this is pretty rare.  Out of 34000 players registered with the curse system, there are only five people with a total score over 100.

There are, however, 770 people who have gotten at least 8 total curse points (who knows whether all of them saw d-town, but no more than 770 have been sent to d-town).  That's 2% of the players.

So yeah, I think it is possible to have the d-town threshold drop as the total score rises.

**Comment by jasonrohrer** [comment]
This is live now.  To make it fair, I wiped everyone's current curse score (not their total).  So if the were serving a sentence, the sentence is over (and is not longer that it should be, due to the new code).
