### ISSUE TITLE
custom server stop working

### ISSUE THREAD

**Issue by baniyasi** [jasonrohrer/OneLife#212]
I download OHOL+_v193_win_full, launch OneLife.exe and OneLifeServer.exe, connected successfully, but the server process stop working, why
the log stay at "Need to send updates about these 1 players:"

**Comment by Awbz** [comment]
As your issue pertains to the modded release(s) that I provide, it belongs over [here](https://github.com/Awbz/OneLife/issues), but the problem is likely due to missing data folders.

In the server folder, you'll either need to create symlinks (preferred method) or copy in the following:
***..\categories  ..\objects  ..\transitions  ..\tutorialMaps***  and  ***..\dataVersionNumber.txt***

The runServer.bat file in the v195 release should attempt to create these symlinks for you, but you'll have to run it at least once as an administrator unless you have Developer Mode enabled on Win10.  Hope that helps!
