### ISSUE TITLE
Temperature Problems

### ISSUE THREAD

**Issue by Stylingirl** [jasonrohrer/OneLife#224]
Multiple players reporting that it's nearly impossible to play and survive in any biome due to temperature changes.

**Comment by Mcjoshinz** [comment]
Can confirm, the temperature is unbalanced. When you spawn your temperature is normal and slowly decreases / increases depending on biome until it reaches an extreme point. Afterwards when you walk between biomes (1 square is all it takes) and your temperature is instantly HOT / COLD in the 90% / 10% position on the temp guage.

**Comment by Mcjoshinz** [comment]
Clothes also don't affect temperature.

**Comment by dogwolf12** [comment]
Can confirm. Deserts and jungles are now the causation of swift death, so you have to stay in colder biomes, which are a bit better, but still death incarnate. if you find an abandoned town, you have to run in then out. Because of this update, you either spawn an Eve or an Eve's child - no lineage makes it past early gen. 3.

**Comment by Mcjoshinz** [comment]
Its not so extreme as we initially thought. The new feature of "heatshock" certainly bamboozled us tho.

**Comment by jasonrohrer** [comment]
This has been changed quite a bit in the forthcoming update also.
