### ISSUE TITLE
Snowmen don't provide radiant heat

### ISSUE THREAD

**Issue by CrazyEddieTK** [jasonrohrer/OneLife#232]
It looks like snowmen and other negative heat sources no longer provide radiant heat.

nerfsnowballsnow reported the symptoms [here](https://onehouronelife.com/forums/viewtopic.php?pid=45486#p45486) and betame pinpointed the responsible line of code [here](https://onehouronelife.com/forums/viewtopic.php?pid=45489#p45489) .

[This](https://github.com/jasonrohrer/OneLife/blob/7935b09d58f51294d30ad256f3c30b78c95a0280/server/server.cpp#L2513) is the code in question.

Note that although they no longer provide radiant heat, it looks like they do provide convection heat (I think, based on reading the code; I haven't tested it).

**Comment by jasonrohrer** [comment]
This was intentional.

There is no such thing as "radiant cold."

Facing a fire from across the room warms your front, but not your back.

Facing a snowman from across the room doesn't "cool" your front in the same way.  There are no "cool" rays.

However, having a snowman present inside a room will cool the whole room, due to convection.
