### ISSUE TITLE
Can't close the game when minimized

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#239]
On Windows 10,

Game doesn't allow you to close it when it's minimized. When I try to close the game by right clicking on it in the taskbar and hitting 'Close window', the game won't close. I have to open the game and hit % to quit and finally close it.

**Comment by jasonrohrer** [comment]
Yeah, the game is confirming that you really want to quit.  This is normal.

The way it's handled may not be normal, because it's not popping up a dialog box when you try to close it....  but it's popping up a dialog box in-game.

This is a platform-independent game, so....  it does its best to work the same way everywhere.
