### ISSUE TITLE
convertDB script throws errors in opening DB files

### ISSUE THREAD

**Issue by cuff-links** [jasonrohrer/OneLife#25]
When I run the convertDb.sh script, I get an error opening every KissDB file. They are all present, but it says they can't be opened. Is there another way to address this?

**Comment by jasonrohrer** [comment]
That means they've already been converted, I think.

Are they not getting opened correctly by your game server?

**Comment by cuff-links** [comment]
They are not, unfortunately.

**Comment by jasonrohrer** [comment]
So the latest game server code complains about them?

If you run:

`head -c 3 map.db`

You will see "Sdb" as the first few characters if they are already converted.

If you run:

`head -c 3 playerStats.db`

You will see "Kdb" as the first few characters, because playerStats is left as a kissDB in the latest code.

Note that this will appear at the start of your next prompt, so it's easy to miss.  Mine looks like this:
```
jasonrohrer2@latitude:~/checkout/OneLife/server$ head -c 3 playerStats.db
KdBjasonrohrer2@latitude:~/checkout/OneLife/server$
```

But anyway, if your DB files are not converted, they will all have "Kdb" when you look at the first 3 characters.

If you are seeing Sdb correctly on all of them, then the question is, why is your server not opening them?  Are you sure your server has been rebuilt properly?

**Comment by cuff-links** [comment]
The mapfile has been converted. SDB shows for the map file and kdb shows for the playerStats file. I am sure that the server has been rebuilt properly because we have all of the new content from the update. Burdock and other wild foods are there. Just missing the actual map data. I SCPed my files from my server to my local machine to be able to add it to this issue.

**Comment by cuff-links** [comment]
<img width="1287" alt="screen shot 2018-04-18 at 1 34 29 pm" src="https://user-images.githubusercontent.com/1432078/38948389-785ee888-430d-11e8-9bc8-67b6808425f5.png">

**Comment by cuff-links** [comment]
Here is the db file. 

https://nofile.io/f/ACBvx87s2wz/map.db

**Comment by jasonrohrer** [comment]
Sounds like you just need to recompile your server.

The db files have been converted to STACKDB, but the server is still trying to open them with KISSDB.  That means the server is still running old code.

**Comment by cuff-links** [comment]
@jasonrohrer Did the file work for you? I reran the ./pullLatestAndBuildTestServer.sh file. Should that not have rebuilt the game? It's still not working.

**Comment by jasonrohrer** [comment]
Sorry for the trouble...

That nofile link seems to have expired.

When you launch your server, what is the exact error message you are seeing?

Can you post that text here?

**Comment by cuff-links** [comment]
Ok. I started fresh with a new clone and a new server and it worked this time. Not sure why. Gonna close this one.
