### ISSUE TITLE
PLAYER_UPDATE messages reveal full map coordinates

### ISSUE THREAD

**Issue by CrazyEddieTK** [jasonrohrer/OneLife#251]
Per [this post](https://onehouronelife.com/forums/viewtopic.php?id=5359) by gondor2222:

> As far as I can see from printing PLAYER_UPDATE messages to stderr, these messages give you the exact current location of every player on your server, relative to the tile of your birth. I recommend these update messages be filtered so players only receive updates for nearby players, because the current system allows:
> 
> Easy identification of exact town locations (including the tutorial) relative to your current position, by clustering players
> 
> Approximate global coordinates: by saving your player ID across lives and looking up the lineages of other players in these distant towns, a hit in the lineage will tell you exactly where that town from your past life is relative to your current location.
> 
> Exact location of any living player, and their place of death once they die (e.g. griefers)

Players are currently using this information to find the towns near them for any given spawn and then travel there directly, including going back to working on "their" projects in "their" towns.

As gondor suggests, you may want to consider filtering the update messages on the server so that clients only get messages about players near them.

**Comment by jasonrohrer** [comment]
This "global" update message is only sent to you once, when you first connect to the server, telling you who's on the server.

And then also whenever a new player joins, or when a player dies.  These are "global" messages.

Other than that, you never hear about these players (you only get info about nearby players).

The client is currently coded so that it "needs" to know about all players on the server, even ones that are not nearby.

So, I will fix the server to put "dummy" coordinates in that message for players that are too far away.

**Comment by jasonrohrer** [comment]
There is a bit of a weird problem here that I currently don't know how to fix:

Information about new graves is currently sent to everyone, even for out-of-range graves.  This includes the position of the grave (so that the client can remember to show the right label on the grave if the player ever mouses over it).

This is sent to all players because I never know when some player will later walk into range of that grave and mouse over it.  So their client needs to know where it is.  The server doesn't remember this and tell the client about it later, once the client walks into range.

This is a small leak, and less crucial than the Player Update leak, but it's still a leak.

**Comment by gondor2222** [comment]
Can you increase these fake coordinates to further away than 1977, 1977? Right now it's still close enough that a player might stumble across it following a bell tower or just walking northeast, and you actually see all of the players standing at that location performing the actions they're actually doing, which is a bit unsettling and might mistakenly be flagged by other players as a bug.
