### ISSUE TITLE
Feature request - Perspective View Toggle (vs Current Isometric View)

### ISSUE THREAD

**Issue by AndrewBrownK** [jasonrohrer/OneLife#252]
I would like to raise a low priority feature request or discussion. 

Right now all the landscape is completely square, top down. However the character and object art all stands upright. Or if you think about it, not upright, but North.

What if instead of the landscape rendering square (top down, vertically), it rendered trapezoidal (top down at an angle)? This way the directions "up" and "North" are aligned naturally instead of forcibly.

Forgive if this is a vague description without familiarity of pertinent code files, but here is the work I imagine would be entailed.
- Things are rendered slightly smaller at the top of the screen and slightly larger at the bottom of the screen
- Tall objects do not experience warping by being smaller at top and larger at bottom, they are the correct size for whatever tile they are rooted on.
- This implicates a natural parallax effect for tall objects
- This could provide a drastically **different** (not inherently better or worse, just definitely different) look and feel from the current square landscape. Therefore it's probably a good idea to add a toggle for this feature. Or otherwise make it optional in some way (like a mod?)

**Comment by jasonrohrer** [comment]
All the artwork in the game is currently rendered pixel-perfect, with no scaling or warping.

This is a huge change you're suggesting here.  Probably best left to a mod, if someone wants to try it.  This is the way that Don't Starve is rendered, by the way.  I wanted my game to be pixel-perfect, with very sharp pen lines, instead.

Also interesting (without any graphical changes) is a mod that "rotates" the view in 90 degree increments, so that North becomes West, etc.

But even something as simple as that would break walls and doors, which are currently different objects, hand-drawn, for the NS vs EW versions.
