### ISSUE TITLE
Arrows getting deleted

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#265]
When hunting a person with bow and arrow - can become necessary due to griefer attacks - the arrow can get deleted:
First, the intended mechanics probably is that when someone fails to hit with the arrow, that the arrow gets put on the ground where one has clicked.
The problem however is, that when this tile is already occupied that the arrow gets deleted then.
I see no other solution than simply avoiding that problem by letting the arrow stay in the bow.

**Comment by ghost** [comment]
Maybe one can modify the feature by spawning the arrow nearby in a straight line until a free tile is found. Depends on how easy that is to implement

**Comment by gitbirb** [comment]
I saw this happen once to me. I had an arrow with a note that i wanted to use to bloody the note on a griefer, but he had a knife wound and it just disappeared when i shot him for whatever reason. Probably because of this bug, so i instead had to get a new note and a new arrow because both disappeared, and sacrificed a griefer twin to make the note stand out more and be remembered.

**Comment by jasonrohrer** [comment]
This has most likely been fixed with the new KILL semantics, where it's impossible to miss.
