### ISSUE TITLE
No way to fast forward replay

### ISSUE THREAD

**Issue by JkHowling** [jasonrohrer/OneLife#276]
Currently the replay function leaves something to be desired: navigation

Right now, my only option to check something that happened in my life is to simply sit through 30-40 minutes, sometimes much longer. This is rather annoying on both my end as a player, and your end as a developer, surely? 

Some sort of ability to toggle a speedup function would be very appreciated. Let me toggle 2x, 3x, maybe 4x speed so I can skip through the majority of the irrelevant to find what I was looking for, yeah?

**Comment by jasonrohrer** [comment]
enableSpeedControlKeys.ini

You also need to disable vsync in your graphics card.

Then these keys control speed:

^ & * ( ) -
* is normal speed, each key to the right add 2x speed factor.  Each key to the left add something like 1/2 speed factor.

Because of the way the replay system is written (simulating actual input events), it must simulate the entire thing frame-by frame, and can't jump ahead in time.

Thus, playing the frames back faster is the only way to speed it up.
