### ISSUE TITLE
Possible memory leak in killMessage

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#311]
I may yet be missing something, but I notice that killMessage is autoSprintf and sendToServerSocket. Other places that do this immediately delete the message.

**Comment by hetuw** [comment]
nice catch Justin, i made a link to the line: https://github.com/jasonrohrer/OneLife/blob/OneLife_v231/gameSource/LivingLifePage.cpp#L19159

i have a general programming question:
I see jason uses autoSprintf to create a char array and then deletes it with delete[], like this:
```
char *message = autoSprintf( "MAP %d %d#",sendX( mapPullCurrentX ),sendY( mapPullCurrentY ) );
delete [] message;
```
the same could be achieved like this:
```
char message[64];
sprintf( message, "MAP %d %d#",sendX( mapPullCurrentX ),sendY( mapPullCurrentY ) );
```
In the second example, the message gets deleted as soon as it goes out of scope so you dont need to worry about deleting it.
Both examples need 2 lines of code, which one is better to use?

**Comment by jasonrohrer** [comment]
The problem with the static version are twofold:

1.  You need to predict ahead of time what the max length can be, which requires you to think about each case, each time you do this, and NOT change the arguments to sprintf later without re-thinking about it.  The dynamic alloc version avoids asking you to think about how long it will be, and is therefore always bug-free (will never overflow, unless you run out of RAM).  I.e, give yourself one less thing to think about.

2.  If you have a long function, you will have a lot of these arrays allocated on the stack.  There is a danger of running out of stack space, depending on the limits of your OS.  I'm not sure how grave the danger is, but I don't want to think about it.

This also probably reduces overall memory usage, because you allocate and free as you go.


Of course, there is a trade-off here.  The downsides:

1.  You need to remember to free the memory manually.

2.  The performance is likely slightly worse (but memory alloc is probably NOT your bottleneck).  Maybe deep in an inner loop, I'd try to avoid it.

3.  Increased chance of heap fragmentation over time.  I've never encountered this problem in practice, though.
