### ISSUE TITLE
Building insulation not working all the time

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#327]
It worked with no issue in a building with stone walls, but ancient walls dont seem to work.

Havent tested other type of walls.

Also seems like like being at the edge of the building makes it not work sometimes too.

**Comment by AlecYawata** [comment]
Ancient stone wall is working good.
https://www.twitch.tv/videos/434311745

Dont forget program check only 13x13 area around you.
See screenshot.
![スクリーンショット 2019-06-04 21 05 48](https://user-images.githubusercontent.com/2708205/58877828-beaee100-870c-11e9-8844-663b341ab054.png)

**Comment by jasonrohrer** [comment]
I did fix it so that walls with signs insulate...  

I haven't been able to reproduce this with ancient stone walls.  Please let me know if you have more info about this.

I am thinking about how to detect bigger houses, but obviously, it involves sampling even more of the map, which consumes server resources.
