### ISSUE TITLE
--DUPLICATE-- Bug: moving bones causes names to randomly change 

### ISSUE THREAD

**Issue by rolandmartial** [jasonrohrer/OneLife#338]
**I originally opened the issue on Data7. Whoops. Original issue, to be closed along this one:
https://github.com/jasonrohrer/OneLifeData7/issues/332**

When bones get transported via basket, they sometimes change properties, and the age and name get changed to someone else's in the family line. Bug was unpatched as of Version 237.

With video proof, courtesy of Twisted.
https://youtu.be/K2bIVEhAN78?t=2434

40:34-40:37 The name is Boris Troll
41:31-42:00 Name becomes Epic Troll XVIII, and remains that way. Person who previously died is later confirmed to be Boris, and also the death date doesn't match - 244 years old.

This bug is possibly related to:
#288 
Bug section thread:
https://onehouronelife.com/forums/viewtopic.php?id=6838

**Comment by jasonrohrer** [comment]
Great twisted video there.

I noticed two things:

1.  He set the basket down before dumping it (using SWAP with the flint on the ground).  Not sure how this case is handled.

2.  The area he set the bones down in had a lot of bones nearby, meaning that maybe there was some other bone pile there long ago that had decayed away already (but the server still remembered it).

Hoping that someone can figure out the exact steps to reproduce this reliably.

It might in fact be case 2, which is harder to "force" when testing, because you need to wait for the grave to decay away (I can easily imagine that the server code doesn't handle this case correctly).

**Comment by rolandmartial** [comment]
> 1. He set the basket down before dumping it (using SWAP with the flint on the ground).  Not sure how this case is handled.
> 2. The area he set the bones down in had a lot of bones nearby, meaning that maybe there was some other bone pile there long ago that had decayed away already (but the server still remembered it).

I managed to replicate the bug today. It seems that it's linked to 2: the new bones take the properties of the old bones in the graveyard, which have now disappeared. I believe it has to be on the same exact tile where bones used to be. 

Testing hypothesis 1: swapping at random doesn't yield the same results. Even leaving the basket down with the bones in it and swapping with flint like Twisted did not result in name or age change.

I was sadly not recording the game at the time, but I'll try to get it recorded tomorrow.

**Comment by jasonrohrer** [comment]
No recording needed.  I'm pretty sure that's it.

The server is forgetting to reset that info when the grave decays to nothing.

**Comment by jasonrohrer** [comment]
Also, SWAPPING itself is needed, just in a spot where a grave used to be, right?

Like if you just dump them in that spot, I'm not able to reproduce, but if you swap with something in that spot, then the old name "follows" your basket forever, after you pick it back up.

That's what I've been able to reproduce.  The SWAP action is the one that isn't handled correctly.
