### ISSUE TITLE
Inefficient Pathing

### ISSUE THREAD

**Issue by trevorhackman** [jasonrohrer/OneLife#347]
For example, when at a distance, if you click on a berry bush the character moves all the way onto the same cell of the bush then picks a berry. You can interact one tile away. No need to move all the way onto the same cell.

**Comment by jasonrohrer** [comment]
Yes, it does this for eating locations only, because it makes it much faster and more efficient to munch multiple berries if you're standing on the same tile.

For picking up an item, it walks to the nearest tile (most efficient).  But the berry bush is a special case, because you often want to eat more than one.  The bush-self-bush-self mousing is much quicker when you're standing on the bush.
