### ISSUE TITLE
held baby uses /die and his cloths disapear. 

### ISSUE THREAD

**Issue by miskas9** [jasonrohrer/OneLife#366]
I first came across this bug yesterday and it happened twice.  I play from 2018 but I wasn't playing much.

**Comment by miskas9** [comment]
asked more daily players about this, it is a known and common bug

**Comment by jasonrohrer** [comment]
I think this may have been fixed.

I just tested it, and the clothes end up correctly spread on the ground.  Note that if the ground is cluttered, the clothes may end up quite far away.  If the ground is cluttered enough, so that the server can't find a place to spread them, it eventually gives up and the clothes vanish.  But this is a very rare situation.  It looks as far as 10 tiles away from where the mother is standing before giving up.  So in some situations, the clothes may end up off the edge of the screen somewhere.
