### ISSUE TITLE
Several graves of the same person

### ISSUE THREAD

**Issue by DarkDrak0** [jasonrohrer/OneLife#370]
This bug normally happens when trasporting baskets of bones in a cart. Lets say you pick up the bones of: Eve One, Eve Two, Eve Three, Eve Four, put them in a cart, transport them out of town and put them down. The result may become: Eve One, Eve One, Eve One, Eve One.

I suspect this is due to trying to swap between baskets of bones in a cart, which are considered the same item, thus other baskets of bones get the same name of one of the baskets.

**Comment by jasonrohrer** [comment]
Yeah, I don't think tracking works at all if you put them in a cart.  I'll take a look.

Probably, what will need to happen is that these will have to become unknown graves.

**Comment by jasonrohrer** [comment]
Actually, fixed it so that bone baskets aren't containable instead.

There are two ways that this could be fixed:

1.  Bones put in a cart have their identity forgotten, and become unknown bones (thematically okay, because the bones get mixed up in the cart, but probably will be an unpleasant surprise for many players, when their mother's grave is forgotten after passing through a cart).

2.  Bones can't be put in a cart.  Grave identities are NEVER forgotten, but the cool "bone collector" cart (a nice visual, etc.) can't happen.  I'm worried enough about the upleasant surprise in (1) to prefer this version.

The reason this can't be fixed for real is that grave movement is attached to the player moving the grave, and thus isn't tracked through containers.  A player has one grave "in the air" at a time.  Once they put that grave into a cart and pick up another, they have more than one "in the air."  Fixing the underlying implementation would involve a non-trivial amount of work.
