### ISSUE TITLE
no mouth animation when talking and other face movement

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#395]
https://www.youtube.com/watch?v=mT4JktcVQuE&t=6s

In the trailer the mouth moves when talking and also the eyes have movement to them and dont stay static.

It always felt weird even borderline creepy to play with people that have no facial movement like their face is freezed or something.

**Comment by jasonrohrer** [comment]
Welll... eyes moving is tougher.  I think I drew the JASON eyes specially to have him look where he was walking.  To do this for all the characters and ages is possible, but a lot of work.  And many of the eyes won't look right "flipped", so new eyes would need to be drawn.  The animation engine supports this... but the content part is hard.

Talking mouths is totally possible.  However, it's a little weird for it to be silent, and also not hooked to what they are actually saying (the length of it, etc.)

There could be constant mush-mouth cartoon sounds while talking, like murder mouth, but friendlier.  Or like the adults in Peanuts cartoons (wha wha wha whaaaa wha).

It might make sense to have an "open mouth" shout type emote that happens when you talk, along with a cartoony "HEY!" type sound.  Like Navi in Zelda when she starts talking to you.

**Comment by Dodg-e** [comment]
If you put the "HEY!" sound from Navi i'm deleting the game and asking for a refund haha

Mush-mouth sounds good as long as it's not too obnoxious.

If it's possible the mush mouth animation and sound length could depend on the number of charachter

Moving eyes would be nice, but yeah probably harder to make it right, probably would look really weird if it followed the mouse cursor.

Maybe if it followed the cursor but with some sort of delay or slowed movement so the eyes dont move rapidly in every direction it could look good, as long as the movement doesn't go to extremes.

**Comment by jasonrohrer** [comment]
This would be very hard to get right, and not be annoying.  I'm going to table this for now.
