### ISSUE TITLE
Incompatible with macOS Catalina (10.15)

### ISSUE THREAD

**Issue by connorhsm** [jasonrohrer/OneLife#423]
The latest version of macOS prevents me from opening the OneLife application. I was given a clear warning this would occur before I began installing the update.

See Apples page on their transition to 64-bit. https://support.apple.com/en-au/HT208436

I am still able to open the client application by Awbz.

**Comment by jasonrohrer** [comment]
I knew this day would come....  ugg.

I don't have a 64-bit mac.

**Comment by connorhsm** [comment]
I've left Awbz a message on Discord asking if they can comment here.

Otherwise, I'm fairly certain they cross compile. To quote Awbz:

> If it helps any, this is what I use on my Ubuntu VM to make Mac builds, this lets me make binaries for Linux/Windows/Mac all with 1 script from the 1 Linux VM: https://github.com/tpoechtrager/osxcross

Would this be a possibility for OHOL?

**Comment by Awbz** [comment]
I'm a little late to the party on this one, but I've been asked a number of times to comment here about my macOS builds.  I've been told that my modified client is currently the only way that Mac users, Catalina or otherwise, are still able to play OHOL since you've officially dropped support for macOS.

My OHOL development environment is a 64-bit Xubuntu 16.04 VM (on a Win10 host) that I've setup to do cross-compiling to Windows/macOS using mingw-w64 and the [osxcross](https://github.com/tpoechtrager/osxcross) toolchain mentioned previously with the MacOSX 10.10 SDK.  The "trickiest" part is getting the SDK, which is outlined in the [PACKAGING THE SDK](https://github.com/tpoechtrager/osxcross#packaging-the-sdk) section of the osxcross repo.  As I haven't owned a physical Mac since the early 90's, I used a VM with Yosemite (10.10.5) to package my SDK and test the client.  I'd be happy to share my packaged SDK with you if you're at all interested and find this portion of the process too tedious.

- Once the SDK is procured, I cloned the osxcross repo to */usr/osxcross* and copied the SDK into the */usr/osxcross/tarballs/* directory.  Any necessary dependencies for building can be acquired using the */usr/osxcross/tools/get_dependencies.sh* script, if needed.
- Then I build the toolchain with the *build.sh* script located in the root of the repository.
- After the build is completed, I simply copy your (non-empty) macOS *SDL.framework* folder into the */usr/osxcross/target/SDK/MacOSX10.10.sdk/System/Library/Frameworks/* directory.
- Finally, I added the */usr/osxcross/target/bin* directory to the PATH variable and things are all set!

Next, I [created a new Makefile](https://github.com/Awbz/minorGems/blob/master/game/platforms/SDL/Makefile.MacOSXCross) for macOS cross-compiling and use *o64-clang++* for the build with the following PLATFORM_LINK_FLAGS:

`-framework OpenGL -framework SDL -framework Cocoa ../../minorGems/game/platforms/SDL/mac/SDLMain.m -rpath @executable_path/../Frameworks ${CUSTOM_MACOSX_LINK_FLAGS}
`

If it helps at all, I've attached a small shell script that I use to bootstrap vagrant boxes to get them from a fresh install to being ready for cross-compilation for OHOL.  While I understand this solution might not be "perfect" or the "correct" way to do things in the new Mac world...it works without any changes needed to your code or unnecessarily buying new hardware.  Just my 2¢, do with it as you will, sir!

[bootstrap.txt](https://github.com/jasonrohrer/OneLife/files/3934987/bootstrap.txt)

**Comment by jasonrohrer** [comment]
I really appreciate this...

But I'm also having trouble with how complicated this all is, and the feeling that it's not very future-proof.

It's hard to justify all these acrobatics for 5% of the player base.

It also burns my biscuits to do any acrobatics, because Apple has ignored backwards compatibility again, for like the 10th time in my life.  And they wonder (or maybe they don't) why most software isn't available on Mac?

At age 42, I feel like life has gotten too short to waste any more time chasing after the latest incompatible Apple change.

So, sadly, OHOL will be added to the very long list of "software that dosesn't work on Mac."

**Comment by connorhsm** [comment]
Thank you for responding to this, I understand and appreciate your reasoning.
