### ISSUE TITLE
Building useless if a door open

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#436]
If i remember correctly even one door open in a full house with floors etc makes the whole building lose all it's insulating value right?

So a complete structure becomes useless just because a single door is open, this makes building a very bad strategy and annoying to deal with, you need to get in and out a structure but then constantly have to deal with open doors (yes there is the spring but it's a later tech)

Open doors could have a 10-20% insulation to avoid buildings behing completely useless when a door is open and annoying to deal with.

Or maybe a negative insulating value, this way it would lower the total insulating value of a structure but not delete completely insulation, being in a house with an open door is still warmer than being outside with no walls around at all.

**Comment by jasonrohrer** [comment]
At this point, it's not about the insulation value, but the fact that "indoors" vs "outdoors" is a binary property, depending on whether there's a path to outdoor air or not.

When the door is open, there's a path out, so it becomes an outdoor space.

I could add R-value to open doors, and then it would make it an indoor space even when the door is open.  But then people would just leave the doors open all the time, right?

I suppose there could be some half-way state, called "drafty" that happens when the door is open.  Maybe as long as there is only one wall hole, your space is drafty, and you only get half the indoor bonus or something...

**Comment by AlecYawata** [comment]
Indoor bonus was changed, so now is time to add R value (like 0.1) to opened door?

**Comment by jasonrohrer** [comment]
The new auto-closing spring doors (and snow doorways) solve this problem pretty well.
