### ISSUE TITLE
Animals Stop Moving Randomly

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#474]
I've noticed this most with dangerous animals.  I think I've only observed it with a mod with a zoom feature, in case that's related somehow.  Basically, the animal will stop moving around at some time.  I observed it most recently with a wolf when out building a road in a badlands.  The animal can usually, if not always, get forced to move again by attempting to move to the same tile that it occupies.  Unfortunately, it doesn't seem to happen with any sort of regularity, so there's no predicting how long one would need to stand in close proximity with dangerous animals for this to happen.

**Comment by jasonrohrer** [comment]
How far away are they from you when you do this?

They do go to sleep after not being "seen" for long enough by a person (so as not to consume server resources forever when no one is looking at them).

How "seen" is defined is based on the non-zoom screen.  X +/-8, and Y +/- 7 around your current location.

You might be able to experiment with this yourself and confirm that it is only "out of window" animals that stop moving.  However, if you walk so that they are in-window, they should wake up and start moving again.

You will also notice other transitions stopping outside of the window, like milkweed will stop cycling, and fires will burn forever, etc.

**Comment by DougLefelhocz** [comment]
After they've stopped moving, I've gotten as close as one or two tiles away from the animals and they don't seem to move.  I see them literally stop moving within the default view radius, and also don't seem to start if I get close to them.

**Comment by jasonrohrer** [comment]
Is this easy to reproduce?

Can you try to reproduce it with the official client?

**Comment by DougLefelhocz** [comment]
I'll give it a go, I suppose, seeing if I can get it to happen again with the official client.  I first remember seeing it with mosquitoes back before the temperature overhaul when trying to trap them in a jungle. They would mysteriously stop moving behind trees.  Not sure if there's usually an object below the animal when it happens... lately I've seen it with wolves out in the badlands, and I'm usually on a horseacart and thus can get easily get close without getting bite.

**Comment by DougLefelhocz** [comment]
I went into a jungle on server9 (using the default client) and tried to mostly watch mosquitoes and throw some items on the ground.  I died to a wolf bite at 37, so I probably spent like 15 minutes or so watching the mosquitoes.  They all seemed to move fine.  The issue might be have been related to the same thing that caused geese to not move off of stumps when headless and an object below them.  Will try to see if I observe it sometime in the future though.

**Comment by DougLefelhocz** [comment]
I haven't seen this happening again, after I've tried to move closer to wild animals without touching them.  I believe this is likely fixed if it was an issue for people playing the default client, so I'm closing this.
