### ISSUE TITLE
Carts get lost forever if you hit the wrong biome

### ISSUE THREAD

**Issue by sigmen4020** [jasonrohrer/OneLife#479]
If you accidentally or purposely enter the wrong biome while holding a tire cart, the tire cart will land on the tile in the wrong biome. 

Example:

![](https://media.discordapp.net/attachments/419395479420534785/661561013979578369/unknown.png)

**Comment by jasonrohrer** [comment]
I'm having trouble reproducing this.  Where exactly are you stepping to make this happen?  For me, the cart is always left OUTSIDE the bad biome when I step in.

**Comment by sigmen4020** [comment]
Pretty sure I just stepped on the tile with the cart in the image. It happened twice for me in that life. Maybe the problem happens when you enter tile from the NE, NW, SE or SW as opposed to entering the tile from the N, W, E or S? Because I could’ve have certainly done that judging by the image. My memory of it is a bit hazy though, since it happened a couple of days ago, plus I’m not honestly sure how I did it since it just ended there by complete accident.

**Comment by jasonrohrer** [comment]
Well, if the cart dropped like that, ANY held object should drop in the same way.

So testing it shouldn't be that risky.

I made a test map with exactly that layout, and I tried entering the bad biome from all sorts of angles, and I just couldn't get anything to drop into the bad biome.  It always dropped outside.


Grab some pine needles and look for a bad biome.  Can you get them to drop inside the bad biome?  If so, please note the steps needed to reproduce.

**Comment by sigmen4020** [comment]
Okay, I've managed to reproduce it. It seems to occur in rare scenarios where you get the wrong biome debuff without actually entering the tile. Like you are skimming past the tile and the game sees it as you entering the tile and then applies the debuff. And in these scenarios it's possible for the cart to enter the wrong biome. Long story short, for this to happen you don't actually touch the tile in the wrong biome, but the game thinks you do. Hopefully that's understandable enough.

**Comment by jasonrohrer** [comment]
And this is happening with the official client?

Can you shoot a video of it happening?

**Comment by sigmen4020** [comment]
I've been having issues getting video recording software to work on my laptop, so I'm probably not gonna be able to get a video of it.

It's happening with hetuw using regular mouse controls (so no WASD). Haven't tested it with the official client.

Also I've only been able to reproduce the bug using carts. When I've tried with other stuff I haven't been able to reproduce it.

**Comment by jasonrohrer** [comment]
Can you try it with official client?

HETUW has some different movement code in there...

**Comment by sigmen4020** [comment]
Took some time to complete, but here it is.

Made this video that showcases the bug using vanilla client. The bug happens at about 2:38.

https://www.youtube.com/watch?v=ZN6kLVLoy18

Here's a reference link to the family tree, just so you know when this was recorded:

http://lineage.onehouronelife.com/server.php?action=character_page&id=5772536

**Comment by jasonrohrer** [comment]
Wow, nice work!

So it looks like you were clicking back and forth like crazy as you rounded that corner again and again?  I'll see if I can reproduce it on my end.

**Comment by jasonrohrer** [comment]
Still finding it impossible to reproduce on my end.  Some specific series of mouse clicks, I'm guessing.

The weird things about this, looking at the server code:

1.  Whenever you start a move that eventually crosses into a bad biome, the server force-drops what you're holding WHERE YOU'RE CURRENTLY STANDING (which, from previous moves, isn't in a bad biome, or else you wouldn't be holding something).

2.  That force-drop always respects biome boundaries.  It looks for an empty tile, but only in the biome where you're currently standing, before the bad-crossing move happened.


So, somehow, a move is starting already in a bad biome, while holding something, and I can't figure out how.

**Comment by tatianaanthony** [comment]
I didn't find this issue before I made issue 606 (I think in the wrong github?  The OneLifeData7 repo (https://github.com/jasonrohrer/OneLifeData7/issues/606) (sorry, I didn't know there were multiple repos.

Here's a copy paste of mine.

> I found a situation in which entering an uninhabitable zone with a cart leaves the cart irretrievable.  See image.
![IMG_2085](https://user-images.githubusercontent.com/9399133/72849104-04a4bf00-3c74-11ea-9cd3-88eeb320b3a3.JPG)

> Expected behavior:  Entering an uninhabitable biome drops anything you're holding.  Those objects appear on the ground in the last cell that you occupied in an inhabitable biome before entering the uninhabitable biome.  It is possible to retrieve your item.
> 
> Actual behavior:  Entering the jungle biome with a cart (when the area entered was mostly surrounded by other items) results in the cart remaining in the jungle biome, in a spot that is unreachable.  
> 
> Version:  The Baby Placement Update, on Windows 10.  Playing through Steam.
> 
> Other notes: 
> 
> I started between the two tables to the north, and did a click-hold on the bottom edge of the screen to route me south.  It took me through the jungle peninsula there.  You may notice items to the south, southwest, and west of the jungle peninsula.
> 
> I believe this is a bug with how the location of an object dropped by biome sickness is chosen (though I don't know enough about the code to find that and confirm whether I'm right). 
> 
> 

One fix could theoretically be keeping track of the most recent good-biome location a person is standing in, but I expect that keeping and updating that value for every player at all times could be a lot of processing.

**Comment by jasonrohrer** [comment]
Oh, I see.... hmmm.  That's a good clue!

Seems like, when walking between those tables, your character had no choice but to route through the bad biome... still, you should stop at the edge before stepping in.  I'll see if I can reproduce it.

**Comment by jasonrohrer** [comment]
Man, I still can't reproduce this.  I set up an identical scene to what you've go there, and no matter where I click or hold she always routes around, unless I click into the bad area directly, and then she drops it outside before stepping in.

![screen00504](https://user-images.githubusercontent.com/12563681/73091945-6772a200-3e90-11ea-8389-8840dacf09fd.png)

Are you using the official client, by the way?  You said you were on Steam, but you haven't installed a mod there, right?

**Comment by tatianaanthony** [comment]
I'm using the official client, the only mod I use is the nudity mod.  I wish I'd gotten a better picture, but I wasn't thinking about getting the entire screen at the time, and I was using my phone to capture it.  If it happens again, I'll get more of the surrounding area.  

I do remember that there were more items to the north - I think there were several more tables.

If it helps, it was my life as Fanny Connell, but I've played a few lives since then and didn't know how to extract logs that could be helpful.

I'm trying to think of what else could be useful. I don't remember exactly what I was doing, though.  I think I have a bad habit of shift-click-holding (instead of regular-click-holding) on the edge of the screen and just never unclicking to get my character to move.  It's also possible that I was right clicking in a couple different spots near the bottom to place my cart somewhere reasonable.  Maybe right-clicking on an item while you're holding a cart somehow affects the routing or something else related to this?

I remember being surprised that I got the biome sickness sound.  I think I may have been expecting it to either route me directly diagonal and not through the jungle biome, or up and around.  Are diagonal paths even possible without routing through one of the orthogonal tiles?  I'd expect they are based on how sheep pens often work.

------------------------------------------

Here's where my brain is going, so feel free to disregard.  What happens in the code when:
1. Your character is moving diagonally directly between two tiles that are attached at the corner, but not orthogonally attached
2. Your character is on or near the boundary between the tiles
3. On the frame where the character's position updates, the requested goal changes

Is there any possible way that the character's position is erroneously recorded as being in the orthogonal tile?  Is there anywhere in the code that the character position is determined by the sprite position during movement?  

I know that when you're running with the edge-click-and-hold and your character has to reroute around stuff (the black dotted line shows up to show where you're going), the character will entirely finish that path before continuing on a straight line towards your cursor.  On the other hand, if you click while the character is in the process of following the dashed line, it will cancel that route, and follow your cursor immediately.  Could the determination of the start position of the new route be erroneously putting the player in the bad biome?

---------------------------------

Anyway, I'll let you know if I see this again.  I'll make sure to document what I was doing and the surrounding areas more thoroughly.

**Comment by jasonrohrer** [comment]
Well, if you get a chance, hold some pine needles or something else of little value and then find a corner of a bad biome.  Try it over and over and see if you can find the trick that will cause the pine needles to drop in the bad biome.

**Comment by DarkDrak0** [comment]
I tried to reproduce it. I think it's linked to how the pattern to your destination changes when you change destination fast while still in the middle of movement. Several times i just walked through a bad biome tile, but didn't drop anything. Similiar thing happens when one circles around a well or a tree, for example: there can be a point when you attempt to pass through it and you are just bounced back.
Then if you click fast on a bad biome while passing through a bad biome tile, you character drops the held item on the bad biome tile. Here are two videos me getting the bug. Only last 10 seconds of each have the bug happening, but im too lazy to get a video editor.
https://youtu.be/q8zcVOZHULw
https://youtu.be/bB0KDLYeciQ
It's hard to reproduce since you need, not only to spamm click around the bad biome, to get the movement pattern to make you pass through it, but also to click on a bad biome tile in that split second when you're passing through a bad biome.

**Comment by jasonrohrer** [comment]
Wow!

Thank you, Drake.  This video helped me reproduce the issue on my end and figure out what's causing the problem.

There is a brief moment when walking diagonally between two cells where you're closest rounded position is actually neither the start nor the destination, but one of the "catercorner" cells.  In this case, the bad biome.

If you happen to click again while in this intermediary position client-side, the client finds a path starting at the bad biome cell (which is the closest cell to you in this moment).
