### ISSUE TITLE
Steam ID XXXXXXXX runs into GENETIC FITNESS display on login screen

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#491]
Fix:  shorten the XXX string after replacing the steam ID numbers with X's

**Comment by TwistedHBG** [comment]
This is also true for emails.

![image](https://user-images.githubusercontent.com/43919541/72219537-6e6feb00-3547-11ea-940d-c7ed58126047.png)

**Comment by Dodg-e** [comment]
Since email and key is very rarely changed after it has been entered once and since genetic score is a central part of the game.

Wouldn't it make more sense if the email and key would be in the settings after it has been entered the first time and the genetic score would be in the center of the screen

**Comment by jasonrohrer** [comment]
Yeah, maybe an overhaul of this screen would make some sense....

But that's beyond the scope of this bug report!  :-)
