### ISSUE TITLE
Lineages die during updates

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#492]
Proposed solution:

https://onehouronelife.com/forums/viewtopic.php?pid=86123#p86123
https://onehouronelife.com/forums/viewtopic.php?pid=86148#p86148
https://onehouronelife.com/forums/viewtopic.php?pid=86162#p86162

**Comment by DougLefelhocz** [comment]
Alternative solutions have gotten proposed on the forums.

Also, see here: https://github.com/jasonrohrer/OneLifeData7/issues/562 and here: https://github.com/jasonrohrer/OneLifeData7/issues/565

**Comment by Dodg-e** [comment]
"There could be a way to "freeze" living people, but no good way to have the same players resume those lives after the update."

Since updates are an exceptionnal case and having continuity of lineages is kinda one of the main points of the game is it that much of an issue if it's not the same players that continue the life of a character started by another player before the update?

My bet is the unsatisfying part was that players would be sudenly cut off from the current life they are living but it's possible to let them finish their lives while at the same time creating a save point for the in game characters, about 30 minutes before the update, so other players that join after the update can keep the lineages going.

**Comment by jasonrohrer** [comment]
I appreciate the tenacity here, but I don't think this is a problem worth solving.

Any solution would be terribly complicated and bug prone, not to mention having weird side-effects and edge cases.

Again, a lineage surviving continuously is only meaningful because there was a continuous chain of people who all knew each other.  Nothing is gained by faking it.

**Comment by DougLefelhocz** [comment]
"Again, a lineage surviving continuously is only meaningful because there was a continuous chain of people who all knew each other."

Knowledge is not something that exists inside of in-game characters, since they can get run by bots (and I've heard that some bots do play).  Knowledge only exists in the human beings behind the characters.  Chains of people are discrete by their very nature also.

If Eves could have ancestors, there could still exist a connected chain of people who had experience with each other.
