### ISSUE TITLE
Server1 Lineages Die Out Due to Forces Beyond Their Control

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#501]
After players not checking a custom server get directed in whole or in part to server1, after a while, incoming players get thrown back to bigserver2.  There exist no children for server1 lineages after a while and no present way for those lineages to come back to life later also.  There are no bots, or not enough, for those lineages to survive also.

There were about 13 lineages that got affected by this weekend, and have been many more since splitting incoming players got reintroduced.

**Comment by Tarr-OHOL** [comment]
Make sure to click custom server.
?????
Profit.

**Comment by DougLefelhocz** [comment]
All servers have an upper limit on the number of players that they can have.  Also, most players would have to know about how the custom server system works, and I doubt that they do.

**Comment by jasonrohrer** [comment]
Yeah, custom server setting is not the answer here...

Did this happen over the weekend when it got really crowded?

We want everyone on the same server whenever that is possible.  However, we do need to split players up when that's NOT possible.

The current algorithm does a good job here, splitting players up once the threshold is passed, and then keeping them split for a long time.  Only when the overall population drops quite a bit is the split undone.

So it doesn't ping-pong between split and not split.  It kinda "makes up its mind" and sticks to its guns.

**Comment by jasonrohrer** [comment]
Current settings:

Start splitting population to two servers if the total ever goes over 130.

Stop splitting population if the total ever drops below 52.

In the rare case where it goes above 130, it will be held split for most of the day, until late at night when it drops below 52.

**Comment by DougLefelhocz** [comment]
> Did this happen over the weekend when it got really crowded?

Yes.  There were two re-directions of incoming players on Saturday, and one on Sunday.  I counted 13 lineages which died out during that time, with at least 12 dying after re-direction.

Also though, there existed one time where it got spotted where a large number of players were on server1 around 6:00 A. M. EST a few weeks back.  There's a post by Spoonwood on the forums where player count on bs2 and s1 got documented during some instants of that time period a few weeks back.  There's no information about what the player population was like before the first report, but the date when that happened is there.

**Comment by DougLefelhocz** [comment]
Bigserver2 has 62 people on it, and server1 has 38 people on it right now at 5:15 P. M. EST.  I don't know if the player count reached 130 earlier today or not though.

**Comment by DougLefelhocz** [comment]
Also, from what I've seen by checking the reflector, I think that the server population has stopped splitting without the total dropping below 52.

**Comment by jasonrohrer** [comment]
I made some scripts to show server populations over time, and you're right:

![Screenshot - 01242020 - 12:32:17 PM](https://user-images.githubusercontent.com/12563681/73101975-b8d95c00-3ea5-11ea-8c40-7619dbe46b8c.png)

There are several things here that aren't clear to me.

First of all, the first peak does go over 130 (50% of 260, the bs2 max), so it makes sense that it starts splitting.

But the next two days, the splitting is happening well under 130.  It's still close, though, and I think this might have to do with the server reporting this back to the reflector:

`int currentPlayers = players.size() + newConnections.size();`

I could imagine something like 15 newConnections in the mix, so I think that's okay.

Looking at the code, I see that it starts splitting at 50% of the total capacity of the "active" servers.  When only bs2 is active, that should be at around 130.  So it spins up server1 at that point.

After that, it stops splitting when the population of the active servers (now bs2 and server1) drops below 20% of total capacity.

And this is where the problem lies.  Server1, for some reason, has a total capacity of 400 (probably left over from stress-testing in the distant past).  260 + 400 = 660, and 20% of that is... yep, 132!

So the "stop splitting" point is ABOVE the start splitting point.


Even if they both had the same capacity of 260, when one of them hits 50%, splitting to two servers would bring the fraction of max instantly down to 25%.  Thus, 20% to stop splitting is dangerously close, and will likely cause ping-ponging.

First, I'm going to restore server1 to a sane pop cap of 160.

Second, I'm going to change the stop-spreading fraction to 15%, which is 63 total players spread on server1 and bs2.  That means roughly 31 players on each, which is getting pretty low.

So it will start splitting at 130, and stop splitting at 63.

**Comment by jasonrohrer** [comment]
Actually, the stop-spreading fraction on the live reflector is already 10%.... so I return to being stumped.

**Comment by jasonrohrer** [comment]
I'm going to add some logging when it splits and stops splitting, and see if I can get some more data here.

**Comment by jasonrohrer** [comment]
Also note that for now, I've put server1 back up to 400 max, so that I can check the logs to see why it's ping-ponging.

**Comment by jasonrohrer** [comment]
Making some progress here.

The logging shows the following:

```
Jan 25, 2020 12:03:49 AM 0 * 0.5 <= 92, 1 servers is not enough, adding another 
Jan 25, 2020 12:12:24 AM 660 * 0.1 >= 14, 2 servers is too many, removing one 
Jan 25, 2020 10:29:38 AM 0 * 0.5 <= 0, 1 servers is not enough, adding another 
Jan 25, 2020 10:32:30 AM 660 * 0.1 >= 66, 2 servers is too many, removing one 
Jan 25, 2020 03:21:53 PM 0 * 0.5 <= 0, 1 servers is not enough, adding another 
Jan 25, 2020 06:30:25 PM 660 * 0.1 >= 54, 2 servers is too many, removing one 
Jan 25, 2020 11:39:09 PM 0 * 0.5 <= 0, 1 servers is not enough, adding another 
Jan 26, 2020 12:30:28 AM 660 * 0.1 >= 48, 2 servers is too many, removing one 
Jan 26, 2020 07:35:31 PM 260 * 0.5 <= 130, 1 servers is not enough, adding another 
Jan 26, 2020 07:39:42 PM 560 * 0.1 >= 3, 2 servers is too many, removing one 
```

What's happening here is that there are times when no servers are reachable, for a moment due to routing or server load or something.  That causes some spurious cases where it starts spreading, and then stops shortly afterward.

There's one case where the pop got up to 130 for legitimate spreading.  But then it stopped shortly after, again due to a temporarily-unreachable issue.  Hey, the only reachable server says it has 3 people on it, better stop spreading!

I've changed it to NEVER start spreading when when see 0 servers online, and never stop spreading if some of our servers are offline.  We should wait until they're all reachable again before deciding to stop spreading.

I'll let it run with these changes and see what the logging shows.

**Comment by jasonrohrer** [comment]
Checking the logs, it has been 10 days since there were any spurious splits.  I'm going to count this as fixed for now.
