### ISSUE TITLE
More Floors, More Players, More Objects in One Spot Leads to Lag

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#503]
Using [random.org](https://www.random.org/) I ended up rolling 0.  0 gets used for bs2, while 1-15 gets used for s1-s15 respectively.  I got named [Juliaann Underberg](http://lineage.onehouronelife.com/server.php?action=character_page&id=5819831)

Early in my life I notice it seems quite laggy by the fire, in the clothing room, in the kitchen, and even in some places by the farm.  So, I decide to mostly get resources out of town and bring them back to town.  Later in my life I decided to even zoom in all the way, to see if I still had lag as zooming in all the way has tended to reduce the effect of lag in the past.  I walk around in the kitchen when I'm older than 40 to see if I still have lag if zoomed in all the way and ... 

I still had lag!

I'd imagine that lag is very frustrating for new players.

**Comment by jasonrohrer** [comment]
This depends mostly on the pixel fill capabilities of your graphics card, I think.  In very busy areas, some GPUs cannot keep up.

If you're using a mod, who know's what's going on?  Maybe the mod isn't correctly culling off-screen objects before drawing them (the GPU will cull pixels, but there is still some cost to drawing off-screen objects).


It's been a while since I examined this issue, but back when I last did, I bolstered the in-game /FPS command.  There is now a lot of info and graphs when you type /FPS in chat.

So, if you can try the official client, and get yourself into a laggy spot in the game, and then try to see where the cost is coming from with /FPS.

**Comment by jasonrohrer** [comment]
Please re-open if you have more info.
