### ISSUE TITLE
Womb Cooldown?  Twins Don't Seem Right.

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#505]
A few weeks ago I had someone suicide on me a bunch of times on server12 as Eve Spoon.  That person tried to get to his/her Eve spawn, but couldn't, and apparently only got born to me.  Someone in the discord told me that suiciding to get to one's Eve spawn was no longer working.  Yesterday, I got [born](http://lineage.onehouronelife.com/server.php?action=character_page&id=5829826&rel_id=5829826) a few times to someone on a road and kept dying.  I decided to suicide a few more times and see if I could get to my Eve spawn and could not.  Thus, it looks like players will get forced to get born to a mom even after suiciding which suggests that womb cooldown isn't working correctly.  The family trees of Eve Cool, Eve Underberg, Eve Sauler, and Eve Connell _might_ also suggest womb cooldown as not working correctly.

I did eventually decided to stay for a bit yesterday after I couldn't suicide to my Eve spawn and the person had reached their destination point, but checking my family tree from yesterday I had an identical twin sister even though I didn't use the twins option.

**Comment by jasonrohrer** [comment]
Womb cooldown is respected ONLY if there are other mothers available for you.

Eves are now only spawned if they are actually needed due to mother overload or family deficit issues.

Spawning Eves for other reasons was creating too many families.

Also, suicide has ALWAYS cleared up a mother's womb cool-down right away.  Otherwise, a mother who actually wanted a baby would get stuck waiting after every suicide.
