### ISSUE TITLE
Issue with the new baby placement mechanics

### ISSUE THREAD

**Issue by AcorpBG** [jasonrohrer/OneLife#510]
Since the new baby placement update that was introduced with commit [dabead1a816f599d524a0f7de8f8debefb9869ec](https://github.com/jasonrohrer/OneLife/commit/dabead1a816f599d524a0f7de8f8debefb9869ec)
The old deprecated bad mother mechanic was removed because of cooldown.
This is resulting in getting spawned to the same bad mother especially on server restart.
Example: Eve Volek(http://lineage.onehouronelife.com/server.php?action=character_page&id=5840080)

The effects of this issue is that the weakest family/race get priority and since all babies are dead the family remain the weakest and all new babies are spawned to this same badmother while other families with good Eve mothers get no new babies, you are locked to the same bad mother.

I think in this case it is better to spawn new Eve from the same race than forcing people few games in a row to the same bad mother.

Here is the exact code that was removed and made deprecated because of the CDs which are ignored in the new algo. 
```
// lower the bad mother limit in low-population situations	    SimpleVector<LiveObject*>parentChoices;
    // so that babies aren't stuck with the same low-skill mother over and	
    // over	
    int badMotherLimit = 2 + numPlayers / 3;	

    if( badMotherLimit > 10 ) {	
        badMotherLimit = 10;	
        }	

    // with new birth cooldowns, we don't need bad mother limit anymore	
    // try making it a non-factor	
    badMotherLimit = 9999999;
                if( numDead >= badMotherLimit ) {	              
                    // this is a bad mother who lets all babies die	
                    // don't give them more babies	
                    continue;	                   
                    }
```

**Comment by DougLefelhocz** [comment]
I find it a bit bizarre to call Eve Volek a bad mother.  There exist a few guides on Eveing on the forums, I think also on YouTube, and also on the [Wiki ](https://onehouronelife.gamepedia.com/Eve)that caution against taking on children early/too many children early.  There's no way to carry a basket with the primary tools and children early on (there is no cheap baby sling available for an Eve to make quickly at present, if such will come someday).  Also, do you know how many children Eve Volek fed?  Because it might be double digits.  Furthermore, you might want to note that [Eve Happy](http://lineage.onehouronelife.com/server.php?action=character_page&id=5839915) had a lineage during the same update period as Eve Volek.  The children of Eve Happy didn't have any grandchildren.  There was at least one grandchild from the children of Eve Volek.

**Comment by AcorpBG** [comment]
The statement that Eve Volek is bad mother comes from the code and the removed feature. 
The Issue is you get spawned to the same mother that is not feeding you. 
In such corner cases as server restart there should be something to prevent this from happening.
I can tell show you example where Eve Boots cared for her children and her children cared for the unnamed black Eve's children. 
I have no problem with the caution for eve to not pick more children early on. 
Again the issue is when you are in the loophole to get spawned to one particular Eve that is not picking children, 120 kids when the whole player count at that specific time was 60 players speak for itself. 
Lets end the discussion of weather Eve Volek is bad mother or not and leave to Jason to decide if this is birth mechanic issue or intended.

**Comment by AcorpBG** [comment]
Here is some more info from the publicdata
```
cat 2020_01January_23_Thursday.txt|grep 2612984|grep -v 9a0589cb673446fd534812d43cde1913f30b256a|awk {'print $4'}|sort|uniq -c|sort -bnr
     18 edc0f44ef3f2f9c1eb9f02f28b170d585df7b328
      8 b62a5b8c5cb7277fd8f4905c35d9b81f21f41820
      7 1e55b580f9975391566ac2d5b783f24bf981f26c
      6 f7fa54b16453b303ae9c34dbf9d93050f5220fe8
      6 b714615e7b5b4582a5ae2019d611439bc4f1cd61
      6 8e3cacd7a55a3f5e8c4e66cff6c826222f0332f6
      6 72535c705c09f5f454c2204c456fbc7a61d86586
      6 16de33d89e8a16656e1404a4d56b4b0a579e1583
      5 ebd7fe6217f9d4765528ac7c10aef1091c31384d
      5 b2ab71671e77ccd8f5800d8bf6f440e633fb66e0
      5 6147bd739b8d9d1e0236e18d57641918bfdca593
      4 3ce403481bf68baf1b158a2bf7f12ed93c0a47fe
      4 2f5167fced4f329e1ed8219139f3f2e2b899850e
      4 265223909fa4f36f07a340f020cafdb74d91615e
      3 f534a523f1164d4c9dc448e0b88b214f8b0073b0
      3 c7c9fddf7c53d81186fdec2c3e5e3bde1ec64283
      3 859dc7fd548d354d6c1125bdea918dc1786ab92d
      3 72b6e50d742dd787b4a4c5bc7edd8f2e00de93fa
      3 6f9b38e9749915c384abbe11463ddcd0f3dc12dc
      3 655f5758dd4270ad4745fe06971cf79b7e5ef704
      2 dd913a8f41e8841e570c9503f268990c421664d3
      2 d9f2cfef2c2ecdeb015e93556522c804e6c1e79b
      2 546b7abb499b0b586013521a09e675a5b33256dc
      2 358aa827e7fa2927ec3455d6cc5c44ea7603b519
      1 d30ac36b762b46429a6d27316b811bd2c130e83f
      1 549fec82bf513698b97cfa18f57856a4da879552
      1 3657a1bbd2cab4e49039e42a5d0b97670de3be79
      1 31787cb80d49db779a01fa92f10ea8bc4b29fc61
      1 2be37306ebbffc24fd6eeb96e7422c9a8552b418
      1 0e4d213c7653d0cca240f0b650958292dbabe7dd
      1 0bc8040b34ac824cf15ecd679019e2ae13d6111f


```
18 edc0f44ef3f2f9c1eb9f02f28b170d585df7b328 This player got born 18 times to this mother.
also checked this player is not cursed but lets ignore that as it is outlier, 
There are still 10 players that got born more than 5 times to the same mother

**Comment by DougLefelhocz** [comment]
Eve Boots had at most [20 players](http://lineage.onehouronelife.com/server.php?action=character_page&id=5840082).

From the numbers above Eve Volek had 31.

Eve Volek was apparently on the server before anyone else as her identification number was 2612984, while Eve Boots's number was 2612994, and Eve Happy's was 2613051.

**Comment by jasonrohrer** [comment]
This issue probably doesn't have much to do with the bad mother limit as much as when we chose to spawn a new Eve to deal with load.

In this situation, it seems obvious that there weren't enough Eves to go around, but the question is why?

**Comment by jasonrohrer** [comment]
Actually, looking at the logs, we got quite a few Eves right in the beginning.

That Eve got as many babies as she did mostly due to SIDs.  If people are going to try doing that (to get born in a city when there aren't any city-mom options, I'm guessing), that's just going to happen.

The code seems to be working as intended here, spawning new Eves as-needed to deal with a growing population after the server restart.

However, I will keep this issue open for now so I can check the more detailed logs after the next restart and make sure Eves are being spawned correctly.

**Comment by DougLefelhocz** [comment]
4 Eves for something like 60-80 people is a large amount of children per Eve.  Even 10 children per Eve before she reaches her late 30s really pushes it (4 to 6 children per Eve is more reasonable).  From what I can tell, the game has often gone through periods where mothers just won't feed children for game play reasons, because of a spike in the incoming player population, how the early Rift worked, or other reasons.  And Eves can't carry children and a basket at the same time, making it unlikely that it's worth it for an Eve to feed children (especially twins or those with the new player popup), unless the Eve can identify that child as a vet, until she has a spot with a rabbit snare, stone hatchet, and fire bow drill, and even a bit later since the temperature overhaul.  

I would seriously doubt that new players enjoy their first, second, or third life just not getting fed by an Eve.  But, that has often been the best thing for an Eve to do since there hasn't been a quickly crafted baby sling for an Eve to make, there's not all that much wild food around (due to the tall/short object bug becoming a feature and biome restrictions exacerbating lack of food), and there's little natural heat since the temperature overhaul.  And there's even more reason for Eves to be very selective about feeding children during an update period with only 4 Eves around.

I think that the game motivating knowledgeable players to just not feed innocent children, though exceptions like racist babies exist, makes for a longstanding issue that ends up making the game struggle with player retention, and thus it doesn't get all that many more players due to word of mouth.

**Comment by jasonrohrer** [comment]
Looking at the bs2 logs after this update, it seems to be fine.

However, I will check again next week.

**Comment by DougLefelhocz** [comment]
I played and ended up as a boy of Eve Pie.  She was in a grassland when I was born, and tried to feed all of her children.  She starved in her 20s.

**Comment by jasonrohrer** [comment]
Checked again this week and it seems to be much more sane after a server restart.
