### ISSUE TITLE
when there is lag

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#514]
Usually everything freezes then eventually catches and the whole scene is played in accelerated until you get to the present point.

Wouldn't it save in performance and make the games less laggy for other aswell if instead of replaying the whole scene it would  directly go to the present point?

**Comment by jasonrohrer** [comment]
Yeah, that sounds like a reasonable way for it to work.

However, the way the client works, everything is kinda simulated.

The state is arrived at by executing the messages from the server in-order.  The client doesn't know the state otherwise (the server isn't sending state snapshots that the client can jump to).
