### ISSUE TITLE
Hard to know who knows what tool

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#517]
You cant tell who knows what tool unless they are holdig it, so finding someone that knows how to use a shovel or any tool tedious.

Maybe saying the name of the tool like "SHOVEL" for example would alert anyone that knows how to use a shovel, they would see the text bubble saying "SHOVEL" from a x range and the bubble would be on the edge of screen in the direction of it.

**Comment by jasonrohrer** [comment]
Thought:

Can holding a tool that you don't know be a trigger for this kind of hint?

That seems like a good trigger... you've got the shovel in hand, and your first step should usually be to find someone around who knows how to use it already.

So I'm thinking that there could be a little blue, forced "+" speech bubble pop up above their heads when you grab the tool that you don't know how to use.

Since off-screen speech is supported now at some radius, you'd also see the + bubbles for nearby people too.

Now, if you don't find someone at first and have to wander with the tool, and you find another group of people, you could set down the shovel down and pick it up again to re-trigger the hint for that new group.

**Comment by miskas9** [comment]
BEST TOOLS FIX EVER!
