### ISSUE TITLE
Forum report:  Predictable model distribution - gingers and blacks

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#518]
sigmen4020 noticed that child display model can be extremely predictable. The "child not same model" rule may be too restrictive with single-race children.

https://onehouronelife.com/forums/viewtopic.php?id=9006

> As you all may know gingers and blacks only possess two female models whereas whites and browns possess three female models. There is also a thing in place where one model can never give birth to the same model. This means that model distribution in gingers and blacks are easily predictable since there are only two models. You are one female model, and therefore you will only give birth to the other available model. This also means that if you are ginger or black your granddaughters will always have the exact same model as you.

**Comment by jasonrohrer** [comment]
This is true!

However, it's something that will be fixed naturally when more models are added.

For the time being, I think it's good that you don't look the same as your mother.  And it's fine for grandchildren to look the same as you, because at least you have aged a lot more than them by then, so you can't be visually confused with them.
