### ISSUE TITLE
Bear cave with bear on it doesn't block movement. 

### ISSUE THREAD

**Issue by Tarr-OHOL** [jasonrohrer/OneLife#519]
![image](https://user-images.githubusercontent.com/53706597/73215199-8dfb3c00-4121-11ea-891b-903bedf7be52.png)

Basically this bug was abused for two successful apocalypses where anyone who had no idea how the bug worked would have zero chance to stop it. 

Basically: Block the tile directly in front of the bear cave with an impassible tile. 
Double click the bear cave to wake the bear up into its animation where it stands at the mouth.
While bear is sticking out of cave run through the bear tile as it doesn't block movement.
????
Profit.

**Comment by Dodg-e** [comment]
Couldn't the bear just peak out his nose and see if there is an available tile for him to move out instead of actually leaving the bear cave then heading back in.

**Comment by jasonrohrer** [comment]
The bear already does this.

If there's no place for him to go, he goes back in his cave.

HOWEVER, for any of this to work, the cave itself has to not block movement (so that he is free to walk off of it if he can).

The same is true of the ice hole with the seal leaving and a bunch of other cases.  They are non-blocking momentarily.

**Comment by jasonrohrer** [comment]
I gotta pick my battles here.... this is a minor issue with no consequences.

The perfectionist in me wants to fix it just to fix it, but it would take a few hours to fix.

**Comment by DiscardedSlinky** [comment]
Hell yeah, time for more dev approved apocalypses
