### ISSUE TITLE
not caring about gene score because overwhelming

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#523]
The more people count for the score, the more it gets overwhelming, the less you feel like you can do something about it, the less you care
Maybe for men only mother and brothers and sisters would count
and for women only mother and kids would count
this way you have between 2-5 people to take care of and not 10+

Also pls heart on chest or something to recognize score members

**Comment by Dodg-e** [comment]
Also the older they are at the moment you are born the less weight they should have since you had less of an occasion to spend time with them hence make a difference in regards to their survival.

Next level: the heart sprite could be bigger or smaller depending on how much someone counts (their weight) for your score. Sprite size percent depends on weight percent or something like that.

**Comment by Dodg-e** [comment]
Maybe weight should be divided by the amount of people that counted for score for example having 10 babies and letting one die would have less of an impact than having 3 babies and losing one.

https://onehouronelife.com/forums/viewtopic.php?pid=87674#p87674

**Comment by Dodg-e** [comment]
The goal is that someone who had a life where 10 people count for their score should not be punished compared to someone who only had 3-4 people count for their score and therefore much easier to manage hence increase your score.

If the final score is not balanced then someone who had 10+ people count for their score at the end of their life had an unfair disadvantage (or unfair advantage if they farm them for score in a prison and force feed them) in score compared to someone who had less people to keep track of.

**Comment by Dodg-e** [comment]
https://onehouronelife.com/forums/viewtopic.php?pid=87681#p87681

**Comment by Dodg-e** [comment]
Weight of each member = age of score member (how much time you have the opportunity to spend with them, the younger the more weight) + how close they are to you (unless uncles, nieces etc get completly scrapped and only the closer ones count)

Your difficulty = (weight member1)+(weight member2)+(weight member3) etc

Leveling scale = arbitrary number used to make it equal difficulty for everyone every life to either gain or lose score (no more rng with som players having to deal with 10+ score members and losing a lot and other with 3 score member that can easily climb the leaderboard)

Score is calculated depending on how long they survived but also depends on the level of difficulty in that life (the more weight) and then calculated with the server difficulty scale.

So if you had only 3 score members and make them live to 60 you will get max points but only the max that is allowed by the current server difficulty (leveling scale) since you had a much easier life than someone who had to take care of 10+ score members

Leveling scale could be a dynamic number that gets updated continuously depending on the difficulty each player has lived so far, server difficulty in other words dynamically depends on how rough each player's life was

**Comment by Dodg-e** [comment]
member1 (age of death/average lifespan player)x weightmember1 = score member1
member2 (age of death/average lifespan player)x weightmember2 = score member2
member3 (age of death/average lifespan player)x weightmember3 = score member3

etc

Your difficulty (how difficult was this life) = all the weight added

Server diffculty = every life lived on server difficulty / number of lives lived

Score difficulty = your difficulty divided or multiplied (not sure) by server difficulty

Score = the score you had multiplied by score difficulty

**Comment by jasonrohrer** [comment]
Well, I don't want to make it more complicated with weighting and such.  That only makes it harder to reason about.

However, it might make sense to shrink the pool somewhat.

Seems like grandmas should care about grandchildren, right?

Currently, I don't think men actually have it worse off than grandmas....  both have a potentially big pool.

Heart markers, maybe, but they would be everywhere visually, and mess up the look of the game.  The leadership badges only appear on clothing.

I have thought about eye color or halos or some other thing, but I haven't come up with anything satisfying yet.

There could be a /FAM thing that temporarily pops hearts up above heads (and off-screen things too, just like the tool (+) thing).

Or maybe it happens automatically for your whole fam every time a new baby is born?  So that's a family "moment".

**Comment by Dodg-e** [comment]
Yeah constant visual marker would probably be bad

Popping hearts when /FAM sounds good.

Yes reducing the pool somewhat would be nice, the closer the pool the more it makes sense to have "groups" and properties especially if it becomes a dynamic of "there is a risk of lack of ressources and starvation so it's either us or them, and i dont want a "score member" to die so having "our stuff" makes more sense than having "free stuff for everyone" but would still be a failure to have members of the other group die since you cant exchange with them anymore but at least not your "score member" that died of starvation.

**Comment by jasonrohrer** [comment]
But I also want to avoid weird incentives.

Having a G-ma sacrifice her grandchild to save her own daughter is backwards.

Maybe it has to be a rolling window, including only the youngest 5 offspring currently alive?

So you care about your kids for a while, but then stop caring about them and start caring about the grandkids?

But this would also create artificial discontinuities in the caring motivations.  You care about some kid and then suddenly stop caring when the 5th grandkid is born.

This is where the weighting would help (I care about you less, and if I have to sacrifice one, I'll sacrifice you).  However, it makes it more complicated to reason about.

ALSO, you already DO care about the younger ones more than the older ones, b/c letting them die will likely cause the biggest ding to your score.  Letting a BB die at 2 is a huge hit, whereas letting someone die at 45 is likely not a big hit.

So there is some natural weighting in there already.

**Comment by Dodg-e** [comment]
Yes but letting the 10th baby die while 9 others are alive or letting the last female of the family die and ending the bloodline should be different no?

Maybe what's important is having the most successful offsprings and not being too much punished for letting the x number baby die?

Since successful offspring that live past x years will be able to continue the lineage hence continuing survival.

**Comment by jasonrohrer** [comment]
But in real life, we care about them ALL.

We don't just put all of our eggs in one basket and let the other kids starve to make one kid as strong as possible.

Maybe the problem is something else.  Currently, letting a BB die young is much worse for your score compare to helping a BB live to 60 is good for your score.  The "dings" are much bigger than the "boosts", generally, especially if you have a high score.

This is a reality of an asymptotic, capped score.

So it is really true that you must care about every single one, and not let one die, because one dying might be worse for your score than 9 living to old age would be good for your score.

**Comment by Dodg-e** [comment]
if one dying is worse than 9 living to old age then score is really about RNG and you cross your fingers to have the smallest number of relatives possible.

yes balancing that aspect would make it that even if you have a lot of members to care about, as long as you did good your score will be good, and not get punished because you suddenly got spammed with lots of babies because of RNG.

**Comment by jasonrohrer** [comment]
Well, not 9 old vs 1 dead, but more like 5 vs 1.  See the leader here:

http://onehouronelife.com/fitnessServer/server.php?action=leaderboard_detail&id=5982

Look at the size of their negatives compared to their positives.

**Comment by Dodg-e** [comment]
i'm going to skip the number reading and mathemathics but as long as you are more rewarded for taking care compared to being punished in the overwhelming cases it should already be a good improvement.

Also the score member notification

Not sure it would be enough to make a big difference in terms of how important the score is though, but maybe this + higher ratio of tools allocated to score and not base slots + lower pool of score members (no more nieces, uncles etc) would make a difference.

Then risk of food scarcity could possibly motivate the different score families to make private properties in order to have these ressources in priority for their family and avoid losing points.

Ideally each new female that births children would have their own property since they are starting a new family and need the ressource in priority for them.

**Comment by jasonrohrer** [comment]
There is now a pointer in place to offspring babies that are born.

Regarding shrinking the pool, the reason it is so large is because various exploits have been closed.

If your sisters don't matter, for example, then you are motivated to kill them to reduce nieces and nephews.

If your mother doesn't matter, you will kill her to eliminate sibs.

Also, if I shrink it so that only your kids matter, the optimal play will be to kill everyone in your fam except your own children, right?



Anyway, for a woman, children and grand (and great grand) children matter.

For both sexes, mothers and grandmas matter.

For both sexes, younger sibs matter.

For men, nieces and nephews (an grand nieces and nephews) matter.

**Comment by Dodg-e** [comment]
Or instead of killing or getting killed they will leave and make their own place, since they are not part of the same score pool they have no reason to be together right? Since they would compete for ressources

Having smaller pools is one of the key points imo that could make the difference between having properties, trading etc or having the current big shared villages.

**Comment by jasonrohrer** [comment]
I think most of the exploits in question are for men.

Men score from nieces and nephews, so they used to have ways to reduce their pools by killing sibs (who didn't count before) to reduce their nieces and nephews.  After sibs counted, they would kill their moms to reduce sibs.

Mom and gma aren't a problem (that's just two extra people).

There is an exponential blow-up.

I don't know that having immediate offspring only (one layer deep instead of two) would have exploits, but it will be strange for grandmas to not care at all about grandkids.  Gma should be giving advice to daughter about childcare, and helping to keep grandkids alive.

**Comment by Dodg-e** [comment]
No problem for gma's but you shouldn't care for the babies of your sister for example since you have your own babies to take care of.

Then each fertile woman would have their own little family+shared ancestors, but then the issue is that you still care about your sister so you would tend to stay together instead of making a new home...

But your own babies should count (much)more than your brothers and sisters right?

So this way it gets worth to make a new place for your offspring, you still stay in touch with your brothers and sisters etc but your own offspring have priority in case you are in a "yours or them" scenario.

Also makes sense since irl you rarely see big houses with your kids sisters kids, gma,uncle etc, it does happen but depends on multiple factors but usually you get your own place, partner, kids etc

**Comment by jasonrohrer** [comment]
Women currently DO NOT care about the bb of sister.  For women, only direct descendants count.  It's always been that way.

So it's already working how you want it to work, at least for women.  Take your kids and care only about them.


Only men care about sister's babies.  Gay uncle theory.  Men have no children of their own, so their nieces and nephews count as their children.

**Comment by jasonrohrer** [comment]
Closing this for now.  A lot of changes have been added to help in this area.

Someone broke 53 on the leaderboard.

Twisted is now in second place, so it's obviously not random or outside his control.
