### ISSUE TITLE
If make transition with Last use and Reverse Use together. Transition Will broken

### ISSUE THREAD

**Issue by CSOLYOO** [jasonrohrer/OneLife#524]
![image](https://user-images.githubusercontent.com/20432375/73591475-cb006d80-4529-11ea-9903-a7cf5a3db3cb.png)

I m making a mod with ohol. And I add a transition like this.

Bowl of Rum is 4 use. Rum Bottle with Funnel is 4 use too.

When the use of bowl of rum goes to 1（last use）. And pour it to funnel bottle. The use of Rum Bottle With Funnel become 4 and not 1. I dont know where is wrong so I create a issue there.
And use the last use of “bottle of rum” to empty bowl will create a 4 use "bowl of rum". Weird.

![image](https://user-images.githubusercontent.com/20432375/73591503-3c402080-452a-11ea-93dc-1e947bff1157.png)
![image](https://user-images.githubusercontent.com/20432375/73591508-51b54a80-452a-11ea-863d-f4939e6d1fe1.png)
![image](https://user-images.githubusercontent.com/20432375/73591589-63e3b880-452b-11ea-9f69-0c6120537261.png)
![image](https://user-images.githubusercontent.com/20432375/73591590-66dea900-452b-11ea-9887-83672ef59ca2.png)
[
Onetech url here](http://moetech.onehouronelife.cn/80440-%E4%B8%80%E7%A2%97%E6%9C%97%E5%A7%86%E9%85%92)

Update: Maybe the problem are the pattern transition? But still weird.

**Comment by jasonrohrer** [comment]
Yes, this is a known issue with objects that have different numbers of uses occurring in the same transition.  Or maybe even usable objects on both the actor and trarget side.

The engine simply doesn't support this, due to the combinatorial explosion that would need to be handled in the code.  It is generating N transitions behind the scenes for an object with N uses.  If both objects had uses, it would need to generate N^2 transitions behind the scenes.
