### ISSUE TITLE
Issues to close

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#535]
http://onehouronelife.com/forums/viewtopic.php?pid=87922

**Comment by DougLefelhocz** [comment]
Again I got this message:

> Bad request. The link you followed is incorrect or outdated.

If this is just a request from high level forum people, it's just asking for people in your in-group instead of asking for open feedback, and this is a public github.  The people on the high level forums are a small fraction of players who all have their own biases, aren't new players, and by no means understand everything.  It's not impossible that such people who have joined such want special influence on the development of the game.  That the high level forums even exist shows a lack of concern for working with the general public who has been interested in the game, because there's no good reason why those people's opinions should matter more than others, and the high level forums suggest that their opinions matter more than other players a priori.
