### ISSUE TITLE
Killing and joining posse unintuitive

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#540]
I still see cases where someone is chasing a murderer/troublemaker and doesn't know how to use a weapon (uses right click without shift and drops weapon chasing griefer)

Or having to explain to someone that they have to say the posse command to join a fight

Now that we have murder mouth and timer it also prevents accidents that could happen by right clicking to drop weapon

So is the shift really necessary?

It should be kept since it alows to right click with a weapon without dropping it

But i think default killing should be right click on someone while holding a weapon, like before

It was simple and everyone knew how to use it

Now to join a posse the text command is crucial in cases where you couldn't click on someone or too far etc, but it's really unintuitive, complicated and tedious in combat situations.

So why not being able to join a fight/posse by simply right clicking on the person targetted?

Even with no objects in hand? to make it more simple to use

Obviously in some cases (wounded,sick,biome effect etc) it wouldn't allow it but other than that they serve as melee/morale support and dont need an object in hand like a berry to be intimidating.

Right click could be kill/join fight

It fits on the mouse graphical hint and makes combat 100x more intuitive

**Comment by jasonrohrer** [comment]
You can already join posse by shift-right-clicking on target person, but only if you're also holding a weapon too.  If you're holding a stick, you do need to join verbally.

The SHIFT is nice because it clearly differentiates KILL from DROP.


I don't think it's such a bad thing for killing to be somewhat hard.... to have a bit of an "expert wall" around it.

Though obviously this is an issue that we're still actively discussing in the forums.
