### ISSUE TITLE
Markers override each other

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#570]
Bells, apocalypse, home, baby, map ,experts etc

**Comment by jasonrohrer** [comment]
Bell and Apoc are displayed separately (though do replace each other).

There's a general problem of screen real estate, of course.

The core problem might be that some markers you have control over (like HOME, EXPT, SUPP, MAP).  These are only triggered or changed by your own actions.  You decide that you want to find an expert, and touch the way stone, and now you have an EXPT arrow.  You don't need the HOME arrow right now, obviously.  You issue an order, and get a SUPP arrow.  You can avoid that by not issuing an order (like when navigating long distances, you probably wouldn't, unless you were moving as a group and wanted to find a lost supp).

The BELL arrows (including apoc) are now on a different arrow slip, but they are always triggered without your control.  Would suck if they replaced your MAP, but they currently don't.

Rarely, a leader-issued order will replace your marker.  But that only happens when you're near your leader or another follower.  Still, this might be annoying sometimes, and happen outside of your control.


The MAIN bugaboo here is the BABY arrow, which pops up and replaces your arrow outside your control constantly.

**Comment by jasonrohrer** [comment]
Actually, I think the simplest fix might be to have a priority order for the temporary arrows, and not replace a higher-up one with a lower-down one.

Current temporary home arrows have these types:

MAP
BABY
LEAD
SUPP
EXPT


Seems like the priority order could be:

EXPT / MAP
LEAD / SUPP
BABY

I.e., if you have an EXPT pointer set, the only thing that can replace it is a map (or vice versa).

BABY can only pop up if you have no other temp home locations set.
