### ISSUE TITLE
Possible Oddities with instant transition system.

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#576]
Looked like a sheep may have duplicated when I killed it right as it moved.

https://www.twitch.tv/videos/572188531?t=1h51m19s

Dying bears also seemed to do an invisible move when going offscreen

https://www.twitch.tv/videos/572188531?t=3h41m51s

One that didn't - stayed on screen

https://www.twitch.tv/videos/572188531?t=3h59m14s

**Comment by jasonrohrer** [comment]
For the sheep, if you watch closely, another sheep (off to the right) is heading toward that spot, just as the one you're aiming for moves out of the way.

As far as the server is concerned, an object exists in exactly one spot.  In the case of a moving animal, it exists at its destination instantly as soon as it starts the move.

So the sheep you were aiming for was "gone," but the incoming sheep was already there.  Your client sent the "use knife on sheep" message for that X,Y location, and the server checked if there was a sheep there.  The incoming sheep was there, so it let the action go through.

This ensures conservation of matter.  However, it does make that moving sheep look like it teleports from the client perspective.  The client is "rendering" a move across time that doesn't actually exist on the server, and the server is like "the sheep here is dead now!", even though the client is in the middle of rendering the move.

I'm going to leave this alone for now, because it's such a rare case, and it would be pretty complicated to fix (the client would need to "hold" transitions for moving objects until they are done moving, client-side).

Looking into the bear.

**Comment by jasonrohrer** [comment]
Ah, for the bear, it seems like the timing of dying is too short, and if that happens while it's making it's last move, it teleports to its final location.  Making that timing a bit longer should fix it (same for wolves).

**Comment by jasonrohrer** [comment]
Wolf death was already 3 seconds, but bear death was only 1 second.  Whoops.

**Comment by jasonrohrer** [comment]
Fixed in https://github.com/jasonrohrer/OneLifeData7/commit/ab98320000915083382b8e1e96903c125381db30
