### ISSUE TITLE
User DougLefelhocz can create spam github reports.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#585]
There exist several forum posts convincingly indicating this as a serious and longstanding issue.

**Comment by DougLefelhocz** [comment]
This is merely another attempt to try to have longstanding issues with the game ignored by engaging in a personal attack instead of examining the issues.  Were this comment and [another](https://github.com/jasonrohrer/OneLife/issues/577) by Twisted, to have relevance, then it would include a discussion of the issue.  It does not, and thus this comment has nothing to do with game development.  It is merely an attempt to try to belittle serious discussion of longstanding issues so that such does not come to the surface.
