### ISSUE TITLE
Food scale CURVE instead of just multiplier

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#589]
Want to be able to weaken weak foods a lot without touching higher-value foods.

**Comment by laccy** [comment]
increase the hunger bar size and the values, so its faster drain but from a bigger food bar
maybe the top half could only be filled with cooked food, like pies or carnitas, whatever that needs more steps, not carrot or berries

multi bite foods should be the same or similar, like 4 bites, 8 bites, 12 bites
so when the multiplier is changed, the bites could be calculated from the total value 

popcorn was buffed, 1x6 was going up to 24 vs 21 on berries
but with the nerf, since it can't go below 1, gets 24 pips vs 14 on berries
so no food should be less than 2 bites to start off then it is 1 when we got 0.5 value
I guess that's enough nerfs? set a rock bottom value and multiply it first 

bite sizes could be calculated from the total value
so for 3x4 would be 1.5x4, it could be 3x2 or 1x6

similarly, the pie was 4 bites, so it hits harder since each bite is half, total value is half but the hungry work is twice worse, same for pigs, especially that is a lower value food, so killing a pig costs half of the food. Or maybe hungry work should scale with the food factor.

would be better to have a middle stage for pig and sheep so they need more investment but give more food so the hungry work doesn't matter that much, or a small stand, where you take pigs with a rope, put in the stand to kill it and doesn't cost hungry work doing this way. also, it would allow butchery buildings to be made.

**Comment by jasonrohrer** [comment]
Fixed in https://github.com/jasonrohrer/OneLife/commit/722afc6ce7a2dd1a97693ff001918df128a7c797
