### ISSUE TITLE
Food pips visual representation

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLife#591]
Can we have a visual representation of how much pips a food gives when we are holding the food?

Here is a screen how hetuw mod does it, would be perfect if you made it the same, it just looks pleasant: little dots on food bar when holding a food.
https://cdn.discordapp.com/attachments/677300246824484867/699159386479919174/2020-04-13_09_12_37.png

It's useful to know how many pips a food gives in a few cases.

If you don't like it, just close the issue, it's fine.

**Comment by jasonrohrer** [comment]
Hetuw implementation is NOT correct.  It's just a guess.

Food values are defined server-side and not known to the client, due to food scaling curve, eating bonus, and other server-side settings.

After eating, the client shows the offset that occurred (it knows how much the food went up).  But before eating, it doesn't know for sure.
