### ISSUE TITLE
Yum chain feels a bit weird with the scaling changes.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#592]
This is not a major issue but I still wanted to point it out.

Yum chaining foods gives you a bonus depending on your current chain of previously eaten unique foods. With the scaling changes (both linear and I assume gamma) this is no longer true - having a 6x yum chain only gives you 3 pips, for example, which feels a bit weird.

Would the yum chain bonus being exempt from the food scaling make sense? This would put an even greater focus on having a varied diet and producing a variety of foods in a village.

Would the yum chain being unbreakable also make sense? It would be both a buff and a nerf at the same time, as you could eat a meh food without breaking your unique chain which would be great for teaching new players about yumming, but it would also make it so you can't just make six different foods and create new chains from those several times per lifetime.

**Comment by jasonrohrer** [comment]
So the suggestion with unbreakable (which we have talked about before) was that a MEH food would just not give you the bonus, but wouldn't break your chain.  Seems like this would make building up huge chains, and thus eventual huge bonuses, much easier.

I mean, eating 6 different foods over and over isn't such an OP strategy, is it?  You get at most +6 from the last food, which is nothing.


I will change it so that YUM isn't scaled with the scaling or gamma curve, though.  You're right that it is currently confusing (you see the number on your screen, but it doesn't translate into bonus food points).

**Comment by TwistedHBG** [comment]
I think there was a misunderstanding somewhere, I don't think eating a MEH food should give you any bonus. Bonus food should be reserved for YUM foods only.

Eating 6 different foods over and over results in about 20 bonus food each cycle, which is a decent chunk of time.

**Comment by Spodnie** [comment]
I also kinda like the unbreakable chain thing. It wouldn't really affect expert players much, but it would encourage newbies to experiment with foods. It would be interesting for them I think. It would encourage people to yum and therefore make big variety of foods which also is super fun.

Ehh, you probably won't read a comment in a closed issue :P
