### ISSUE TITLE
Bears are too powerful now

### ISSUE THREAD

**Issue by themattgoldfarb** [jasonrohrer/OneLife#595]
Since you fixed the bug where wild animals won't attack if you're standing on a tile, bear griefing has become too powerful.  Its really easy to awaken eight bears on a horse cart and lead them into a town.  It can be done quickly and there isn't really a defense against it.  Fencing off the whole town doesn't work, cause they'll just lead them through the opening.  Then it's impossible to even try to lead the bears away.  Once the bears are in town, the town dies because no one can be productive while bears are in town.  Food runs out and everyone starves.  There's too many bear caves around the map to block them off or kill the bears inside.  

It's really obvious as a problem when you compare it to bobos recent grief.  With posse mechanics, it takes three people to kill anyone in a town.  After that, there is a 60 second cooldown where the griefer can't attack.  Bobo claiming success kind of showed the strength of the posse system, it took three people just to grief a town, with your new changes, that will be a lot of work to accomplish. 
 With bears, a single player is basically a large griefer gang without a cooldown.  Going through the logs, I found 6 unique players who released over 100 bears yesterday.  One player accounted for 60 of them.

I'm not sure on the best way to stop this.  

You could try making it so bears won't go within 50 tiles of a primary home well.  Bears are still a threat that need to be dealt with, but they won't instakill villages.

Another option is to make a bear eat the releaser if they release more than two without killing the bears.  They could get around this by releasing the bears slowly across lives, but that's work and griefers don't like doing work.

**Comment by jasonrohrer** [comment]
I'm going to leave this for now and see if players can figure out a way to solve it themselves.

For example, there's a new notification when a someone knocks at your gate.  This means that a town gate doesn't need to be owned by everyone to be viable.  One (or a few) people could be gatekeepers, and let people in and out of the town when they have a good reason to go in/out.  They don't need to stand by the gate anymore, because they get a VISITOR notification when someone can't get through the gate.

The other thing, obviously, is preventative bear hunting.  There may be too many bears around, but it's still worth trying.

I would also really like people to have a stockpile of arrows and bows around to deal with bad situations.  Or what about panic rooms?

There are all kinds of interesting things that I don't see players doing, and the more I "sand off" the dangers, the less they have to do to prepare for danger.
