### ISSUE TITLE
A conceive that need tapout to trigger on Dummy Object

### ISSUE THREAD

**Issue by CSOLYOO** [jasonrohrer/OneLife#599]
![image](https://user-images.githubusercontent.com/20432375/80073717-be187680-857a-11ea-876c-6d5b197ad78f.png)

This is a Sprinklers that 5 min to trigger once. And its tapoutTrigger,1,1,2,2
But when I do this, I found that tapout cant trigger on dummy object.

![image](https://user-images.githubusercontent.com/20432375/80073916-0c2d7a00-857b-11ea-8cb8-567d19a2be01.png)

I try to remove these lines to enable the tapout tirgger in Dummy Object.
But it cant work.

Jason, Can you add the support to dummy object tapoutTrigger?

TapoutTrigger can do a lot of new thing. Like the Sprinklers.

My design is. One bucket of water can water the field for 10 time. 5minutes to trigger once.

I think this can Expand your thinking of using Existing mechanism.

**Comment by CSOLYOO** [comment]
And I try to modify the Dummy's name to avoid the giving name affect the tapout Recording.
But failed.

**Comment by jasonrohrer** [comment]
I see the problem!

However, there's a good reason why Dummy objects can't be used as Triggers....  because the Shallow Wells are triggers (when they are first built), but their various use states are NOT meant to keep triggering things.

Tapout is somewhat expensive, because it has to search many cells of the map (81 cells, in the case of the well).  Thus, I want that to happen only one time (when the well is first built) and not every time the well is used.

Can you try making a Sprinkler that does NOT use the Use Dummy system?  What about making 3 sprinkler objects, each representing a "charge" left.  Sprinkler 1, Sprinkler 2, Sprinkler 3.

Each one does a tap-out on dry plants nearby, watering them.


By the way, I really like the idea of a sprinkler for watering nearby dry plants!
