### ISSUE TITLE
Shooting an animal that is about to attack while passing over an object negates the shot and deletes the arrow

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#608]
Me, about to shoot a bear:

![image](https://user-images.githubusercontent.com/43919541/81725546-4a390200-9486-11ea-88ca-a5e3bef6498b.png)

The bear gets shot:

![image](https://user-images.githubusercontent.com/43919541/81725584-58871e00-9486-11ea-8b8e-d850cef82525.png)

The bear walks over an object with a person on it and the third arrow disappears:

![image](https://user-images.githubusercontent.com/43919541/81725643-718fcf00-9486-11ea-8a5b-4482e7b72005.png)

Note: the person that is being attacked here already had a wound, not sure if that is relevant but I did want to point it out.

**Comment by cordy-123** [comment]
https://youtu.be/psVz5L3YrzI?t=1249

link to Twisted's video at the time of the bear attack
-> you can see that there were 3 arrows. then it became two.

**Comment by jasonrohrer** [comment]
Wow, you're timing is SO exact there.

The 3rd arrow is literally visible for 1 frame in the YT video.

**Comment by jasonrohrer** [comment]
This is actually pretty easy to reproduce solo.

Get a bear to chase you with 2 arrows in it.

Then stand with several non-blocking objects between you and the bear, and stand on one of them, forcing the bear to run through where you're standing on it's way to an empty tile.  When it starts running toward you, shoot the third arrow into it.  The third arrow will appear, but then as it passes you, the third arrow will disappear, and it will attack you.

3-arrow bears are incapable of attack, by the way.

The bug is in stale object tracking server-side, in the moving object record.  Will fix.
