### ISSUE TITLE
Bobo just keeps killing families.

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLife#610]
Perpetual leadership is very cool, I really love it! It's great that when we see a person griefing, we can just report about it to the leader instead of dealing with them on our own. (Could be even better if we could find the leader more easily, if you added "/leader" command that would show an arrow to him or something)

But defending against a tyrant is almost impossible.
How do we even do it? Exile the leader, then ask everyone to do the same, then ask them again to follow us? This is so unintuitive that I don't even know how it works to defend against a tyrant, not mentioning people who just want to play the game without following forums, discord etc.

What I suggest is make a command that when enough people write it, the current leader would lose their position - they would no longer be the leader, furthermore if leader is voted out, he should be  unable to be followed by the next leader. Some kind of vote or something, should not require too many characters to write, ideally no need to write leader's name.
The command should be explained in esc menu.

But who would be the next leader after voting out the current one? I don't know, hopefully you find out something nice, it should be automatic.

Another thing is that we shouldn't be able to follow other family members. That was at least one of the cases of victim families. Bobo (ginger) came into brown's fam, and brown's leader followed him and Bobo killed whole brown fam. Reasoning is that - the larger gang Bobo has, the bigger chance is that one of them will become the leader and he could just follow Bobo and let him do his stuff.

**Comment by Spodnie** [comment]
Oh, "I FOLLOW NOBODY" makes sense, I didn't know about this command, I guess almost nobody did since I saw a few videos of Bobo and nobody even tried using it, they just didn't know what to do.

But let's say majority uses this command, do they still need to form another kingdom to be safe? Do they need to follow each other? If yes, that's not good, because it requires too much coordination in times where everyone panics - that means it would never happen and we would be always losing against tyrants.

Would be great if this one command was enough to fight against a tyrant. Something like, everyone who uses it becomes temporary ally with everyone else who used it as well.
I don't know. But we really need something easy, One command wrote by majority should be enough to defend, or we will be always losing, I hope you find a good and simple solution for this.

**Comment by Arcurus** [comment]
Its very nice that now there is an intact leadership structure in towns. but as mentioned defending against a tyrant is almost impossible.  The problem is, a evil leader can simply exile and then kill one by one very fast, since a one man posse is then enough to kill.  Starting a rebellion is then already far too late. Not warning the victim does not help either.

In Bobos new video about the Red Wedding clearly you can see, that people who are being killed have no clue what happened to them (exile) they think it was a bug that Bobo abused. So they will not learn next life how to defend. Even if they learn they wont get any warning either.
Here link to the red wedding in OHOL, great way to debug: https://youtu.be/tksmE9HLfrU?t=170

There are two main problems currently:
1. Its super easy to get elected as evil leader, you either need just to wait or trick some with lot followers to follow you, the waiting Bobo speeds with his helpers who then follow their "Evil" King, since Bobo for sure does not like that "boring" work. And why should he if he has his helpful minions...

2. There is no chance to escape from being exiled and killed by an evil leader. Renaming Exile to Execute would be more appropriate under the current circumstances.


to 1: using the genetic fitness to assign the default leader could help here, especially if past lifes in this family would be considered more. Hindering to follow one with a low genetic sore if you are the top leader could also help with that. But all this still cant give a 100% protection against evil leaders.

to 2: A simple solution would be to switch back to single combat with some improvements like better noob warnings / escape ( auto run away if no weapon).

The exile / posse system could still play some role like giving speed bonus.

Alternatively the following could help to give a rebellion against an evil tyrant some chance:
- Give a chance to fight back if you are attacked
- Give a clear warning and some time like 60 sec for an exiled one to organize a rebellion or run away / exile means currently certain death, fair to have a warning about that.
- To still stop an exiled one to grief in this time he could be limited to age 3 items (only if there are more enemies then allies close to him) and / or if you hit him he drops what he holds and cannot pickup stuff for 10 seconds. The same mechanics could be used to stop any outside group who has less allies.
- if you attack someone you auto unfollow and exile him (reduces the complexity)

There seems to be also a bug that exile does not count if the posse is declared before the exile.


The pro of the current exile / allies system is, it makes killing harder for all except leaders and gives leaders / exile more power.
The con for a single person its lot more difficult to stop a griefer, since he first needs to find a leader who takes care, or needs to start a rebellion.
Another major con is an evil leader can currently easily execute all without any chance of resistance.
Also with the current system no more true group fights are possible anymore since the majority group always wins.

The question therefore are: Do we create more problems then we solve with the current system? Are there more simple solutions? 

To find out which system is better we could allow an Eve to define if their Linage uses single combat or Allie system. Outsiders would then default to the settings in the homeland.

That was my two cents to that...
I guess at least game of Throne fans will like the Red Wedding :)

**Comment by jasonrohrer** [comment]
Well, if the leader tries to solo kill you, they still have the usual slow-down and waiting period (12 seconds, I think), where the victim gasps and has a chance to flee at much higher speed than their attacker.

So, that part hasn't changed.  Solo killing is no easier that it used to be, ever.

I will add a DING message when you get exiled or redeemed by a leader that you follow, along with your current ally count.

I will also change the auto-inherit code to find the most genetically fit person (for both property and leadership).  That means the default leader will always be a good player.  Now, if that "good player" betrays you and follows Bobo?


Regarding targeting someone to kill auto-de-following them, you might not follow them directly, right?

So if your leader follows Bobo (so he's your super-leader), you can't de-follow Bobo.  Should you suddenly have no leader at all?  Like, you've lost confidence in your sub-leader too?  I guess that is how it has to work.

So, you target some leader above you, and it says, DING:  "YOU TARGETED YOUR LEADER.  YOU NOW FOLLOW NO ONE"

Then if someone joins your posse who also follows the targeted leader, it says, DING:  "YOU TARGETED YOUR LEADER.  YOU NOW FOLLOW JOHN SMITH", where John Smith is the guy who started the posse.

**Comment by Spodnie** [comment]
> So, you target some leader above you, and it says, DING: "YOU TARGETED YOUR LEADER. YOU NOW FOLLOW NO ONE"
> 
> Then if someone joins your posse who also follows the targeted leader, it says, DING: "YOU TARGETED YOUR LEADER. YOU NOW FOLLOW JOHN SMITH", where John Smith is the guy who started the posse.

I'm worried this solution won't stop Bobo, it was always hard to convince people to join posse, and once he targets you back, you will drop the weapon and you need to start another posse, people would need to keep writing "I join you", I can imagine how much mess there would be when trying to do this.

Another thing that is confusing to players is that they need to hold something when they say "I join you", can you fix it?

One command that would make you leave the current leader and join the newest one would be so much simpler in my opinion. No mess at all, you can just go and tell people to write it because current leader is killing everyone, and people would do it without all the confusion.

"I FOLLOW NEW LEADER"... 19 characters, a little too many, idk.
"EXILE MY LEADER” - this could work. It would make a new leader and leave the current one, and next people writing it would join the first person who said that.

**Comment by Spodnie** [comment]
Additionaly if a mom has living kids who are below 15 years old age, and they follow the same leader as she is, they should automatically unfollow the current leader and follow their mom when she says "EXILE MY LEADER"

So simple solution, no mess at all, please Jason...

Edit: or actually when they are below 12 years old, because then they can say, "I FOLLOW YOU".

This would make us able to save our kids.

**Comment by Arcurus** [comment]
> Well, if the leader tries to solo kill you, they still have the usual slow-down and waiting period (12 seconds, I think), where the victim gasps and has a chance to flee at much higher speed than their attacker.

not sure if this works lite that, once you mentioned that you can now be a single men posse, since exile counts negative to the required posse size. Tried to figure it out in the video, but was not 100% clear to me, since he had also some helping friends nearby, so i just asked him, lets see if he replies, at worst i have to study the code.... for sure whatever he used, it worked quite well to kill all... 


> I will add a DING message when you get exiled or redeemed by a leader that you follow, along with your current ally count.

thats great!

> I will also change the auto-inherit code to find the most genetically fit person (for both property and leadership). That means the default leader will always be a good player. Now, if that "good player" betrays you and follows Bobo?

Yea, therefore we need to have at least some chance for rebellions...
For sure its not 100% Bobo proof yet, but in future we could use it to make it harder for bad leaders to get elected like giving extra malus if you kill your close relatives or cannot even be followed if gene score is too bad,... its a starting...

Lol you can put in an East egg, if you happen to follow one of Bobos account known from the videos or a player called Bobo, then you get the message: congratulation you follow now Bobo and gave your family to a near certain death, see you next life!

> So if your leader follows Bobo (so he's your super-leader), you can't de-follow Bobo. Should you suddenly have no leader at all? Like, you've lost confidence in your sub-leader too? I guess that is how it has to work.

sounds logic, as default then following yourself

> Then if someone joins your posse who also follows the targeted leader, it says, DING: "YOU TARGETED YOUR LEADER. YOU NOW FOLLOW JOHN SMITH", where John Smith is the guy who started the posse.

sounds also logic

To Spodnie: I think holding the item is so that you have an in game way to signal when you leave the posse. dont know if it is really needed, since picking up anything other then a weapon would also be enough to signal that.

With all this posse stuff, im not sure if its worth fixing it compared to the single combat system, but since this is the way we seem to go for now i will try my best to help. At least this leadership system brings some game of Throne stories to it.... No wonder why it was so important to have a sane king if he simply could chop of your head....

**Comment by jasonrohrer** [comment]
Okay, I've made a TON of changes here.  There are now many more notifications, and ways to check your status.

But the big thing is the way leaders are automatically chosen when the old leader dies.... now through fitness instead of age.

This will make it MUCH harder for a bad actor to become leader by default.

And it order for them to become a super-leader (by getting followed by a leader), that means they will need to trick a high-fitness player into following them.  High fitness players are experts, so that is pretty unlikely.

But you now get a DING when you are exiled, and the unfollow command (I FOLLOW MYSELF) is on the help screen.

I'd like to see how things feel with these changes before changing anything else.

The "auto-de-follow when targeting a leader" thing is messy enough, with enough wrinkles and edge cases, that I'll leave it alone for now.

**Comment by jasonrohrer** [comment]
Also, this is good, because it bolsters the benefit of being a high-fitness player.  You get to be queen by default.
