### ISSUE TITLE
Sorry for another issue (Defending against tyrants)

### ISSUE THREAD

**Issue by Spodnie** [jasonrohrer/OneLife#611]
But instead of giving us a way to defend, you tried to prevent bobo from being the leader, which I'm worried won't really work, it will be just a little bit harder for him, but he will still be able to do it, especially that his gang members possibly can have high gene score. And tricking the leader isn't really hard, just be nice and work in the town, and then kindly ask the leader to follow you.
I mean, you made good changes that will improve overall leadership mechanics, but we still need a way to defend against tyrants.

Don't you like "EXILE MY LEADER" idea? It's very simple to use and would work great in all situations.

**Comment by Arcurus** [comment]
I think Jason added now at least a message for the one exiled. 
The other logic like automatic follow / exile for this update seems to be too tricky to put it in yet.

not sure  if another command would help much.

the ability to fight back if you are attacked no matter if from a single person or a posse sounds more promising. Whenever you start attacking some one, everyone should be able to attack you back. So the group can fight it out. The leaders choice would be then to decide if the fight can happen through exiling /attacking them. Attacking one could lead to auto exile the attacked one, so no need to know much about complicated mechanics. 

Further having a high murder rate during your reign or the reign after (since you are responsible for choosing your hire) could also decrease your genetic score further, but should be balanced with something positive, maybe count the genetic score twice in case if you are a leader.

**If you ask me i would say the following, keep it simple always wins:**
- use the leadership system for the order system, so an leader can easily communicate
- give the followers the chance to say some thing back to the leader (reverse communication)
- inform the leader automatically if one ally is attacked

With this in place and the new leader update a leader has it much more easy to organize his followers for an defense or attack. If he does not drill his people for combat, its his fault.

**The battle is then one on one withe the following changes:**
- the first hit does not create a wound, he lets the payer say GASP after 3 sec he can be hit again. Additionally the player gets a clear warning message to run or fight.
- if hit in the next 30 seconds again he get wounded, if not he again must be hit and says GASP
- if hit and has no weapon he drops everything and runs in fear away automatically
- optionally non deadly weapons could be introduced like sharp stones and straight wood stick
- if you hit by a non deadly weapon the first time its like with a normal weapon / you say GASP
- if the second hit is with a non deadly weapon you drop what you have in the hand, get movement speed of X 0.8 (cumulative with each hit) and cannot pickup stuff for 5 seconds
- kids before age 3 could be allowed to play with non deadly weapons, but only be allowed to use it against kids. This would help them to practice their combat skills.
- Bows loose their "auto aiming" and must predict again where the player is moving

The leader could drill his people using non deadly weapons or teach the healing with deadly weapons. The Top leader could also get some "extra hitpoint", maybe through items for leaders. 

**In summary the leadership system would be for organizing / leading people while the combat system would take care of the fighting.** Exiling ones puts them out of the command structure and marks them as exiled for the others. Additionally exiled ones and strangers could be only allowed to pick up stuff that has Age 3 requirement if more "enemies" then allies close by.

**Comment by jasonrohrer** [comment]
Well, I want to go slow here and try incremental changes.

People currently have the power to switch leaders whenever by saying "I FOLLOW YOU" near someone else.  That is pretty quick...  I understand that doing it en-masse requires organization, but that's what sub-leaders are for.

If you don't trust your leader fully, elect a sub-leader ahead of time (one person under that leader who everyone else follows).

Having a 2-leader chain, with everyone under the bottom leader, makes it much more robust against a tyrant.

If the top guy goes bad, the second in command can unfollow him, breaking his power instantly.

If the second in command goes bad, the top guy can exile him, making whoever is beneath him see him as exiled too, making him vulnerable to being killed.

Anyway, I'm interested in seeing how players work through these problems, given the new tools that they have this week.

**Comment by jasonrohrer** [comment]
Also, you really think that bobo's helpers have high gene scores?

They help him kill all their relatives.  That makes them have low gene scores by definition.

**Comment by cordy-123** [comment]
I don't watch the videos...coz don't want to give him views.

But I saw screenshots a few times where his helpers are from other races...which means in those specific instances, the helpers' gene scores don't go down/suffer since they are killing diff fams. (Since expert way stones are very useful for finding certain race towns, they can reach the targeted town by age 12.)

**Comment by Arcurus** [comment]
Using a secondary leader sounds interesting, but guess it wont work if not done by default, also i dont think it will help. The second leader can simply himself become the tyrant, so the groups would needed to be split on different leaders. This could be done for example by letting the default follow algorithm chose top three genetic score leaders and distribute the auto followers on them. so one king and two sub leaders all with equal amount of sub followers. they should of course also be informed with a message of their responsibility how to throw of the king if needed.

All that said, i think the main problem is mixing the leader system with the combat system. Already the power to inform people is quite big especially now with high score leaders having most likely more trust. This could be enough to fight off all kind of dangers from inside and outside or simple organize an escape if needed. Adding a back communication for the allies to the leader could further boost it.
