### ISSUE TITLE
Curse System should depend on time played

### ISSUE THREAD

**Issue by hetuw** [jasonrohrer/OneLife#625]
I hear from a lot of people that play a lot that they get sent to DT for no good reason but at the same time griefers are still griefing outside.

I believe that a big problem is that you have to wait 30 days to get rid of a curse and it doesnt matter how much you play in that time period.
This means you can avoid DT by buying multiple accounts, if one gets sent to DT you just use another and wait until the curses for the one in DT disappear. 
Also people who play a lot collect more curses in the same time, but the curses dont vanish faster.

This could be fixed by making curses disappear depending on the time played and not irl time passed. If someone gets sent to DT and than stops playing for a month than the next time he logs in he should still be in DT.

**Comment by Arcurus** [comment]
Another issue with the curse system is, that you can curse other family members. 
For protecting against other family members there are other possibilities like the fence system, no need for curses there.  Otherwise fighting of attackers results in a curse war.

**Comment by TwistedHBG** [comment]
IMO the good thing about curses is that you have to wait 30 days for it to expire, no matter how much you play in that time period. If I curse someone I know they're marked for 30 days. If the curse expires by playtime I have no clue how long I'm safe from them.

If curses depended on time played people could just bot and constantly respawn. In fact if I remember correctly curses last a fixed amount of days precisely because people used to bot to clear their curse time.

Also if curses depended on time played having multiple accounts would be more powerful than before. Just leave all of them online overnight and bam, you shaved off ~10 hours off of four accounts at once just like that.

Curses should last a real life amount of time as they do now.

**Comment by Arcurus** [comment]
its ok for me if a curse means, ok i dont spawn with this player in the next 30 days in the same family.  But it does not, with every curse the blocked radius is increased.

Protecting against outside attackers should not be through curses. There are fences and combat system to protect against outsiders. If he is killed i think there so or so is a family ban for a certain time, so he would need to spawn somewhere else and then come all the long way back.

Just imagine you want to help your family and get to an iron mine which is close by another family, but not fenced. The common defense now is curse him away and not defend the mine with fences.

I would also find it more interesting if a player with lot curses can from time to time incarnate in a family, but there would be a chance with each curse that other player will see him as cursed. 
The interesting story would then be, ok what to do they with him? Exile him before he makes mess? Or give hin a chance and have a close look at him.

Also currently there is no away of undoing curses. 2 out of the three curses i got was just because of walking in the wrong time on the wrong place when some one said "i curse you".

**Comment by hetuw** [comment]
`IMO the good thing about curses is that you have to wait 30 days for it to expire, no matter how much you play in that time period.`
There are always people that curse for random things. The more a player plays the more curses he/she will collect, this system currently punishes people for playing the game a lot. This is a game that punishes you for playing it.

**Comment by jasonrohrer** [comment]
Let me look at some stats....  who is cursed, currently?

934 people have at least one outstanding curse.

381 of those people have only 1 curse.

86 people have over 10 curses.

I'll do a correlation plot in a second (hours played vs curses outstanding)

**Comment by Arcurus** [comment]
> There are always people that curse for random things. The more a player plays the more curses he/she will collect, this system currently punishes people for playing the game a lot. This is a game that punishes you for playing it.

thats true especially if you take care of griefers, since most ignore griefers you get their curses if you take care of them. Thats fine if it just means not playing with the player in the same family for 30 days, but if it means more....

Maybe make curses always both way would help to let think people twice if they curse. And of course a possibility to undo curses as long as "i curse you" happen to hit innocents.

**Comment by jasonrohrer** [comment]
![Screenshot - 05262020 - 01:24:53 PM](https://user-images.githubusercontent.com/12563681/82947524-0b5e7e00-9f55-11ea-94ee-4afc4977c1c8.png)

**Comment by TwistedHBG** [comment]
Keep in mind if someone only plays to grief and they're forced into DT they're not going to play at all until their 30 days is up.

**Comment by hetuw** [comment]
i think the graph is showing that the people who play a lot get punished by this system. How many curses do you need to get sent to DT? Looks like most people who played more than 6000 minutes will go to DT from time to time, do they all deserve it?

If you have 5 curses and one of the people who cursed you is on, will you be sent to DT?

**Comment by Arcurus** [comment]
i think now with the leader exile and posse system we have now a much better way then before to take care of griefers, which before could be done only through curses. The good thing with the leader system is, that you need to have a high score to become a leader, while cursing even the bad players can do. Therefore we could make a try to not increase curse ratio with more curses for one week and see the result. So curses would only protect you from the same player spawning in the same family as you. Further curses could be always both way.

**Comment by jasonrohrer** [comment]
![Screenshot - 05262020 - 01:48:09 PM](https://user-images.githubusercontent.com/12563681/82949027-c25bf900-9f57-11ea-96a5-4a6cbd94a7e2.png)

**Comment by jasonrohrer** [comment]
The second graph uses quintic fit instead of cubic.

**Comment by TwistedHBG** [comment]
> 
> 
> i think now with the leader exile and posse system we have now a much better way then before to take care of griefers, which before could be done only through curses. The good thing with the leader system is, that you need to have a high score to become a leader, while cursing even the bad players can do. Therefore we could make a try to not increase curse ratio with more curses for one week and see the result. So curses would only protect you from the same player spawning in the same family as you. Further curses could be always both way.


Since OHOL features reincarnation curses are needed for the game to function. Leadership is not in any way shape or form a replacement for curses. The curse system was fine tuned a ton over the past year and I personally don't think it needs changing, certainly not any drastic changes.

**Comment by jasonrohrer** [comment]
Keep in mind:

There were 3807 unique players in the past 30 days.

2915 of them had ZERO curses logged.  76% of them.

The vast majority of players are never sent to D-town.

Actually, I can get you some stats about that too.

**Comment by hetuw** [comment]
If you look at the 10 people that play the game the most, they have roughly an average of 13.5 curses (if i did the math correctly), that is more than enough for DT. Why punish those who love your game the most Jason?

**Comment by jasonrohrer** [comment]
"more than enough for DT"?

What do you mean?

You only go to DT if there's no place on the server for you to be born, right?

So you're worried that all 13 of those people are online at the same time?

If you accumulate curses innocently and by accident, there will be far less correlation in those player's play habits.

Whereas, if you make 13 people mad right now, you're very likely to go to DT for the next few hours (because they're all still online and playing).

**Comment by TwistedHBG** [comment]
I bet some of the people that play the most are people who just afk and use a bot to constantly respawn (you've seen them, they exist.). Those people don't love ohol the most, they just want to annoy others. That person with 19000 minutes played has 38 curses. 19000 minutes played is 316 hours, which is over 10 hours played per day for the last month. It's decently likely that person is afk botting which is why they got so many curses,

**Comment by jasonrohrer** [comment]
The block radius is this:

50 * [number of living people who have you blocked] +
[number of total people who have you blocked] ^ 2

So if you have 13 curses total, and let's say that 2 are online (remember, this is 13 out of 3800 unique players).  Your curse radius will be 100 + 169 = 269.

So you think this person will be unlikely to find a mother 269 away from the two mothers that have them blocked?

**Comment by jasonrohrer** [comment]
163 people were born in d-town over the past 30 days.

96% of players never saw d-town.

**Comment by Arcurus** [comment]
>Since OHOL features reincarnation curses are needed for the game to function. Leadership is not in any way shape or form a replacement for curses. 

I understand why curses should protect against inside griefers, but why against outside attacks?

**Comment by TwistedHBG** [comment]
> 
> 
> > Since OHOL features reincarnation curses are needed for the game to function. Leadership is not in any way shape or form a replacement for curses.
> 
> I understand why curses should protect against inside griefers, but why against outside attacks?

There was a (thankfully short) period of time where you could only curse people in your family, and the game turned into an unplayable grieferfest . Griefers would get born in their towns and they would leave as a kid to grief a nearby town.

Conflict doesn't work in the game currently (and it never really has) because if you go attack a town you're destroying the town you're going to be born in next life, i.e. you're basically destroying your own town.

**Comment by jasonrohrer** [comment]
Anyway, it's not clear that we need to change something here, to help the lives of the 4% of players who ever visited d-town this month.

If we look at players who have visited D-town 30 times (like once a day), we see that it's only 43 players, or around 1%.

Meanwhile, there are around 10 players who have visited d-town 100s of times each, so it seems to be working in that regard.

**Comment by Arcurus** [comment]
> And the game turned into an unplayable grieferfest

you have fences and posse to stop them, With leader system, they even cant attack, so they can only do animal griefing or stealing if no fences. If you kill them, they wont spawn for a while in the same town where they came from. Curses or killing them could further changed to stop them from incarnating in the attacked town, but should not hinder them in other towns.
