### ISSUE TITLE
Eve town genetic score loss is not balanced

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#628]
This video from Twisted shows some aspect why Eve town is much harder then a running town:

https://youtu.be/-H_lJ-8dWxw?t=2660

It comes down to:
You are often in the middle of nowhere without any cloths or food.
You need to move around with all, so its lot more difficult to feed all (not all may come along).
Eve towns are much harder many stuff needs to be build first.

Possible solution:
Calculate for each generation a server average in the last 10 days of the gained / lost genetic score.
Use this average to increase or decrease gene los / gain for this generation compared to the hole average gene score loose / gain.

For example if generation 3 is in average double hard, gene score gain would be multiplied 2 and gene score loss divided by 2.

**Comment by TwistedHBG** [comment]
I think it's fine. That town had tons of food because it wasn't an actual Eve town, we had resources form an adjacent town. Most of those kids commited suicide by running into wolves while no one was looking, probably because they didn't like the town. It had very little to do with the fact that it was an Eve town.

**Comment by Arcurus** [comment]
if they dont like the town they could have used /kill which would have saved you score.
if you run around here and there to find a new place with your family the risk to run into wolfs is higher then if spawn into a normal town.

The food issue for this video / town maybe true, since there was a developed town with food nearby, but in one of your other videos, you spawned in an area without any food, just lucky you found one berry to eat in the last second.  

The food problem could be solved through changing the placement algorithm as outlined here:
https://github.com/jasonrohrer/OneLife/issues/624

Still i guess there would be a lot bigger challenge to play as eve. The main reason is simply, because its very different experience from the other life you normally have. We can of course say thats fine with us, but it would reward people who do suicide before they play eve or in a eve family to minimize gene score loss. So the one who makes the work and does an Eve village is punished.

**Comment by jasonrohrer** [comment]
Yeah, Eve town is supposed to be hard as nails.

It's a pretty rare experience, still.  The vast majority of lives are not lived in an Eve town.

So it's fine for there to be an occasional very hard mode.

And I don't want to soften the effect of an Eve town on your score, because then you would care less.  Twisted, who cares about score, is concerned about each member of his family here, and that's good.
