### ISSUE TITLE
Spawn jumped 20k west

### ISSUE THREAD

**Issue by JustinLove** [jasonrohrer/OneLife#633]
circa 2020-06-06 21:05 UTC, Eve Corn spawned near -48000, with the previous settlement around -27500. A player was active in donkeytown at the time, so it's probably considering all living players. (there was also evidence of donkeytown getting separately shifted, but at first I thought it was just within each player class)

**Comment by Arcurus** [comment]
there seems to be now three lines of eve spawns with big jumps in between...
see here: https://onemap.wondible.com/

cant we try out the alg i suggested? its designed to solve both, it limits the eve jump while it makes sure to place eve on not exploited areas.

**Comment by TwistedHBG** [comment]
I'm almost positive it's considering DT homelands when spawning a new Eve.

The first thing that comes to mind is to make it so the spawner ignores DT homelands, but then another thought crossed my mind - if DT players spawned southeast instead of southwest this would be a non-issue. Worth considering if it ends up being a quicker and easier fix.

**Comment by Arcurus** [comment]
here a link to a video how far experts are now away:
https://youtu.be/YpIG0USk-0s?t=566

**Comment by jasonrohrer** [comment]
Yes, it could be considering dt homelands.  I thought I handled that issue, but I'll take another look.

**Comment by jasonrohrer** [comment]
Also, looks like because of this issue happening over and over, we're way out in the weeds now, at coordinate 500,000+.

Seems like we might need a map wipe to rein it back in, after the fix.

**Comment by JustinLove** [comment]
I'd say the wipe isn't necessary - any restart will end separated settlements, but it kind of doesn't matter - either way we aren't near a major developed area, and even without this bug it was moving a couple thousand a day.

**Comment by Arcurus** [comment]
>Also, looks like because of this issue happening over and over, we're way out in the weeds now, at coordinate 500,000+.

does this mean because of this bug we finally are close to reaching the true end of the world?
Im curious how it looks....

**Comment by jasonrohrer** [comment]
No, we're not anywhere close to the end of the world..... that's out at +/- 2 billion.

Question:  why is it moving a few thousand a day?  That seems like a lot.

I'm thinking it's because people tend to walk far west to settle.  Even one outlier a day could push all future Eves far.  Which is the problem with this method.

I think we need an outlier-proof "kernel" algorithm of some kind, that finds the critical mass of civilizaiton.... all members of the "core cluster", and puts Eve to the west of the west-most member of that core cluster.

**Comment by TwistedHBG** [comment]
It's almost definitely DT homelands, you can see it on wondible's map: 
![image](https://user-images.githubusercontent.com/43919541/84821635-b70e6180-b01b-11ea-8249-3f5ada8dc7ef.png)

The red Eve spawned after the DT Eve, and they spawned to the west (persumably because the DT Eve made a homeland).

Also, if you check a waystone the distance to the nearest family will most likely be divisible by ~20k, and donkeys spawn 20k south 20k west.

I think making donkeys spawn 20k south 20k east would be the simplest way to prevent gargantuan distances. Sure, there is a chance for outliers to go west and make a homeland, but the real issue right now is almost definitely DT homelands.

If donkey homelands don't move spawn points, perhaps someone is spawning as a twin with a non-donkey person and moving the spawns that way?

**Comment by TwistedHBG** [comment]
Random idea that might be a decent patch solution for now - what if Eves spawned to the west of the newest homeland, but couldn't spawn more than 500 away from the previous Eve spawn point? That might be enough to make it so Eves spawn in untouched wilderness in the vast majority of cases, while at the same time preventing excessive westward drift?

**Comment by Arcurus** [comment]
fixing donkey town homeland, could reduce drastically the eve west bug.

but more long-term thought it would be nice to rethink the eve spawn, instead of constantly moving west it would be nice to be able to reclaim some of the old land. Most of what was build could of course be retaken by nature meanwhile. 

The alg i suggested should be able to fix both. one querry to test an eve location should not be much more expansive then making a query for a given players client. With round about 100 semi random queries the alg should in most cases find a nice land. And since eve spawn happens not often this should not be at all an resource issue.

UPDATE:
Just for clarification, the suggested alg starts with a small search area which is increased if no good location is found, but even with the search area increasing, still to test one location the effort is still the same, since only this location is tested. If needed i can explain it more in detail in a chat or call.  Designed at university quite a lot of efficient algs for compiler programming, this alg compared to is really simple...

**Comment by TwistedHBG** [comment]
Another example from onemap that almost proves it's a DT issue:

1. Year 61920, families are spawning near one another as expected
![image](https://user-images.githubusercontent.com/43919541/84825378-a4972680-b021-11ea-95a1-ef9ae5c39fa0.png)


2. Year 61927, donkeys spawn in DT
![image](https://user-images.githubusercontent.com/43919541/84825455-bd9fd780-b021-11ea-8f97-24c7a48cf2b9.png)

3. Year 61978, new regular Eves spawn and they spawn to the west of where the donkeys were
![image](https://user-images.githubusercontent.com/43919541/84825536-db6d3c80-b021-11ea-87de-0f3fb9a78340.png)

In the span of 58 minutes the Eve spawn location jumped 20,000 tiles. There no way for anyone to walk 20,000 tiles in that time frame, it has to be a DT issue.

**Comment by JustinLove** [comment]
The major issue is definitely DT. I've even seen what looks like DT spawns bumping other DT spawns.  

Few Thousand: (Perhaps this should be a separate issue) Before that, and at jumpless periods in-between, distances were "difficult but doable", for the most part. For the big picture on the map, select the Arc mode, drag coarse all the way to the right, and choose eves-only to keep the data size less than the server record limit (probably anything approaching a week of full lives will hit the cap, and it's been a *long* arc). There is a definite discontinuity of speed around -12000, which if you select one of them, is around 2020-05-30, when the relative distance change was made.

Looking at any of the clusters, you can see jumps of 700ish here and there. One those isn't so bad (well tapout is 200), but all the jumps can add up fast. If a family is long lived, the others start to leave them behind.

**Comment by jasonrohrer** [comment]
Whoops, there's a simple sign error in map.cpp line 8480....

The reason this problem didn't rear its head more often is that d-town homelands are so rare...

But whenever there is a d-town homeland, it would cause the Eve spawn to jump...

**Comment by jasonrohrer** [comment]
BTW, the problem with "reclaiming land" is two-fold.

First of all, if you walk West for a while, and then reclaim dead land at the East end, those "wrap around" eve placements are going to be VERY far away from the West end.

Next, as you start "walking West" again from that Eastern starting point, there's the possibility of running out of room, if the Eve spawn catches up with older civs that haven't died out yet.
