### ISSUE TITLE
Stuff was randomly appearing and disappearing (without drugs)

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#634]
For some time when i wanted to pick up stuff it was not possible anymore without any reason, then suddenly a bowl became a sharp stone while trying to fill on bucket of separated milk and other strange things magically appearing or disappearing.

After a while the bug was gone, dont know why.  If i can reproduce i will write, maybe others know more?

**Comment by jasonrohrer** [comment]
Your games are being recorded in the recordedGames folder.

Next time something like this happens, quit and drop the latest recordedGame file into your playbackGame folder, then launch the game to watch it.

If the bug is still present in the playback, you may have caught the cause of the problem, so you should email me the recording file.
