### ISSUE TITLE
Gene-score shenanigans 

### ISSUE THREAD

**Issue by MrXIX-OHOL** [jasonrohrer/OneLife#645]
Lets take this family:

![](https://i.imgur.com/pEvkPpm.png)

Osiris Edge (you) got born at T=0 and died at T=60 (age 60)
This was 41 min ago from the leaderboard so our current T=101

Holy Edge (daughter) got born at T=38 and died at T=98 (3 minutes ago)
Jake Edge (son) got born at T= 37 and died at T=97 (4 minutes ago)
Danie Edge (niece) got born at T=20 and died at T=80 (21 min ago)
Dannya Edge (niece) got born at T=19 and died at T=79 (22 min ago)
Bruce Edge (nephew) got born at T=11 and died at T=71 (30 min ago)

![](https://i.imgur.com/1VPWkk3.png)

All the relationships were correctly identified.
It looks like the nieces and nephew died while son and daughter were alive.

Maybe it can't correctly determine alive offspring when you already died?
(since all the gene-score from nieces and nephew were added after T=60)

http://lineage.onehouronelife.com/server.php?action=character_page&id=6348876&rel_id=6348876
http://onehouronelife.com/fitnessServer/server.php?action=leaderboard_detail&id=30517

**Comment by jasonrohrer** [comment]
What's the problem here, exactly?

Note that only people born AFTER you were born count toward your gene score, except in the special case of your mother and gma.

So only younger siblings and nieces count.

Also, you only count nieces and nephews, as a woman, if you have no children of your own at the time they are born.

So what happened here is that Green was born before Osiris, so didn't count as a genetic nephew.  Then Bruce, Danni, and Dannya were born when Osiris had no kids.  And finally Nameless was born AFTER Osiris had some kids, so Nameless didn't count for Osiris.

**Comment by MrXIX-OHOL** [comment]
It looks like I made a wrong assumption.

I assumed the gene-score was calculated and determined upon death of a family member. (instead of when they are born)
This way, the nephew and nieces aren't supposed to count.
In the case of Bruce, he was born when Osiris was not fertile yet.
This could be considered a weird behaviour, but is acceptable.

This case looked like a mother who played like she should by raising children, and still gets affected by nieces and nephews.

(nameless committed infant death, and therefore will not count for anybody)
