### ISSUE TITLE
Document mechanics better

### ISSUE THREAD

**Issue by exo-pla-net** [jasonrohrer/OneLife#664]
There is no information on how to start or join murder posse's on the internet.

Here is the announcement post for Posse mechanic:
https://www.onehouronelife.com/forums/viewtopic.php?id=7972

The announcement should have included *how* to start a posse / basic mechanics.

Similarly, there is no information on how to remove property fences on the internet.

Here is the announcement post for property fences:
https://www.onehouronelife.com/forums/viewtopic.php?id=6029

It should have included *how* to remove property fences. (If this was a mechanic that was later added, the announcement post should be *updated*.)

Lack of documentation serves to make OHOL hostile to new players. It doesn't serve a higher purpose. To illustrate:

- It would be _natural_ in real life to gather a posse to confront an aggressor. Even chimps do it.
- It would be _natural_ in real life to knock down a wall of a thief's den to retrieve your stolen property. Yet a player would would struggle to figure out how to do it in OHOL.

OHOL is therefore not simulating the frustrations of life, nor is it simulating communication hurdles. These are un-lifelike frustrations in an artificial environment. Which means that, in these undocumented mechanics, OHOL isn't speaking to the grander truths about life. OHOL is reduced to speaking only about itself and its own limitations. That's not interesting, and that's not fun. 

We need better documentation.

**Comment by Arcurus** [comment]
for sure documentation is missing....

that said posse mechanic currently is way too complicated then it needs to be.

First of all attacking one should be enough to join the posse against him.

Since now we have "life by the sword die by the sword mechanics" in place we could again be more "allowable" with posses. My suggestion would be to allow posses to kill once they reach three people. People who are in the kill cool down (recently killed one) are not counted in the posse. 

Additionally i think now which "life by the sword die by the sword" there is no need to restrict /die babies or any other restriction for posses. In worst case a group of three people could then try to kill one person, which makes the attacker kill able himself and therefore reduces the damage a posse could do to a village. 

This would be also a lot simpler to explain and use....

To property fences, also here the mechanic seems more complicated then needed...
Why not allow with a tool (sharp stone) somebody to put down a property fence. Once hit with the tool, the fence could go into an "damaged" state, that allows it to be removed after 5 minutes passed (it goes into Shaky Property Fence).

The owner of the property and the leader of the owner of the property could get a message that some one tries to put down his property. 

With above mechanics in place we could simplify the fence mechanics and by default let property fences not decay anymore, which would make them much more useful.

**Comment by jasonrohrer** [comment]
Arc, attacking IS already enough to join the posse.

If you need three people to kill someone, and three people attack that person at the same time, they will automatically form a posse.

The only time you need to use the "I JOIN YOU" phrasing is if you don't have a weapon in your hand, or if the target is too far away for you to target them directly.


Yes, I agree that there should be some kind of "official" documentation for the more advanced features.  I'll have to figure out where that will go.

**Comment by jasonrohrer** [comment]
I've started an FAQ here:

https://onehouronelife.com/forums/viewtopic.php?pid=101114

I'll be adding to it over time.
