### ISSUE TITLE
Tutorial Has "Noob Trap" in Teaching Berry Munching

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#668]
The player starts the tutorial with six white bars, meaning that one berry won't fill them.  The tutorial stone by the first berry bush says "STARVATION MEANS CERTAIN DEATH.  CLICK THE BUSH TO PICK A BERRY.  CLICK YOURSELF TO EAT.  PICK AND EAT MORE UNTIL YOU ARE FULL."  Thus, the player has to eat at least two (and probably more in some cases), berries consecutively to get full if they follow what the tutorial recommends.  Such berry munching gets universally regarded as poor, inefficent play with few, if any, exceptions.  It's most definitely not recommended to new players getting born into a town later than an Eve camp, and even worse if born into a generation where a berry gives but one pip without yum.

Thus, the tutorial has a "noob trap" at present.

Probably, the tutorial would be better if it were to have information about yumming earlier with multiple food types earlier in tutorial also (possibly even cooked pies, since the distinction between raw and cooked pie has confused new players in the past).

**Comment by DougLefelhocz** [comment]
To add to the above, munching on wild berries in particular at one point in time probably was different (domestic berries not so much though).  When they regenerated, and always gave 5 pips, consuming them consecutively could be the best thing to do in some situations.  But, ever since they haven't regenerated after a certain period of time, and food value decline has existed, it's hard to conceive how munching on berries could make sense in almost all, if not all, situations.

**Comment by TwistedHBG** [comment]
100% agreed. Eating several berries in a row is never a good idea, in fact it's always a complete waste of resources and it actively hurts towns. The tutorial teaches players to do this, and then they spawn into towns and devour berry bushes, which a) hurts the town, and b) gives them barely any food.

**Comment by jasonrohrer** [comment]
Yeah.... with the "life is easier for new players" settings, this is going to be even MORE of a problem.

Someone munching berries might not be wasting food, after all, because they are a new player with an extra eating bonus.

Thus, I think the food RATE should be softer for new players, without actually adjusting the Eating Bonus for them.

Otherwise, they are trained to consume foods in a certain way for their first ten hours..... and people might scold them incorrectly (if they have a huge eating bonus that the expert can't see, berries might not be so bad).


For the tutorial, it's just weird to have a pie sitting there as the first thing they encounter to eat, especially since it can be carried with them, etc.

And when traveling through the wild, I think people DO stop and eat berries from bushes that they find.
