### ISSUE TITLE
Posse mechanic currently is way too complicated then it needs to be

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#674]
First of all attacking one should be enough to join the posse against him.

Further since now we have "life by the sword die by the sword mechanics" in place we could again be more "allowable" with posses. My suggestion would be to allow posses to kill once they reach three people. People who are in the kill cool down (recently killed one) are not counted in the posse.

This would also solve the problem what to do if a leader is not in town or if its a non responding leader. 

Additionally i think now with "life by the sword die by the sword" there is no need to restrict /die babies or any other restriction for posses. In worst case a group of three people could then try to kill one person, which makes the attacker kill able himself and therefore reduces the damage a posse could do to a village.

This would be also a lot simpler to explain and use....

Either find the leader to exile him or form a posse of three through simply attacking him or joining an existing posse through "i join you".

**Comment by jasonrohrer** [comment]
Hmm... I'd like to hear more thoughts about this.

I worry about making killing any easier.

It is supposed to be really hard, and require consensus and coordination.

If the leader isn't around, then you can all pick a new leader, right?  Easier said than done, perhaps, but like I said, killing is not supposed to be easy.

Think of how adjudicated killing works in real life..... the process often goes on for years, with endless appeals.

**Comment by TwistedHBG** [comment]
I think killing currently works as Jason intended. Yes, it is complicated, but it can be done if the leader/most people in a given town agree that someone should be killed. It can be frustrating for new players that just want to kill someone for the memes, but I'm honestly perfectly fine with them being annoyed by that.

I much, much prefer what we have right now to how it was like before and I'm wary of any changes to posse mechanics because I feel it is a delicate balance. That being said killing mechanics ARE complicated, but personally I am ok with that because I understand them.
