### ISSUE TITLE
Having a noob starting score of 30 is kind of too optimistic

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#677]
i guess the most die in the beginning around 5. Maybe starting with zero even is fine, then at least it can only get better....

**Comment by DougLefelhocz** [comment]
One thing though, they get more pips maximum in old age if they start with 30 gene score than less gene score.  Yea, I'm not claiming it at all likely that they live to an old age death in their first life.  But, their gene score is higher after their first death than if it were to start at a low number like 6, so they might have more pips during old age due to its interaction with gene score.

For historical information, if you don't know, before gene score, everyone had their maximum amount of pips decline throughout their later years with 4 pips maximum at 59.  Gene score thus at least theoretically provided an incentivize to most players, since they could get more pips during old age if they maintained it at a reasonable level.

**Comment by Arcurus** [comment]
if they reach that old, they most likely yum. And yum more or less ignores the pips. I for my part never needed extra old age pips.

**Comment by jasonrohrer** [comment]
I'm pretty sure that new players don't see their gene score, and aren't aware of it.

Especially since tool slots have been turned off now, so the initial DING message that used to pop up with their current score isn't there anymore.

**Comment by Arcurus** [comment]
new players for sure see the gene score after the end. But more importantly, they will not pull down the score of others.
