### ISSUE TITLE
Standing on an empty tile that a deadly animal passes over prevents attack

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#690]
If you are standing on an object, and an animal passes over, you get bitten.

But if you are standing on an empty tile, and an animal is going to move multiple spaces (2-space wolf move) to pass over where you're standing, you don't get bitten.

Setup like this to reproduce:

![Screenshot from 2020-10-08 15:20:10](https://user-images.githubusercontent.com/12563681/95519386-d25dfd80-0979-11eb-8ce7-56b2c8d4dc8f.png)

If you drop a round stone at your feet, you will get bitten.

**Comment by DougLefelhocz** [comment]
Wouldn't a wild wolf be able to pass over a prairie tile and bite someone in that prairie with such a change?  If a player stands in badlands and the wolf bites them in the badlands while passing through, alright.  But, if a player stands in a prairie/yellow biome, and the wolf passes through, the wolf can't stop there, so it's more like the wolf has hopped through that area instead of having it's feet there.  Why would a wolf bite a human if it's not invading it's territory?  I mean, it's not a bear eating a human, it's just a bite.

**Comment by jasonrohrer** [comment]
Not sure about the prairie case, but this behavior is definitely a bug.  The fact that there's swamp there in the sample picture isn't what's causing the bug.

**Comment by jasonrohrer** [comment]
Bug happens even if the whole thing occurs in the same biome.
