### ISSUE TITLE
Exiling/posse targeting/cursing requiring the full name can be unintuitive for new players.

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#710]
If I'm Alex Smith and I want to exile Steve Smith I need to say "I EXILE STEVE SMITH". If I say "I EXILE STEVE" it will not work, even though it is 100% clear to me to which Steve I'm referring to - the only Steve I've ever known, the one in my family.

Would it be possible to make it so the game automatically appends your family's last name if there is no valid single-word target? I Say "I EXILE STEVE", the game tries to exile "STEVE", and then if there is no valid target it exiles "STEVE SMITH" instead. Same for cursing/posse targeting.

This is something I often see both new and veteran players struggling with.

**Comment by Arcurus** [comment]
it could look who is close and then auto complete the family name.

**Comment by jasonrohrer** [comment]
Yes, will do.

**Comment by jasonrohrer** [comment]
So, looking at the code, this is easy to do for everything EXCEPT for cursing.

The cursing code is more complicated, because you need to speak their name in their language, and there are a bunch of other limitations in there.  It's also a separate piece of code that I'm worried about touching and breaking.

So, I'll leave that as the one case where you have to speak someone's FULL name.
