### ISSUE TITLE
Long standing isssue clicking behind players possible solution

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#714]
The logic was that it wasnt possible because if an object had the same size as someone then you couldnt click on the player with it anymore.

Since it's only objects that interact with players that follow this logic, would it be possible that if the object in hand doesnt interact with a player then you can access the object behind the player with it.

Like for example a smithing hammer has no use on a player only on other objects so with the hammer in hand you can click on the hot steel behind someone for example.

This wouldn't help for putting berries in bowls for example because you can give food to players or use it with other objects but it would help for a lot of other transitions.

**Comment by jasonrohrer** [comment]
I've kinda made my peace with this issue.

You sometimes need to ask someone to get out of the way.  This is okay, and mirrors real life if there are too many cooks in the kitchen.  It's a funny moment.

It also simplifies the UI, because you need to be able to see something and click on it directly to interact with it.  There are no surprises.

It's not surprising that you can't click through someone.  It is inconvenient, but it does make sense.

I suppose that this rule is broken when you can click through walls and trees..... BUT, there's no way to ask them to move, so it's the only solution.  And plus, it's visually less confusing to see the object "shining through" a wall than it would be to see it shining through a person.
