### ISSUE TITLE
Auto translate for non english players

### ISSUE THREAD

**Issue by Dodg-e** [jasonrohrer/OneLife#718]
I know that this probably goes against your philosophy of the game to add a way to auto translate spoken and heard text in different languages, something along the lines of it wouldn't be what the player really said but a translation made by a computer.

But i figured that if it was an option to either have the original text or being able to choose your language and have it translated automatically then it would be ok since it would make the game accessible to a lot more players and you could always choose to have the original text which would be the option selected by default.

Plus the translation softwares have been increasingly better compared to a few years ago.

**Comment by DougLefelhocz** [comment]
I remember watching a Twitch stream where Twisted figured out that a non-English speaking player was playing with him in his town.  Instead of giving up on teaching such a person, he had the patience to stick with that person and, if I recall correctly, learned that the person was from some South American country.  Twisted then used a few words *in their native language*.  I know also that I once encountered a small group of players speaking Spanish in Two Hours One Life.  Both were refreshing moments, and I'm not sure that they would be likely to happen with an optional auto-translate feature. 

That all said, the crafting guide is in English.  The language barrier getting bypassed with a visual crafting guide would have its advantages.

**Comment by DougLefelhocz** [comment]
Also, I briefly scanned Twisted's video during the September sale.  Though one can argue that it wasn't the right time to do so, one character started singing:

"TUNAK TUNAK  TUN
TUNAK TUNAK TUN
TUNAK TUANK TUN
DA DA DA"

and more lyrics in the original language of Daler Mehndi's brilliant song Tunak Tunak Tun.  I for one wouldn't want to lose the possibility of such moments, and would they happen with people using an auto-translate feature?

**Comment by Dodg-e** [comment]
There's advantage and disadvantages to everything, thanks for pointing that out...

There's also plenty of other occasions to have refreshing moments than language barrier and the disadvantage of it in the long run is substantial, being a tourist in a country you dont speak the language is refreshing but if you plan on staying there for a longer period of time then eventually you will have to know the language of that country.

Concerning traductions in games it's rarely someone that is so dedicated to games that he will learn english just to be able to play more of them, it's the games that integrate more languages if they want to be more accessible and played by the most people around the world.

And if you want to sing some "TUNAK TUNAK" TUNES you can always disable the auto translate.

Better to have the option than not have it at all.

**Comment by DougLefelhocz** [comment]
> There's also plenty of other occasions to have refreshing moments than language barrier and the disadvantage of it in the long run is substantial, being a tourist in a country you dont speak the language is refreshing but if you plan on staying there for a longer period of time then eventually you will have to know the language of that country.

Yes, but what lanugages do OHOL characters, living in some hypothetical future, naturally speak?  I wouldn't assume it English, especially since if one was to travel among different villages, one would hear other languages more often than English.

> And if you want to sing some "TUNAK TUNAK" TUNES you can always disable the auto translate.

The problem here doesn't lie in the singing, but in the hearing.  The difficulty here lies in that such needs to get heard in the original language, or at least that people can easily hear such in the original language.  No one would, or should, control someone else's auto-translate.  But, if someone had an auto-translate feature enabled, then something like Tunak Tunak Tun wouldn't get heard in the original language.

**Comment by jasonrohrer** [comment]
I think it's fine how it works now.

English is the lingua franca in the world of OHOL.  If people want to use Google Translate before chatting, they can already do that.
