### ISSUE TITLE
Same Curse Name, Different Accounts

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#727]
Noticed two different instance of same curse name, different accounts.

Is there something in the code that should be preventing this? Or is it NOT  a bug?

Will direct message you on discord the leaderboard name and the curse names as I don't want to post people's curse names and leaderboards here.

**Comment by jasonrohrer** [comment]
Yes, this is normal, but rare.

There are 456 unique words, and each person is assigned two words at random, using a hash of their email with a sever-side secret.

There are 207,936 possible combinations.

A given person's assignment isn't tracked, because it can be regenerated on-demand using the hash.  So we can't even detect that a given combo has already been used by someone else.

This is a very clean way to do it, but it does have the downside of occasional collisions.

It could be made better by having more words in the list, or giving everyone three words instead of two.

Also, it used to be unique per sender.... so YOU could recognize people you had cursed, but you couldn't discuss that name with others, because they'd have a different name for that person.  That original design made collisions much less likely.  (Each curse sender had their own namespace, with 200,000 combos to choose from).

Now that the names are global, collisions are much more likely (200,000 combos shared by everyone).
