### ISSUE TITLE
The inside bonus can be too easy "destroyed" through open doors

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#729]
Possible solution:
increase the time that an door needs to stay open to destroy the inside boni

**Comment by cordy-123** [comment]
What is a boni?

Edit: After a month, I randomly realized you mean indoor bonus.

**Comment by jasonrohrer** [comment]
Hmm... this was somewhat intentional, because the open door creates a draft, and encourages you to close the door (damn kids leaving the door open again... this is even shown in the trailer for the game).

In terms of the bonus ending too quickly, it's meant to kinda even out over time.  If you spend time in a space where the door is closed most of the time, you will get most of the bonus.

There's also nothing in the code to further "even out" the changes to the heat map.  Either you're inside, or you're not.  There's no timing parameter that can be increased here.  Inside/outside is a binary property, and it doesn't fade gradually.

**Comment by jasonrohrer** [comment]
Ah, I see what you mean in testing this.  When you mouse over the temp meter, the "indoor bonus" flicks in an out of existence so suddenly, and drops from a high number to nothing as soon as the door is opened.

I'm fixing this to have a 10-second fade.  So it remembers the last time you were indoors, and gradually fades away the bonus over 10 seconds as long as you're still no longer indoors.  If you go back fully indoors (like the door is closed), the indoor bonus comes fully back instantly.
