### ISSUE TITLE
Permanent Removal of Players To Donkey Town is Needed

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#744]
Serial destructive players don't have any interest in playing a game of parenting, civilization building, nor playing for multiplayer survival.  They also actively try to hinder those trying to do so.

There are not enough serious consequences for such players.

There is no equivalent of a death penalty for them, since they can come back rather easily.  The only real equivalent of a death penalty would be permanent removal of players from the main play areas.

There needs to exist permanent removal of players away from the main play area (only _server access_ gets promised).

**Comment by kgbprofile** [comment]
Annoying people is part of gameplay. If you don't like it - either cope or find another game. OHOL was never promised to be your peaceful farming game. It can be peaceful and relaxing but it's not about it.
I'm gonna kill you and call you a faggot in game. See ya.

**Comment by DougLefelhocz** [comment]
> Annoying people is part of gameplay

Such has nothing at all to do with parenting, civilization building, or survival.

> OHOL was never promised to be your peaceful farming game.

It's promised to be a multiplayer survival game of parenting and civilization building.  That does imply that the game is peaceful, since war, especially offensive war isn't about survival in the slightest respect.

Your threat shows how little interest you have in playing a game for multiplayer survival purposes, since survival requires continued existence.  If you aren't playing the game for purposes of mulitplayer survival, parenting, or civilizaton building you do grief it, and anyone serious about having such a game would consider trying to get rid of you if that attitude didn't change.

**Comment by kgbprofile** [comment]
While I now see how you got that impression because you explained to me and it makes sense how you could've had that impression it's still not your animal crossing or harvest moon game. It's more like Rust and because you cannot survive alone you have to cooperate, but if there were no griefers and the possibility to have a griefer it wouldn't be the same game.

The idea behind this game is forming a society and a culture in which you can exile griefers and curse those cause substantial damage. Without them there won't be drama and if you don't like drama in OHOL then I'm afraid it's a wrong game to play. Drama and stories people get from living through it are the best part of OHOL.

Yea. Not building the civilization, no. Not upgrading towns, no. The best part and you can see it by how Jason Rorher treasures these stories by publishing on his website, the best part is human to human interaction, drama and perseverance. 

People who complain about griefers usually don't understand this game at all. It's not about building stuff. It's about what interactions you have meanwhile bulding stuff. If you have a prosperous town but no one talks to each other and nobody has great stories to tell - your town is just another minecraft, go play it with tech mods.

OHOL is about stories. You can learn more about One Hour One Life on the [official website](http://onehouronelife.com/), scrolling down to "The thinking behind One Hour One Life" and reading[ user stories Jason Rorher publishes](http://onehouronelife.com/userStoriesPage.php).

I now see the appeal for people who just want to build and I'm here to tell you that you can be very useful to community because roleplayers, people who come for drama can get sucked too much into it and the town might die and it is unfortunate. But hating on the core mechanic that made OHOL what it is and wanting to remove drama is desiring a completely different game.

Best people in OHOL for my gameplay are just people who interact like humans with each other and the worst are robotic builders. Because builders of stuff who don't interact are almost NPC-like and it removes what was in the game from the start, human interaction that makes stories. 

Remember that if I meet a griefer and escape him alive and continue our lineage I then tell a story of surviving a serial killer or a psycho and how we despite that persevered and it is amazing. And you will scream griefer. Sense the difference? Try to live through the lens of a story, it mostly makes griefers much less annoying and many times fun.

Unless griefers lead to the boring, useless, no good story ruin of your lineage, yea. When the civilization is dying and someome griefs yea. But worst griefing for me is: 1. Not playing along with RP 2. Quitting the game when born to a family you didn't wanna be born so we get dead babies 3. Having your own agenda and not following agenda of your parents. 4. Bored people who just wanna grief for no reason, having no idea, no story, no roleplay for what they do.

Yes, I don't play this game solely for survival and it wasn't a solely survival game if you read the game description or user stories Jason Rorher posts or if you read his "The thinking behind One Hour One Life" and so yes I do not play solely for survival, I play for survival of my loving family and if I am born to a cold family I might as well consider ending their lineage because I see they deserve that and that's how it was two years ago and that's how it is today.

Mind you, I'm in top players and I do get to be a leader from time to time, maybe you even had me as your leader, you might hate me, but you probably won't escape me in game, we will meet and I'm gonna parent you at some point :P

**Comment by DougLefelhocz** [comment]
>While I now see how you got that impression because you explained to me and it makes sense how you could've had that impression it's still not your animal crossing or harvest moon game. 

What are you talking about?  I haven't played either of those games, nor thought about playing them.

>It's more like Rust and because you cannot survive alone you have to cooperate, but if there were no griefers and the possibility to have a griefer it wouldn't be the same game.

So what?  Griefing doesn't enhance things whatsoever and never has.  It just makes it so that people can annoy others instead of playing in the spirit of the game.

>The idea behind this game is forming a society and a culture in which you can exile griefers and curse those cause substantial damage. 

No.  There is nothing of multiplayer survival in such, because griefers inevitably need killed sometimes.  There's also no parenting in that, since parenting a griefer isn't wise, and instead they should be abandoned at birth since they will deliberately try to wreck others trying to parent, "build civilization", or survive.  There is no point in playing with bad faith actors.  There is also no civilization building in such, because such isn't about construction, but rather controlling people.

> Without them there won't be drama 

Another lie which shows how small minded your notion of "drama" is.

> Yea. Not building the civilization, no. Not upgrading towns, no.

Yes, you are correct about such.  Consequently, such has nothing to do with the game as advertised and never did.

> The best part and you can see it by how Jason Rorher treasures these stories by publishing on his website, the best part is human to human interaction, drama and perseverance.

That "publishing" doesn't mean that he treasures such stories.  It just means he lets people speak on his forum.  It's not a value judgment from him.

> People who complain about griefers usually don't understand this game at all.

You won't play in the spirit of the game, but you presume to talk about how you understand the game?  Please, you don't even have serious experience with playing in the spirit of the game, nor serious thinking about how to go about for yourself.  So, how would you know since don't have relevant experience, nor even a relevant thought experiment?

> It's not about building stuff. 

Then the game is falsely advertised, since it gets advertised as being about "civilization building".

> I now see the appeal for people who just want to build and I'm here to tell you that you can be very useful to community because roleplayers, people who come for drama can get sucked too much into it and the town might die and it is unfortunate. But hating on the core mechanic that made OHOL what it is and wanting to remove drama is desiring a completely different game.

Greifing is not a core mechanic.  It also can't be a core mechanic for any game, because by definition griefing goes against the core of any game.  If it is thought that griefing can be a core mechanic of any game, then the person thinking such doesn't care at all about making a consistent game.  Inconsistent games have no vision whatsoever, because there is no real, substantial thought of a coherent product.

> Best people in OHOL for my gameplay are just people who interact like humans with each other and the worst are robotic builders. Because builders of stuff who don't interact are almost NPC-like and it removes what was in the game from the start, human interaction that makes stories.

The game isn't advertised as being about stories that go contrary to civilization building, parenting, and multiplayer survival.  And if it were, the advertisement of the game would be inconsistent and effectively meaningless for a broad scale scope of people.

> Remember that if I meet a griefer and escape him alive and continue our lineage I then tell a story of surviving a serial killer or a psycho and how we despite that persevered and it is amazing. 

I don't remember such every.  And I don't find anything amazing in such.  I find such utterly boring.  It's not consistent with the game as advertised.  It shows that bad people exist, instead of showing the potential of people.  It just draws attention to the bad nature of some people or what is necessary instead of what is desired.  It has nothing inspirational in it whatsoever.  People quit playing multiplayer games often because of griefers, and that should be common knowledge.

> Unless griefers lead to the boring, useless, no good story ruin of your lineage, yea.

They do lead to such when they are most effective.  Players who grief over and over again, eventually accomplish such.

> But worst griefing for me is: 1. Not playing along with RP

That isn't necessarily griefing.  It could lead to better or more parenting, civilization building, or multilplayer survival.  No one is beholden to play as you want them to personally, and not role playing as you like, or at all, is not griefing.

> Having your own agenda and not following agenda of your parents. 

That could lead to more multiplayer survival or parenting or civilization building for players on the server as a whole.

> Yes, I don't play this game solely for survival and it wasn't a solely survival game if you read the game description or user stories Jason Rorher posts or if you read his "The thinking behind One Hour One Life" and so yes I do not play solely for survival, I play for survival of my loving family and if I am born to a cold family I might as well consider ending their lineage because I see they deserve that and that's how it was two years ago and that's how it is today.

This shows how hollow that the game remains for you.  You don't consistently try to play for multiplayer survival.  You haven't developed any sort of fortitude to endure playing in the spirit of multiplayer survival even when temporary emotions affect you.  That's on you, and no one else.   Also, no, they don't deserve that.  This game isn't about your own personal emotions.  It's a multiplayer game, not a singleplayer game where there aren't (apparently) any consequences to other people as a result of your behavior.  If you're not playing for multiplayer survival, parenting, or civilization building, that indicates that you're not playing in the spirit of the game.  And if you're not doing that, then you need to rethink your utterly boring practice of doing things on your own emotional whim, instead of having the fortitude and endurance to stick with a concept even when things get rougher.

**Comment by kgbprofile** [comment]
Go play minecraft on peaceful mode. One Hour One Life already gets as low as 20 players online, it is already ruined by curse system, by vote kill and races.

**Comment by DougLefelhocz** [comment]
You probably don't want me to play, because you don't want to have to confront the possibility that you have been doing something wrong by griefing.  You would probably rather not have to take the concept of the game as advertised seriously, so that you can maintain your belief in yourself as never doing anything bad.  You would probably rather be able to feel you were always in the right by deliberately making bad experiences for other people than to have to admit that you were wrong and misjudged things.

The curse system has the advantage of some possibility of control of bad actors.  It is not strong enough and never has been strong enough, because it's nothing like a death penalty with respect to the game, because a death penalty for any multiplayer game is permanent removal from it, or permanent banishment from its multiplayer aspects as much as possible.

**Comment by kgbprofile** [comment]
Griefer is an important role in the game. 

Here's what Jason has on the matter:

"Reality is about the balance between chaos and order.  Maintaining order is something to strive for, and gives life meaning."

"Without the threat of at least some chaos, there's nothing to strive for, and nothing to fight against, and nothing to organize around."

![image](https://user-images.githubusercontent.com/75736768/121818789-53545e00-cc9a-11eb-8e43-16c358cbf4f7.png)

**Comment by DougLefelhocz** [comment]
Griefing goes against the spirit of a game by definition.  If 'griefer' is accepted as a role, then the game is hollow and has no spirit, or the game is inconsistent.  Hollow games are shallow and trash art at best.  Inconsistent games have the same problem.  An inconsistent game without any spirit has nothing visionary in it.  Any game with a vision is both consistent and has a spirit.  

Also, Jared Johnson doesn't have any financial or other interest in this game so far as I know.  As far as I know, Jared Johnson might view the game as competition for people's time away from Jared Johnson's game or game project.

**Comment by jasonrohrer** [comment]
Anyone who was very motivated to grief and was eventually perma-banned to donkeytown would just buy a new account.
