### ISSUE TITLE
Eve Spawns Far Right of Living Families

### ISSUE THREAD

**Issue by DougLefelhocz** [jasonrohrer/OneLife#756]
Apparently, there's some bug or deficiency in the outlier code.

It's pure speculation, but it's possible that someone made an iron unlock far right (more than 6k) of living families at the time, since some family hadn't already done an iron unlock.

**Comment by JustinLove** [comment]
At 2021-07-11 12:46 UTC, Eve Basil appeared at -33566,-282, when all other families were around -42000; the Rest and Mexican families appeared to be in good health, and Chocotech was just dying out. I couldn't find any eastern famuse objects that preceded her arrival. Eves continued to spawn in the area, though of course the arrival of players likely started creating wells there.

Note: apocalypse a few days ago, the vicinity of that area was built up in the previous map, no new bell towers completed since the reset.

**Comment by JustinLove** [comment]
2021-08-16 10:47 UTC, a nameless eve player id 4396173 appears around -41402, at this time it looks like the Carpo family is just dying out and Martin is still going around -63000s. In the maplogs I didn't see any player change starting with -4 prior to the eve, today or yesterday. Afterwards all new eves are at the new far east location.

**Comment by jasonrohrer** [comment]
I'm guessing this was fixed by https://github.com/jasonrohrer/OneLife/commit/3367b9abc535e134f2c5937748856e4d971f51ec
