### ISSUE TITLE
Can't initiate private server

### ISSUE THREAD

**Issue by AVFD** [jasonrohrer/OneLife#762]
I followed the steps to install the private server, but I can't find the file to start the server.

See this image, that says the next step to run my server:
![image](https://user-images.githubusercontent.com/18308993/123480588-f3827f00-d5d8-11eb-861e-1440e108c236.png)

When I access the folder I can't find the file indicated (see the next image):
![image](https://user-images.githubusercontent.com/18308993/123480707-1f9e0000-d5d9-11eb-8153-4f7044b573be.png)

I really wan't to start my private server to play with my friends only.

**Comment by AVFD** [comment]
I don't know if the file is missing, or the indicated file is wrong.

**Comment by jasonrohrer** [comment]
You can see that "make" didn't work there:

`make: command not found`

So your build failed, which is why you can't find the built files.

You probably need to install make, among other things.

I'm not familiar with the "ubuntu on windows" environment, but you may want to try this on a real Ubuntu machine as a sanity check.  These are available from Linode for only $5 per month, and if you only use it for part of the month, you only pay for what you use.  It might be like $1 if you only have it up for a few days for testing.
