### ISSUE TITLE
Disappearing, disconnecting, banana truck

### ISSUE THREAD

**Issue by D-rey-a** [jasonrohrer/OneLife#784]
For some reason, a delivery truck full of backpacks, that are full of bananas, glitches out the truck. I'm guessing it is some kind of container issue, but it doesn't happen with, say, cactus fruit. You appear to run at the speed of the truck, but cannot get out, and any attempt at interacting with environment causes me to dc.

You can take the backpacks out and it returns to normal function. and it only happens with the 21st backpack of bananas.

This also happens with wild garlic if they're related somehow.

**Comment by jasonrohrer** [comment]
Ah, wow, I'm able to reproduce this!

I also noticed that when you insert the 21st backpack, no sound is made.  The other 20 backpacks make the usual "thud" sound.

Also, if you insert 20 backpacks and then something else (a branch), the thud sound is made, and the truck works fine.

**Comment by jasonrohrer** [comment]
Ah, found it:

`char idBuffer[500];`

When the client is parsing incoming MAP_CHANGE messages (MX), it scans the ID string into a buffer with a 500-character limit.

For a delivery truck loaded with backpacks full of bananas, that string is longer than 500-characters, so it gets cut off.  Bananas and wild garlic trigger this because they were added to the game later, so they have higher, 4-digit ID numbers (2143 for bananas).  Thus, they take up more space in the string.

The full MX message once the truck is fully-loaded looks like this:

```
MX
4 1 0 4654,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2144:2144,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143,198:2143:2143:2143:2143 38520

```

And you can see how long the ID string is (all those commas and colons, for all those contained and sub-contained items).

The PLAYER_UPDATE message (PU) suffers from the same issue when you go to pick up the full truck.

I'm still looking into what actually happens when this part of the message gets truncated... it seems like total chaos is likely, though.

This is a pretty easy fix, fortunately.
