### ISSUE TITLE
Radeon compatibility issues

### ISSUE THREAD

**Issue by teliot** [jasonrohrer/OneLife#796]
A limited sampling from my small group of friends that play OHOL has shown that people with AMD setups get terrible performance with the game.

A very beefy AMD cpu/gpu runs fine, however someone with mid-tier AMD/Radeon laptop struggle to walk around a town, while an old entry level Intel/Nvidia laptop has no issues in game. This makes me think that Radeon is unsupported by the game client.

Someone I know has a very good laptop with AMD cpu (Ryzen 7 6800H) and Nvidia gpu (RTX 3050 TI) that plays fine when manually forced onto the Nvidia gpu. However when they change their MSHybrid to auto the game client switches to the integrated Radeon gpu and lags. This shows your client has no support for Nvidia Optimus/bbswitch to switch the gpu (something DirectX and maybe even Vulkan do automagically) and that the client does not perform on this Radeon graphics card. Your steam game page shows system requirements of [GeForce G2100M](https://www.videocardbenchmark.net/gpu.php?id=1371) or better but the [second half of this video](https://youtu.be/F7pz90tpw8Q) shows when MSHybrid is set to auto and the framebuffer changes to its [Ryzen 7 6800H with Radeon Graphics](https://www.videocardbenchmark.net/gpu.php?id=4584) video card.

I have tested the game with an Intel 3770 and a GeForce 970 (circa. 2012 - 2014) and had no issues but have no older or entry level AMD/Radeon hardware I can test on.

~Tux

**Comment by jasonrohrer** [comment]
My guess is that these AMD systems are running OpenGL in software rendering mode, and not using the GPU to accelerate it.  This happens when OpenGL isn't supported by the GPU driver for whatever reason.

This is fixed by either updating the GPU driver or installing some special package that adds OpenGL support... or maybe turning OpenGL on in the graphics card control panel.

Or maybe AMD's OpenGL support just isn't that great?

https://www.reddit.com/r/Amd/comments/p3vxsn/why_does_amd_have_such_garbage_opengl_support/

But OHOL uses a tiny fraction of the CPU and GPU resources of any big 3D game.... so as long as it has some hardware acceleration, it should be smooth.  This makes me think the OpenGL software mode thing is the issue.

**Comment by teliot** [comment]
AMD does not have OpenGL support, have to use Vulkan

**Comment by jasonrohrer** [comment]
I haven't heard of Vulkan.... but it seems like support for it is incomplete on many platforms?

https://en.wikipedia.org/wiki/Vulkan

**Comment by teliot** [comment]
That's not the case. And I would suggest HTML5 over Vulkan.

The issue is mid range Radeon cards can not play the game, AMD does not support OpenGL.

**Comment by jasonrohrer** [comment]
HTML5?  For a game written 100% in native c++ code?

**Comment by jasonrohrer** [comment]
Anyway, I'm going to close this for now.  I'd really have to get in front of some Radeon hardware myself to see what's going on.

However, the game runs pretty well on modern integrated graphics chips (no GPU).

The laptop that I develop the game on is 15-years old...
