### ISSUE TITLE
No temp bonus for babies. Intended or a Bug?

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#818]
Currently, babies (children below age 3) do not get temp bonus from rooms.

Is this intended (coz this would make the baby more hungry and therefore, more interaction between mother and baby) or a bug?

**Comment by TwistedHBG** [comment]
I remember this being intentional

**Comment by jasonrohrer** [comment]
Yes, this was intentional, see:

https://github.com/jasonrohrer/OneLife/commit/ee1bbbc5258a3ca44ad0e4d10dc9eb3043bbbbdb

The idea here is that the indoor bonus was so big that it would swamp babies so that they'd rarely need to be fed, which would subvert the interactive relationship between mothers and their babies.

Right now, you can already dress the baby and put them near the fire, which slows down their hunger a lot.  But the +20 seconds per pip indoor bonus would make it so that a baby would only need to be fed once or twice before growing up.
