### ISSUE TITLE
There seems to be no way to tell client not to update 

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#826]
Updating the Data Version breaks connecting to custom servers without a chance to not update the client.
Therefore it would be nice to have a setting to not update the client.
At best the setting could be where the IP for custom server is placed.
Alternatively the client could only update if the custom server set in the settings is updated.

**Comment by jasonrohrer** [comment]
Thanks, I will look into this.

**Comment by jasonrohrer** [comment]
What happens when you enable this in the settings folder:

useSteamUpdates.ini

Set it to 1.

That should block the auto-updates from happening.

But the other confusing thing here is that required_version_number with the update server URL should only sent to you upon connection to an auto-assigned server (using the reflector).  That should be bypassed when connecting to a custom server.

And your custom server will also send you a required_version_number, but I think the client will just choke with a version-mismatch error message (it won't auto download an update at that point).

**Comment by jasonrohrer** [comment]
Yeah, testing this... with a custom server, I get a "version mismatch" message, but it doesn't try to download an update.

However, logging into a non-custom server immediately tries to download an update.

And useSteamUpdates.ini works to block it from downloading updates.

If the question is... can you somehow connect to a version-mismatched server on purpose (and bypass the client blocking you from connecting).... we can discuss that.

But I will close this for now.
