### ISSUE TITLE
Camera aiming doesn't work and photographs are taken from a seemingly random area

### ISSUE THREAD

**Issue by TwistedHBG** [jasonrohrer/OneLife#827]
The camera aiming outline has never worked properly since day one. The photograph takes a snapshot of a seemingly (random) area between the actual object and the visual outline displayed on screen. Since the outline encompasses a 3x4 area and the photograph is about a tile and a half, you never know what you're going to take a photo of until you've taken it and checked online.

As far as I am aware, the zoomout mod has a feature that fixes this and shows the correct target area.

In a recent life I took five photos, and all of them took a snapshot of a different area within reach. I've overlaid the actual photos I took (found here - http://photos.onehouronelife.com/server.php?action=photo_appearances&server_name=bigserver2.onehouronelife.com&player_id=6296915) with my ingame view as I took them (on the first one there is a slight discrepancy with a person's legs as they moved right as I took the photo but it is the same photo).

I'm attaching those images so you can see the target area seems to be always different, even when the camera is on the exact same tile.

![Camera1](https://github.com/jasonrohrer/OneLife/assets/43919541/2ff8f550-2b2c-45f2-8369-0ce7d63b4fb7)
![Camera2](https://github.com/jasonrohrer/OneLife/assets/43919541/317aa54b-4747-4f00-bc3d-0e8067a792ad)
![Camera3](https://github.com/jasonrohrer/OneLife/assets/43919541/aa00b4a1-8856-4af5-8281-00a444a09a59)
![Camera4](https://github.com/jasonrohrer/OneLife/assets/43919541/77d22954-99f4-4590-991e-1d02f48088d9)
![Camera5](https://github.com/jasonrohrer/OneLife/assets/43919541/0fb7e343-d1ba-4191-ac99-f150b30479ff)

One thing that comes to mind that might be the cause is monitor resolution. I've played both on 1080p and 1440p resolution monitors and the photographs never worked properly, but maybe they work fine with 720p?

**Comment by jasonrohrer** [comment]
Yeah, hilariously, I don't think I ever tested this on anything but the native 720p...

It does work perfectly at 720p, though!

It's an interesting problem, because the pictures are a fixed resolution (400x400), but the game is a variable resolution.

And the "aiming thing" is actually part of the camera object.  It's just a sprite, just like anything else (which why you can see it bobbing as you walk around with the primed camera).

So that means that the aiming thing gets scaled with the rest of the game.  It's not a smart or special sprite, or part of the UI... it's part of the world.

What should really happen here is that a larger picture should be snapped on larger screens, and then it should be scaled down to 400x400.
