### ISSUE TITLE
Seeping Endtower Base does not monumentCall

### ISSUE THREAD

**Issue by teliot** [jasonrohrer/OneLife#829]
Only level 3 "Seeping Endtower Base monumentCall +normalOnly" will ring the server. I play a descent amount and always go to stop these but levels 1 and 2 never monumentCall.

Would it be possible to make it call X number of times? once for each stone in the stack?

**Comment by teliot** [comment]
People in discord were saying they heard the lvl 2 I took down. They heard it when I looked at it, and by the time I approached it it was seeping (I assume it transitioned when I got into the area). Not sure what is up with the inconsistency. I understand not wanting to monumentCall every hour but maybe they could for the first 3 hours or something?

Would it be possible to change its bell to be longer for each level? Maybe shorten the current sound for level 1, have the current sound for lvl 2, and then 2 separate longer sounds for 3 and 4?

**Comment by jasonrohrer** [comment]
Unseen objects don't do anything at all.  They are frozen in time, because there are more than 18,000,000,000,000,000,000 tiles in the world.  So it's normal that a remote tower won't make a sound when it seeps until someone walks up and sees it seeping.

And all the seeping ones do make a local sound... just not a server-wide sound until level 2, 3, and 4 seep.  Which seems like quite enough warning.

Otherwise, it's pretty easy to make level-1 towers all over the place and create a bunch of false alarms.  But if someone is really tending one long-term, you will get the server-wide warning sound.
