### ISSUE TITLE
Murder

### ISSUE THREAD

**Issue by Rae5175** [jasonrohrer/OneLife#837]
When someone is bloody and slow, after they have killed another player, any player can do a terrible solo murder on that person (without a posse). This issue has led to my tragic demise as leader after doing my solemn duty to rid the town of a griefer. I have also killed a different griefer this way after they murdered an innocent civilian. But, yeah, that’s the whole thing! I didn’t realize  this was a bug. Sorry it took so long to find my password and report this to ya! :)

**Comment by cordy-123** [comment]
Not a bug.

Yeah, that mechanic is there so that if a leader tries to kill the whole fam thru exiling and murder, the fam can fight back.

Without this mechanic, the leader can just slaughter the whole town.

**Comment by Rae5175** [comment]
I had a problem killing a leader this way (who slaughtered the few people left in town), so I sent a question about it. I still don’t understand what happened and why I couldn’t kill the guy who was literally standing still. Lol. Anyway, Jason asked me to submit it as a bug report, so I did, eventually. Haha

**Comment by cordy-123** [comment]
I've never had that problem before when killing people holding bloody weapons.

**Comment by cordy-123** [comment]
A look at your discord posts, Rae, shows some of the answer.

Rae:
"Holy moly. I just realized why I couldn’t kill the guy who killed off the few remaining Strawberries last night. I am embarrassed, and that guy was right when he called me “dumb”. Lolol" https://discord.com/channels/328215300279500800/328215300279500800/1112809299744411770

Rae:
"I didn’t say I was going to kill him. Like, killing 101, Rae." https://discord.com/channels/328215300279500800/328215300279500800/1112809867644776468

----

Although later on you said

Rae: 
"If you don’t have to say it, I have no clue why it didn’t work. I tried a knife and an arrow. 🤷‍♀️"
https://discord.com/channels/328215300279500800/328215300279500800/1112816178528780328

Then the conversation in discord turned confusing so I don't know what the conclusion was on what happened.

**Comment by Rae5175** [comment]
Yeah, I was confused too, which is why I sent the email to Jason. Lol. He said he thinks killing someone this way is a bug and to send in a bug report. So, here we are. Since he makes the game, I assume he’s the one who would have the final say-so. Haha
________________________________

**Comment by cordy-123** [comment]
Before the Bloody Weapon Vulnerability mechanic was enacted, you would definitely have old-time griefers kill all the fertiles in less than 5 minutes. 

Since once you get leadership (naturally thru gene score or thru scamming the old leader), you would be an UNSTOPPABLE FORCE.

Getting people to follow a new leader within 2-5 minutes that it would take to murder all the fertiles would be impossible. As most players do not even know how to do so. 

-----


Here is the original github issue that led to Bloody Weapon Vulnerability mechanic. https://github.com/jasonrohrer/OneLife/issues/648

From Jason's update that week (https://onehouronelife.com/forums/viewtopic.php?id=10014)
Jason's quote:
"Next, there's a new exception to the posse and exile requirements---something like "**live by the sword, die by the sword**."  Someone who kills becomes vulnerable to being solo killed, without being exiled or having a posse form against them, for 60 seconds (the same amount of time that they are stuck holding the non-sword murder weapon).  **This helps people deal with the "evil leader" problem.**  **The current leader is the most powerful in terms of being able to exile, which means that dethroning them requires quite a bit of political willpower.  If that leader goes on a unilateral killing spree, organizing collectively to de-follow them---to strip them of power---can be really difficult.**  One of the early ideas for justice in the game was "safety in numbers."  As long as the citizens outnumber the griefers, the citizens should triumph.  That idea resurfaces as we differentiate good killers from bad killers.  **The good ones will need to be protected by others while they are in their post-kill vulnerability state.  The bad killers, who are acting alone and without the approval of the group, become fair game for everyone.**  The 60 second window of vulnerability is a live server setting, and may be tweaked in the future.  It could be even longer than the murder weapon hold time."

**Comment by jasonrohrer** [comment]
Thanks for posting this, Rae!  I does give us a chance to revisit the issue and think about why it is the way that it is.

I'm going to do some testing and verify that you can solo kill a leader who is holding a bloody weapon... that is how it should work.

**Comment by jasonrohrer** [comment]
Just tested it, and it seems to be working.

There's a pop-up message that says, TARGET HAS KILLED RECENTLY, SO %s CAN BE KILLED SOLO.

And it works... you can indeed target and kill them while they have the bloody knife in their hand, even if they are the leader.

killerVulnerableSeconds is currently 60

**Comment by Rae5175** [comment]
Thank you!
________________________________
