### ISSUE TITLE
If mothers can curse their babies we should be able to curse our mothers

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLife#839]
Mothers can curse /die babies for no other reason than that, we should be able to curse the mothers that leave us to die or kill us intentionally.

Make curse a command like /leader is.

**Comment by jasonrohrer** [comment]
This is one of those things where "growing up" is supposed to give your more capabilities.  Babies can't talk, so they can't curse people.  They aren't vocal enough to utter the words.

Especially since curses are personal instead of global (which I see that they were already by the time you posted this)...  it doesn't seem that terrible that you can't curse your bad mom.  "I don't want to be born near her ever again."

Yeah, mom's can say they don't want to play with players who use /die... okay.  It's unfair, but being a baby is unfair.
