### ISSUE TITLE
Low pop server Eves should crave all food

### ISSUE THREAD

**Issue by DiscardedSlinky** [jasonrohrer/OneLife#842]
While we are Eves we usually have very advanced towns and It'd be nice to crave some of the higher tier foods. 

I think I've picked every single piece of wild garlic on my low pop server

**Comment by DougLefelhocz** [comment]
The problem here lies in how reincarnation works; it doesn't put people onto the same family tree when Eve chaining.  If reincarnation would put people on the same family tree if they live to 60, or if they choose to get reborn into the same family even if no mothers are around by a choice screen, then a person on the 6th life in a row Eve chaining could have different cravings than on generation 1, since such a player would be generation 6 instead of generation 1.  Reincarnation on the same family tree under certain conditions such as living to 60 could also resolve the longstanding problem of lineages not being able to survive updates.

**Comment by DougLefelhocz** [comment]
I guess a counter that starts at 0 for an Eve spawn and increments by 1 each time a player Eve chains would work.  The counter could reset to 0 if the player loses their Eve spawn.  If the counter >= 1, then the generation of the last child of the Eve becomes her generation upon return.  Since Eve chaining location survives updates, maybe that could allow lineages to survive updates.

As another idea is set a counter that start at 0 for the player's account.  If player is an Eve and their age of death is 60, then the counter gets incremented.  If the player is an Eve and their age of death is before 60, then the counter variable becomes 0 again.  If the counter >= 1, and the player is an Eve, then the generation of the player is the counter's number.  I don't think that Eves would inherit their own cravings that way.  Maybe the counter only increments if the player is an Eve, their age of death is 60, and they satisfy a certain number of cravings in that life, or alternatively a certain proportion of the cravings in the set of all cravings for that life.  Maybe there's a cravings list that is attached to any player's account, which only gets activated if the counter >= 1.

**Comment by Arcurus** [comment]
why not let a player incarnate to an dead family as long as there is a grave there.

**Comment by DougLefelhocz** [comment]
> why not let a player incarnate to an dead family as long as there is a grave there.

That could override all Eve chaining mechanics.  It also could mean that someone incarnates to a family in a later generation, and never ends up knowing anyone in the history of that family before them.  Also, with multiple graves on a server, where does the player incarnate to?

Maybe there's more to your idea than you've stated though.

**Comment by cordy-123** [comment]
Food is already very easy in low pop towns. Coz there's no generational food decay.

Just ignore the cravings?

Presumably any changes Jason does to this would have to be work-intensive since it would only target LOW-pop eves? Not including active server Eves

**Comment by jasonrohrer** [comment]
Yeah, there is special code in place to force you to eve spawn back near the same location in low-pop mode.  I will look into how the cravings are gated.

**Comment by jasonrohrer** [comment]
Unfortunately, looking at the code, while it's pretty easy to detect the condition where a solo server Eve is present, it's much more involved to detect how far along she is.

She respawns in her same camp as long as she keeps living to 60, and we have a DB tracking the location of this camp (based on her last death position), but that DB does not track how many times she spawned there.

So we can't easily tell how far along she is (without scrapping and reformatting that DB, which would unfortunately have the side-effect of erasing all the Eve camp markers on the low pop servers).

One alternative, which is what you're asking for, is to make all solo Eves simply crave all food, right from the start.  This means that they will be much less likely to get a boost from low-tier craved foods early on, since they might start out by craving a high-tiered food.

However, one interesting thing is that cravings reset with each new lineage, so they will crave something different next life.  Thus, the won't be stuck craving Garlic Shrimp forever, life after life.

I think I'll do this for now, and we'll see where it goes from here.
