### ISSUE TITLE
Dried Corn Backpacks in Truck cause fatal error.

### ISSUE THREAD

**Issue by QuirkySmirkyIan** [jasonrohrer/OneLife#843]
Similar to the 21 banana backpacks in a truck with dried ears of corn it does this as well. Where your movespeed gets messed up, you can't interact with things and if you reload the game your character gets messed up and you get sent somewhere else.

**Comment by jasonrohrer** [comment]
Hmm... this was fixed in general (for all objects) in #784

When I fixed it, I tested it with Bananas in backpacks, and it was fixed.

I just tested it with Dried Corn in backpacks, and it's still fixed and working fine.  They both have 4-digit object ID numbers, so they should both trigger the same (old and now fixed) bug.  The old bug should have been triggered by any 4-digit ID number object in a backpack in a delivery truck full of such backpacks.

Any chance this is happening in some kind of modded client that hasn't incorporated this fix?

It was a client-side issue.

**Comment by cordy-123** [comment]
You can see Quirky's corn glitch truck video here: https://discord.com/channels/328215300279500800/419395479420534785/1125151776178454598

The video was recorded on June 8, which after your update on the banana backpack truck glitch.
 
Basis for the date is data logs on quirky's life http://lineage.onehouronelife.com/server.php?action=character_page&id=9477604
(http://publicdata.onehouronelife.com/publicLifeLogData/lifeLog_bigserver2.onehouronelife.com/2023_06June_08_Thursday_names.txt)

--------

As you can see on the video, Quirky is using some version of the HETUW mod.

Presumably Quirky wasn't using the yumlife mod. (Yumlife mod is the HETUW mod but updated to incorporate your latest fixes. The original HETUW mod has NOT merged with your updates for a while now.

**Comment by jasonrohrer** [comment]
Oh, yeah, it's the mod then.
