### ISSUE TITLE
Curse system is not be able to handle excess griefing

### ISSUE THREAD

**Issue by Arcurus** [jasonrohrer/OneLife#851]
Hi Jason,

i know that you want with the curse system the players to figure out what kind of game they want to play and with who they like to play together, but the current system seems broken:

1. Griefers could amass cheap accounts and therefore are immune or could even use curses as a weapon

2. Since officially all in game is allowed what is possible to do, griefers think that its fine what they do no matter how much harm they do

I think best solution would be give moderators the ability to bann the main griefers to a custom griefer server.

The mods know quite well who are the main griefers and if some are banned others will grief less.

To make it in game you could call these mods avatars and people could give some food on their graves to rank them but in the end you or some main moderators need to whitelist the avatars who bann the griefers to the Dark World.

To how much griefing is allowed you could make it similar to how space station 13 does it.

There are clear roles who is to allowed to plan an antagonist

I think it could be little less strict like out of role play reasons you should be allowed to become an antagonist but be aware not to disturb the experience of other players too much. All needs some balance.

**Comment by Nika50501** [comment]
How would mods ban people who use alts and vpns exactly? This is some kids game not the fucking nsa

**Comment by Arcurus** [comment]
Still there is a cost to alt accounts. Mods banning would be a more cost / time efficient way to deal with it. Seems to work for 2HOL. The question is if this is wanted, or just live with the excess amount of grieving?

**Comment by Nika50501** [comment]
The current system works better. Its based on trust. If you trust someone and they tell you to curse person X you do it, if they are trustworthy for enough people this has a similar effect to instant banning them. This is basically how content town ended up existing for so long, people just kept monitoring it 24/7.

The problem with what you're suggesting is that most ohol mods don't play ohol very often. They just hang out on discord while doing stuff in real life. Other games have tried this but what ends up happening is that mods usually move away from the game, someone ends up getting access to their account and ends up committing a mass exodus of innocent players/

2OHOL works well because it's a self selected gated community.

**Comment by cordy-123** [comment]
The problem is that some people have 40-50 accounts.

And they share those accounts with their griefer friends.

-------

With that many accounts to cycle thru, it's not that hard for curses to go pass the 90 day curse period.

-------

With that many accounts, Donkey Town is not a punishment. 

Going into DT is just a signal for them to change their login info and switch accounts.


------

A few years ago, you would have to "work off" your curses by spending time in Donkey Town.

However, nowadays, there is no real consequence for your curses if you have 50 accounts.

While I do think the hour rate which you had to work off your 'curse score' (how many hours you had to spend in DT to work off your curses) was a bit too high. At least, it served as an actual consequence.

I would NOT recommend bringing back the old system.

Or at least NOT for people with only (example) 20-30 curses. 

And preferably exclude SIDs (Curse my baby) curses from that. (I do not know if that's feasible code-wise. If 'Curse my baby' curses are categorized as a different type of curse.)
 

-----

Maybe something new?

Or a slightly different take on it?


How about if you reach 50 curses (or whatever number) from 50 DIFFERENT accounts/hashes (so you don't get bombarded with multiple curses by the same account) in the last 90 days (to keep inline with the current 90 day curse period), something happens?

Like you have to spend 5 hours (or more) in Donkey Town or something? (**EVEN** if 90 days have passed, you still would have to "work it off". Which would PREVENT them from just leaving the account for 3 months.)

I don't know. Maybe something else as a deterrent.

Because clearly, the griefers are being SENT to Donkey Towns. But no EXPERIENCED griefer are actually there to be Donkeys.

-----

Maybe adjust the curse radius algorithm? BUT only targeted towards those with HIGHER amount of curses? Preferably noob griefers are NOT punished more for this while ALT account griefers dont (by bypassing it by switching accounts). 

Currently the curse block radius is: https://github.com/jasonrohrer/OneLife/commit/968ddd9f4d979306e1d68bfca994e93801038218

"50 * [number of living people who have you blocked] + [number of total people who have you blocked] ^ 2"

----

I don't know what else could be done. 

Maybe other people have other ideas.

-----

Clearly the current system WORKS against 'griefers' with only 1-2 accounts.

But when there are people with 10, 20, 30, 40, 50 + accounts, it doesn't.

It sounds crazy that someone would buy that many accounts but these people are THAT crazy.

No consequence at all for HUGE offenders with alts.

-----

The problem is how to actually have some consequences for EXPERIENCED griefers with alts who KILL FAMILIES off.... but NOT punish the noob sheep killer more.

**Comment by cordy-123** [comment]
I don't think that Jason/moderators should be banning people.

Then they would have to spend hours just reviewing complaints from both sides (griefers and regular players alike). Then when the decision is made, they'd have to read the appeals, etc. 

Also, Jason had already rejected ideas similar to that several times over the years.

-------

The thing about the curse system (and now additionally the trust system) is that it is community-based.

What the community finds acceptable or not is implemented.

Not just what a chosen few do.

**Comment by jasonrohrer** [comment]
First of all, the price of the accounts in the cheapest countries will be going up next month.

But no, the old system, where you had to "do time" in d-town, wouldn't help, because people would just get alt accounts and throw the d-town accounts away.  For all we know they're doing that anyway.

And mods won't help, b/c alt accounts can still get around the mods' decisions.

There isn't a good reason to limit how long someone that you curse needs to stay away from you.  If you decide that they are bad from your point of view, you probably never want to play near them again.  So I will change that 90 day thing to "forever".

You can still redeem someone, especially if you make a mistake cursing them, and then realize your mistake while they are still alive.  Or if they happen to wander in in a future life (after being born far away from you), and you see that they are actually good, you can redeem them then.  Otherwise, they will never be born near you, ever again.
