### ISSUE TITLE
Sometimes you disconnect when you actually died

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#852]
Sometimes death on the server results in the client displaying a disconnection message.

I thought the server waits some number of seconds after sending the "you died" message before disconnecting you, but I need to look into the details.

**Comment by cordy-123** [comment]
Yes, it still happens a bit, even now. Instead of dying of old age. Occasionally, you get the disconnection message instead.

-------

I opened a github issue on it 3 years ago.

Incase it's helpful,

Here's the link: https://github.com/jasonrohrer/OneLife/issues/726

The fix you did back then: https://github.com/jasonrohrer/OneLife/commit/e60579adbbc1ad1055a2e9677b48c6fd24c58438

**Comment by jasonrohrer** [comment]
Yeah, this is weird... it even happens for me sometimes when testing locally, so I don't think it has anything to do with network outages.

**Comment by jasonrohrer** [comment]
I spent some time looking into this today, but unfortunately, it's still a mystery.

It could be either a client or a server issue.

For example, perhaps the server closes the socket early (instead of waiting 10 seconds) after sending the player their PU (PLAYER UPDATE) message with X X to indicate that they are dead, but I can't find that in the code.

Or on the client side, perhaps, after receiving this message, the client sometimes detects a disconnection accidentally that overrides the detection of death.  But I can't find that in the code either.

We probably actually need some log data here.

If you see this happen (when you actually died but did NOT see a proper death reason, and instead were told that you disconnected).

1.  Quit the game immediately.
2.  Email your stdout.txt file to:  jasonrohre AT fastmail.fm
