### ISSUE TITLE
recent curse length alteration

### ISSUE THREAD

**Issue by squishysquid** [jasonrohrer/OneLife#855]
You should probably remove curse my baby if it's 50 years now. It really is like 4-5 people consistently being assholes, the rest of curses are kind of minor things like noob munched the carrots, or someone stole the flat rocks from the forge again.

perhaps a different implementation, have 2 curse dbs first curse is the normal 3 months, if you curse them a second time it goes into 50 year one, because well if someone's an asshole 3 months latter they're probably going to stay one.

**Comment by cordy-123** [comment]
I agree with squishysquid.

Please either remove curse my baby curses or categorize it as a different type of curse so it will stay 90 days. Or even be 30 days. 
(I always thought 90 days was too harsh for sids curses.) But I can live with it being 90 days.

-----

Reasoning:
- Most curse my baby CURSERS curse when they get like 3+ babies in a row that sids. 
(Sometimes, there are people who curse with just one sids bb.)

Which is fine in the old 90 day curse system. 

That many SIDs babies USUALLY indicates a new/newer player SID-ing. 

The newest player SID-ers do not know that there are only 4 families they can SIDs to. 

Veteran players know not to SIDs too much. Or else they'll be SIDs cursed.

Therefore, the players that get caught with Curse my Baby curses the most is the new players.

----

Reasoning:

I've seen several people tell people off when they see them curse their babies ingame. (NOT OFTEN though, I see people getting scolded maybe 1-3 times a month.)

Explaining the usual reasons why they are anti-Curse my baby curses, blah blah.

Presumably this would make these people go even more into lecture mode since the curses are now 50 IRL years.

If the SIDs curser is newbie/newer person, I don't like the (probable) future meta of lots of people scolding them for using their curse my baby curse.

**Comment by cordy-123** [comment]
> perhaps a different implementation, have 2 curse dbs first curse is the normal 3 months, if you curse them a second time it goes into 50 year one, because well if someone's an asshole 3 months latter they're probably going to stay one.

I think squishysquid idea is better than people getting auto 50 year cursed.

----

Or maybe you can consider RiddlingIce's idea:

_"Wish there was like a **"damn you" that lasted 50 years** and a **"curse you" that still lasted 90 days"**_ 

Source: https://discord.com/channels/328215300279500800/328215300279500800/1126561785504354385

---

Either idea would be better than it being straight to 50 years.

----

Reasoning:

The effect on new players / new players who are griefers or trolls.

Usually, you get 3 different types of new players. (Well, 4 types if you include the type who's an alt.)

1. Eager learner.

2. Just wander around and get bored. Not interested in getting taught.

3. The one that kills livestock, tries to stab people, says "how kill", steals babies, etc. All the low-level griefs.


As much as the low-level griefer is annoying, I don't think they should get the 50 year curse.

-------

**Comment by TwistedHBG** [comment]
IMO "curse my baby" shouldn't be a thing any more, especially with curses lasting 50 days. It's almost always been a noob trap - these days with SID and family respawns there's very rarely any reason to curse your baby, and people who use it freely quickly block out a lot of players from spawning to them which can lead their towns to die out without them realizing, but it would always correct itself slowly over 90 days.

I see suggestions here about having different types of curses or different levels of curses, my 2 cents is that cursing someone should add X time (90 days or whichever number ends up being relevant) to your current curse time against them. That way if someone is really annoying, you curse them once for a 90 day block and then curse them again that same life to extend the block to 180 days.

If you encounter them again in a future life you could have the option of forgiving them if you've changed your mind, leaving the curse up if they're still annoying, or extending the curse by yet another 90 days up to 270 or whatever it ends up being.

Pontentially it would make sense for the number to be scaling (I don't know how much work this would be to implement and if it would be worth it - the first time you curse someone it extends the curse by 90 days, the 2nd time by an extra 120, 3rd time by an extra150, even if you don't have a curse against them currently active, the logic being that if you keep cursing someone you really want them outta the way

**Comment by cordy-123** [comment]
> 
> perhaps a different implementation, have 2 curse dbs first curse is the normal 3 months, if you curse them a second time it goes into 50 year one, because well if someone's an asshole 3 months latter they're probably going to stay one.

----

Would have to consider time in between curses though. 

Since you can currently loophole it to recurse the person the next time you see them, example the next day. 

So 90 days between recursing for the 50 years curse to take into effect?

Cause without the buffer period, you can essentially still recurse the same day to make it 50 years.

**Comment by lorocyproca** [comment]
I generally agree with making the curse length longer than 90 days, however a permanent curse has one negative side effect and it is due to the nature of the curse blocking range formula being (A*50) + (B^2) where A is players online who have you cursed and B is total players who have you cursed. This means that slowly over time accounts will start to approach the point where any random new player, troll, or griefer alt making a single curse against your account will start to PERMANENTLY add on more tiles to the blocking radius than is added from players who are still online and actively playing. This happens at only 8 curses and can eventually reach an absurd radius of 2500 tiles from only 50 total curses. I think that this effect is desirable in dealing with griefers who are likely to obtain that many curses over a short amount of time due to their playstyle, but it is inevitable for any account that plays for years. I think that because of this, maybe the sweet spot for curse duration is something like 6 months to a year instead of 3 months or permanent. This allows curses from non-active players to eventually stop counting against active players while also making it so that the amount of accounts needed for a griefer to effectively cycle through is much more difficult to obtain than what is currently needed on the 3 month curse duration.

**Comment by cordy-123** [comment]
Yes. The curse block radius calculations would negatively impact any long-term player/account.
   
Formula right now: 
50 * [number of living people who have you blocked] + [number of total people who have you blocked] ^ 2

Since the back half of the formula takes into account all curses, the auto-50 year curse would certainly affect more than the EXPERIENCED griefers with alts. 

----

The problem is that you can't just throw the baby (regular players) out with bathwater (serious griefers with multiple alts).

The solution should be more inline with Progressive Tax. Rather than Flat Tax.
(https://en.wikipedia.org/wiki/Progressive_tax)

50 years as a **Flat Rate Curse** is way too HARSH. And **disproportionately punishes the people who are more innocent**. 

A **_Progressive / Tiered Curse System_** is a fairer way to deal with the problem.

----

Plenty of people curse for less serious reasons than a murdered family.

I've personally seen people get cursed for / heard of people getting curse for:

-> picking carrots
-> taking a bowl
-> taking a bucket
-> placing the turkey in the oven while there's still pies to be baked
-> taking the flat rocks from the graveyard / smithy
-> berrymunching
-> building a weird building or a non-meta building
etc

All these actions above certainly don't warrant a 50 year curse.

-----

I certainly think an actual noob griefer player shouldn't get perma-cursed to DT forever for sheep killing.

----

**Comment by cordy-123** [comment]
I've posted this github issue on the main OHOL discord and asked people to add their comments or suggestions. They clearly didn't. :D
   
So I thought I'd post their discord posts here in github.

----

Posts Regarding Curse My Baby Having the Same 50 Year Curse Period:

-----

Rukhran: https://discord.com/channels/328215300279500800/328215300279500800/1126568150297743482
can we at least remove "curse my baby" or shorten that particular phrase to 1 hour or something before then at least?

RiddlingIce: https://discord.com/channels/328215300279500800/328215300279500800/1126568262700908644
Oh fuck
Yeah i'm never /dying from now on lol

-----

𝙔𝙞𝙠𝙚𝙨: https://discord.com/channels/328215300279500800/328215300279500800/1126571110696239276
I get cursed a lot since I love a lil /die

----


Tarr: https://discord.com/channels/328215300279500800/328215300279500800/1126619726479638669
I’m not sure, though probably need something for cases like die babies


----


mingo888: https://discord.com/channels/328215300279500800/328215300279500800/1126644913187078304
i like the permanent curses tbh due to the alt problem, but yeah we need to make sure noobs cursing my baby arent going to screw this up


-----

RiddlingIce: (refering to sids and curse my baby) https://discord.com/channels/328215300279500800/328215300279500800/1126579285633814568
Yeah players who are aware of the length of curses now aren't going to use it as much but unaware players are gonna use it as much as they did last time 
Which is a lot

**Comment by cordy-123** [comment]
I've posted this github issue on the main OHOL discord and asked people to add their comments or suggestions. They clearly didn't. :D 
   
So I thought I'd post their discord posts here in github.

----

Posts Regarding Other Issues: (Excluding The SIDS Curses Issue)

-----
 
 
 
Tarr: https://discord.com/channels/328215300279500800/328215300279500800/1126633302422462524
Maybe it should just be a tiered system. You curse one guy once for 30, a second time 90, then permanently after third

---

SickL: https://discord.com/channels/328215300279500800/328215300279500800/1126619408228433981
Now who the fuck suggested to bump the curse ban to 50 years
The game will be unplayable

Tarr: 
I’m not sure, though probably need something for cases like die babies

SickL:
Griefers can literally curse everyone out
A curse should never be a permanent thing

Tarr: 
Yeah it’s problematic with the whole people with 50 alts being able to curse out others and use them as wards
Don’t think this is being handled properly imo

GenericPyramid: 
Not at all
The amount of misunderstanding curses that happen
Or just silly kids see a bloody knife and curse people
Even if they slayed a griefer :sob:
Now with a 50 irl year penalty wtf :skull::skull::skull:

----

Tarr: https://discord.com/channels/328215300279500800/328215300279500800/1126633080430538793
Yeah I really don’t know it’s problematic both ways. It’s good to have long curses because once you’ve nailed one troll account it’s a one and done. Bad thing is obviously people cursing or getting baited to curse is basically permanent too

Brohop: 
yep ive had some guy tryna frame me for his deeds once xD
but the nice thing is generally there is other phex players around that will back ya up

====

_----> comment from me: the problem is that normal vanilla players don't have other phex players to back them up. (PHEX is the chat feature of the HETUW mod.)_

---

ru: https://discord.com/channels/328215300279500800/328215300279500800/1126634985340809370
on second thought, infinite curses are problematic due to the curse block range formula including total active curses and not just online curses. this is the only argument against lifetime curses imo but it's a good one, so I change my mind

ru: https://discord.com/channels/328215300279500800/328215300279500800/1126643656481308754
yeah but the problem is that the curse range formula is (Online Curses * 50) + (Total Curses ^2)  so when you get to 20 total curses your range is at a minimum 450 but when you get to 50 it's 2550. the longer your account exists the more curses it will eventually rack up from random new players or griefers/trolls


---

**Comment by jasonrohrer** [comment]
I think the radius formula may need to be changed somewhat.

Cursing is saying, "I don't want to play with you anymore."  As in, "I don't want you to ever be my baby again, nor do I want to be your baby."

It's a personal choice, but the radius formula turns it into a collective thing as well (basically, to ensure that a widely-cursed player eventually goes to d-town).

But that kinda flies in the face of the stated point of curses:  to let each person decide what behavior is off-limits.

But if one player doesn't like SIDs babies, and another player doesn't like picking carrots.... it seems like it will add up.

Maybe the "total count from all players" part should be removed?

B/c if you annoy 50 people, but none of them are currently online, why shouldn't you be able to play now?  We can't extrapolate from their dislike for you to everyone's dislike for you.

**Comment by jasonrohrer** [comment]
There's also a problem with "curse my baby":  there's no way for the person to redeem themselves.

If you curse someone for picking carrots, they can still plead their case with you, and maybe you would decide to redeem them.

Though maybe this doesn't matter?

Don't forget that curses are bi-directional....  you won't be born to them either, which means that if you curse lots of SIDs babies, it will come back to haunt you, maybe.

**Comment by jasonrohrer** [comment]
But...  at least other spurious curses can be discussed, explained, and rescinded.  Curse my baby cannot be.

**Comment by lorocyproca** [comment]
The total count from all players is extremely effective against griefer accounts and helps prevent them slipping back through the cracks once the players they are griefing have gone offline. Like many things it seems it's difficult to find a solution that doesn't also make things harder on regular players, but I honestly think that the curse duration being something like 9 months to a year would be the best of both worlds. It will shut down griefer accounts long enough to make it un-economic to rotate through accounts the way one of the primary griefers currently does, but it will also allow long-time players a chance to have old, one-time curses fall off and not effect their account anymore.

**Comment by lorocyproca** [comment]
"B/c if you annoy 50 people, but none of them are currently online, why shouldn't you be able to play now? We can't extrapolate from their dislike for you to everyone's dislike for you."

The curse radius still requires and augments the one person who is online and does have that person cursed. So in effect it still needs someone there who dislikes that person, but their radius is just bolstered by the fact that many people (online or not) also agree in disliking that person.

**Comment by jasonrohrer** [comment]
I think these two fixes address the issue, for now.  Let's give these changes a try this week, and re-open if we're still having trouble.

Remember, even if someone curses you, and you can't be born near them for 50 years, that only affects you if the cursing person is currently online.

The idea that non-griefing players benefit from being about to "wait it out" for 3 months (instead of 50 years) seems suspect to me.

Actually, before I close this issue, I will examine the current curse DB and dump some stats here.

**Comment by lorocyproca** [comment]
I suggest keeping an eye on Donkey Town births after this change. I suspect that we will see far fewer instances of griefers being DT'd now.

**Comment by jasonrohrer** [comment]
Okay, here are the counts that are in the current curseCount db (before any changes from this week):

```
      2 24
      1 21
      2 17
      1 13
      2 12
      1 11
      3 10
      4 9
      3 8
      7 7
      2 6
      7 5
     22 4
     33 3
     36 2
    155 1
     46 0
```

In other words, how many people had that many curses active?  2 people have 24, 1 person has 17, etc.

And the 46 people who have 0 curses are in there because their curses have expired (after 90 days)

I'm pretty sure those 0 people get culled whenever the server restarts, so 45 people had their last curse expire this past week.

329 people had curses against them (including the 46 people who had their last one expire this week).

Also, there were 9746 unique accounts that played the game in the past 90 days.  This means that curses have impacted 3% of the player base, at all, sometime in the past 90 days.

So we're imagining a totally innocent player building up 50 curses over a lifetime of play.  But 97% of the playerbase got 0 curses in the past 90 days... let's round that up to 1 curse each in 90 days.  So then to get 50 curses at that rate, they would need to play for... 12 years.

We can set an appropriate "max curse count" that we'd like to see for this 97% of players.  Over the 50 years before their curses expire, they could potentially amass 202 curses, which seems like a lot, if they earn 1 every 90 days.

So lets say that we don't want our 97% of players to amass more than 20 curses, ever.

That means we should set the expiration time at 5 years (instead of 50 years).

In a 5-year span, earning less than 1 curse every 90 days, 97% players will earn ~20 curses before their curses start expiring.

I will also put the second half of the formula, for total number of curses, back to an exponent of 2 instead of 1.5

Because look, the worst player currently only has 24 curses.  That only gives them a blocking radius boost of 117, which isn't enough to send them to d-town, probably, where an exponent of 2 would give them a blocking radius boost of 576.

Of course, if curses take 5 years to expire, we might expect the worst players to accumulate even more... but not *that* many more.  In the short term, we can expect the worst players to accumulate 24 in 90 days.
