### ISSUE TITLE
Provide a way to forgive everyone

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#858]
Many players have cursed people in the past few months that they expected would be wiped in the near future. With the recent changes, though, these curses will actually end up sticking around for close to five years. To actually forgive these cursed players would require bumping into them in-game, which is very unlikely considering how cursing someone prevents them from being born near you. According to your comments in #855, it also prevents you from being born near them, which would exacerbate this issue (though I am not confident curses are actually bi-directional as you mentioned).

A simple phrase like "I forgive all" or "I forgive everyone" would alleviate this issue and allow players to start fresh. If implemented alongside #857, it should also properly log this event.

**Comment by cordy-123** [comment]
Currently, curses are uni-directional.

As it should be.

Or else, no one will ever curse griefers. 

Coz they'll just be shooting themselves in the foot.

Let's say you curse one of the griefers with 50 accounts, by the time you get 20 curses on 20 of their accounts, you'd have 20 curses yourself if curses were bi-directional.

And that just one player with multi-accounts. Trust me, there's plenty of individual griefer players with more than 5 accounts.

This does not include the low-level people you curse: occasional racist, troll, noob sheep killer, truck yeeter, bbnapper, etc.

**Comment by jasonrohrer** [comment]
The COUNT isn't bi-directional, of course.

But the blocking effect is.

I mean, if someone is a griefer, you don't want to get born as THEIR baby, do you?

I will look into the details of the bi-directional code now, and report back in a second.

Ah, yeah, so here's the details:

Curses are only *partly* bi-directional.  There's nothing stopping you from being born NEAR someone that you have cursed.  But you can't be born AS their baby.

Also, this filtering only happens if there are multiple potential mothers for you (based on birth cooldowns and other factors) AND you don't have ALL of these potential mothers cursed.  If you have them all cursed, you still get born to one of them.  Except in the case where there is only ONE available mother, and you have her cursed.  In that case, you are spawned as an Eve.
