### ISSUE TITLE
Use previously logged public data to fix the curse counts.

### ISSUE THREAD

**Issue by lorocyproca** [jasonrohrer/OneLife#861]
The mistake that caused curse count to be reset on server reset may have been fixed but the counter needs to be corrected and restored. The total curse count part of the curse range formula is by far the most potent contributor to sending these accounts to donkey town and it desperately needs to be restored to pre-wipe numbers. As of now, these players who have built up dozens of accounts due to slowly being cursed out over months of griefing have all been given a get-out-of-jail free card for every single account and are going on an unchecked terror spree. What's worse is that most players do not understand that they should re-curse the player that they already have cursed in order to increase that accounts curse total. I have no doubt that you have the required information as it is publicly logged, but can provide my own logs/counts if you need. This very much needs to be done for at least the accounts that have gained >20 curses in the past few months, as they are all alts of the small handful of players who are 100% committed to ruining this game.

**Comment by jasonrohrer** [comment]
Well, the counts were getting reset on EVERY server restart for the past few years.  It wasn't a new bug.

However, looking at the data, you're right in that there are people with dozens or even hundreds of curses who currently have a recorded curse count of 0.

We don't need to go through the logs to fix this, though, because the curses ARE recorded.  The problem is that the curses and the recorded count are in separate databases, and the count database was being cleared every restart.  However, on server startup, we might as well just walk through the curse database and re-create the count on each startup.  It takes like 1/10 of a second to walk through the whole curse database, currently.

I will change the server code to do this.
