### ISSUE TITLE
Please consider adding Galician names to the name list

### ISSUE THREAD

**Issue by ghost** [jasonrohrer/OneLife#867]
Hello! Could you please consider adding some more Galician names to the name list? There are some good ones already, on the list, but these are either common or in the case of Ousenda pretty. I don't know if gender matters but noted in case.

x is the sh sound in Galician by the way

Here are some:
- Uxio (masculine, Eugene)
- Uxia (feminine, Eugenia)
- Sarela (feminine)
- Anxo (angel, masculine)
- Xoan (masculine)
- Xose (masculine)
- Breogan (masculine, mythical founder of galicia)
- Nuno (masculine)
- Loaira (feminine)
- Xulio (masculine)
- Piedade (feminine)
- Xusto (masculine)
- Zoilo (masculine)
- Inocencia (feminine)
- Eiroa (feminine)
- Ousenda (feminine)

Love the game thank you for the consideration <3 Grazas por examinar esta suxestión <3

**Comment by jasonrohrer** [comment]
Nuno is on the list already.

And yes, there are male and female names.  So you can't name your boy baby Penelope.

The problem with doing this is that there are millions of names from different cultures from around the world.  I can't add them all, so I add none of them.

The name data used in the game is quite comprehensive, including 100,000 names that were used by at least 5 babies in a given year since 1880 in the United States.  It's a nation of immigrants, so it includes popular names from many cultures.

https://www.ssa.gov/oact/babynames/limits.html

One thing that is outdated is that the data used in the game stopped at 2016.  I will update it with data up to 2022

**Comment by jasonrohrer** [comment]
The original name lists went from 1880 up to 2018 (not 2016 as stated previously).

Looking at the updated lists for up to 2022, there are 2000+ new male and 2000+ new female names.  Also, some of the previous names have been removed.  Like Bimbo was originally listed as a name in 1954, but it's gone from the new list.  I could add just the new names, and keep the old ones.

BUT, I've also realized that the specific list of names is part of the character of the game.  People have literally named millions and millions of babies using this list.

So I've decided to keep the list, and not add anything to it.
