### ISSUE TITLE
Radios work from Donkey Town

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#871]
Players in Donkey Town can (and have) built a radio to talk to those outside of donkey town. They can use this to jam the communication frequencies with noise and spam slurs. This should obviously be prevented.

**Comment by QuirkySmirkyIan** [comment]
This issue is not meaningful. Radios are **extremely underused** to begin with and already with the few radios that exist people spam nonsense all the time. If someone doesn't like radios just don't use them.

**Comment by selb** [comment]
The low-skill route to DT is to spam the N word. There's a real and obnoxious difference between the usual radio spam and giving the worst of DT an audience for their slurs.

**Comment by cordy-123** [comment]
Considering all the worst griefers have said the dreaded racist word, are rude, and/or antagonistic, it would be a good idea if non-DT people CAN'T hear from DT people. 

Non-DT players shouldn't have to be subjected to DT players. 

That's why there's DT. 

Because they got hundreds of curses and regular players don't want them near them.

That should include not wanting to hear their incessant abusive talk or polarizing thoughts on the radio.

Especially as almost all radios in regular spawns are in the nursery. 

Therefore, a lot of people are subjected to it.

And as they are 200 million tiles away, it's not like we can go find and kill / curse them. 

So people are just subjected to their shit-talking forever or unless regular players just stop using the radio forever.

(If you're asking if these people would spend hours in DT, yes they would. These are the same people who (example) spent TEN hours trying to protect a way stone that other people were trying to remove in the nursery. (They used a lot of alts so they couldn't be cursed out completely.) I believe the standoff ended with the town dead from what I heard. I don't know, it didn't play that day. But these accounts came from more than 10 people. So, it's probably accurate.)

**Comment by ShadyCantCode** [comment]
Nobody is saying racial slurs in dt, you're confusing griefers who build radios to communicate outside of dt with racist assholes.

**Comment by ShadyCantCode** [comment]
None of this stuff is happening, this first radio in dt was built yesterday. Quit lying to get people to side with you.

**Comment by cordy-123** [comment]
> Nobody is saying racial slurs in dt, you're confusing griefers who build radios to communicate outside of dt with racist assholes.

Well, considering that you have been banned from the OHOL discord for using slurs and you have also been muted from PHEX (ingame mod chat) for saying the n-word MULTIPLE times, I highly doubt that you don't say slurs / racist stuff.

**Comment by ShadyCantCode** [comment]
> > Nobody is saying racial slurs in dt, you're confusing griefers who build radios to communicate outside of dt with racist assholes.
> 
> Well, considering that you have been banned from discord for using slurs and you have also been muted from PHEX (ingame mod chat) for saying the n-word MULTIPLE times, I highly doubt that.

You think that me Infront of a team of 5 building in dt was spamming the n word. Just quit the bs 
(DO YOU HAVE PROOF OF PEOPLE SPAMMING RACIST STUFF OVER RADIO????????) + I'm black

**Comment by ShadyCantCode** [comment]
> 

Also I wasn't muted on phex, that was Rudy, the user who called me the N word, you're getting things mixed up.

**Comment by cordy-123** [comment]
> None of this stuff is happening, this first radio in dt was built yesterday. Quit lying to get people to side with you.

Oh you misunderstood.

As you can see in the original post.... 

> Players in Donkey Town can (and have) built a radio to talk to those outside of donkey town. They can use this to jam the communication frequencies with noise and spam slurs. This should obviously be prevented.

The OP said "CAN"

This is simply a preventive measure.

As after Mr. Rohrer has finished fixing all the bugs and made one final endgame update (from what I heard Tarr say), Mr. Rohrer will NO LONGER be updating the game.

This github issue was made coz inevitably someone will do that. 

And if Mr. Rohrer is no longer updating the game, then we'd be stuck with DT radio people.

**Comment by cordy-123** [comment]
> > 
> 
> Also I wasn't muted on phex, that was Rudy, the user who called me the N word, you're getting things mixed up.

Considering that I heard that you got muted on phex for saying slurs a few months ago FROM the ONLY current phex moderator, I'd say I'm correct.

**Comment by ShadyCantCode** [comment]
You arn't correct, rudy said the n word, he got muted

**Comment by ShadyCantCode** [comment]
And I'd say mingo is stereotyping people in dt claiming us all to be horrible racist people.

**Comment by ShadyCantCode** [comment]
> Players in Donkey Town can (and have) built a radio to talk to those outside of donkey town. They can use this to jam the communication frequencies with noise and spam slurs. This should obviously be prevented.

And to accuse all people in dt of being racist is wrong, anybody who is willing to go through the entire tech tree just to spam racial slurs is a bad person, show evidence of people in dt saying racial slurs and I'll agree.

**Comment by ShadyCantCode** [comment]
> Players in Donkey Town can (and have) built a radio to talk to those outside of donkey town. They can use this to jam the communication frequencies with noise and spam slurs. This should obviously be prevented.

Jason might as well ban radios all together because it allows people to say bad words without getting in trouble. This can be in a remote area such as an abandoned town.

**Comment by selb** [comment]
Nobody is saying that all DT players are horrible racists etc blah blah blah. To be clear, my position is that DT players deserve to have a functioning game apart from others while they rehabilitate, and I think this is fairly compatible to Jason's position. But there absolutely are people who install games just to spam disgusting speech that is considered unacceptable by their wider society. One of the design goals of this game is that babies are unable to move or make decisions themselves, and having radios spewing garbage in the nursery while they wait to grow up is off-putting, to put it politely.

All that said, radios really are a weird case where you can't curse people over them, and their actual purpose has been entirely usurped by Phex and other metagaming options. I am not opposed at all to removing the translation purposes (which do not make sense at all) of radios and overall making them less desirable to have.

**Comment by ShadyCantCode** [comment]
A five-year rehabilitation isn't what I'd call a rehabilitation. More like a five-year imprisonment

**Comment by selb** [comment]
Well, the vast majority of players have no trouble staying out of DT in the first place. If you don't have the basic social skills to interact with others in a palatable way, perhaps you could consider learning from your experiences instead of whining that life is unfair. There is no other game that gives you more freedom to behave as you wish; you could make the choice to feel grateful rather than entitled.

**Comment by ShadyCantCode** [comment]
You'd be thinking a lot different if you were in donkey town.

**Comment by jasonrohrer** [comment]
It's an oversight that anything can pass from DT to the regular world.

It is really supposed to be a separate world (just like tutorial world).

It's housed on the same server for efficiency, simplicity, and convenience.

I will fix this.

**Comment by jasonrohrer** [comment]
As for it being "five years".... that's a distortion of what is happening here.

You have one player saying, "I don't ever want to play with you anymore."  That lasts for 5 years.

This is "soft" compared to pretty much any other service that supports blocks (twitter, discord, etc.)  In those services, blocking is forever, and it never expires.


You only "go to DT" if lots of players who are currently playing have you blocked.  If no one who is currently playing has you blocked, you don't go to DT.  Full stop.


Essentially, some people have said, "I don't want to play with you anymore."  In order to honor that, we have to find a spot for you to be born where you're not near these players.

If we run out of places for you to be born, we have two choices:

1.  Violate the wishes of a player who says they don't want to play with you anymore.
2.  Send you somewhere far away from everyone (DT).

**Comment by ShadyCantCode** [comment]
Yes but for 5 years
