### ISSUE TITLE
Drop oldest curse every 90 days

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/OneLife#872]
From an email discussion with Frank M.

A workaround could be to do a batch check on a set schedule, say every three months.  For each player drop the oldest curse if they have a curse that is older than three months old.  No need to add a new field in the database or add a task that is constantly running or anything just periodically running maintenance task or corn job. Yeah so often someone with only one curse will take nearly six months to have it drop instead of 3 but whatever. 

On Mon, Jul 10, 2023 at 3:52 PM Jason Rohrer wrote:
> This is a great idea!
> 
> Unfortunately, making this change wouldn't be simple, because of the way the curse database currently works.
> 
> It records the two email addresses (sender of curse and receiver of curse) along with the timestamp of the curse (when it was issued).
> 
> So there's no tracking per-player of when the last time a curse was removed.  We can just see when the curses were added.
> 
> Jason
> 
> On Saturday, July 8, 2023 at 9:54 PM, Frank M wrote:
> > You've likely decided and would be resistant to unsolicited suggestions 
> > but here's mine anyhow. Have a player's oldest curse drop off every 90 
> > or even 180 days.  This way an accidental curse won't be forever, but 
> > players who are routinely cursed are likely to always be affected.

**Comment by cordy-123** [comment]
Presumably this means that their Total Curse Score gets lowered by 1.

Not that their oldest curse actually gets removed.

???

**Comment by Tarr-OHOL** [comment]
Unpopular opinion: Probably should have cleared everyone's curses when the long curse update came out since curse my baby curses would have still been in effect. I guess you could show a little mercy to the people who are now basically perma donkeyed and still do this and give them a warning of what's going to happen to their account if they continue down the same path of essentially being an anti social player ending up locked back to donkey town again. 

Even if we removed a curse every three months aren't these accounts basically going to be perma donkey anyways? I guess if you only piss off people during a certain time you're much less likely to be blocked other times during the day, 

Gonna be Frank (kek) I have no idea what the solution is. Currently there's no real way for players to be rehabilitated out of donkey town. Obviously the people who are currently stuck there definitely deserve the current punishment they're getting with them building their little towns and then getting griefed by their fellow donkeys. 

I think it would be sort of hilarious to give the donkeys some annoying recipe  as either a way to reduce curses or reset them. Think the apocalypse but even longer like a month or something. Donkeys could grief each other to their own delight trying to free themselves or stopping others from freeing an account. 

Obviously we want to keep the worst offenders locked up with each other but I feel like the current system has zero means to escape unless people start mass forgiving and that's an awful idea.

**Comment by lorocyproca** [comment]
Clearing everyone's curses 

> Unpopular opinion: Probably should have cleared everyone's curses when the long curse update came out since curse my baby curses would have still been in effect. I guess you could show a little mercy to the people who are now basically perma donkeyed and still do this and give them a warning of what's going to happen to their account if they continue down the same path of essentially being an anti social player ending up locked back to donkey town again.
> 
> Even if we removed a curse every three months aren't these accounts basically going to be perma donkey anyways? I guess if you only piss off people during a certain time you're much less likely to be blocked other times during the day,
> 
> Gonna be Frank (kek) I have no idea what the solution is. Currently there's no real way for players to be rehabilitated out of donkey town. Obviously the people who are currently stuck there definitely deserve the current punishment they're getting with them building their little towns and then getting griefed by their fellow donkeys.
> 
> I think it would be sort of hilarious to give the donkeys some annoying recipe as either a way to reduce curses or reset them. Think the apocalypse but even longer like a month or something. Donkeys could grief each other to their own delight trying to free themselves or stopping others from freeing an account.
> 
> Obviously we want to keep the worst offenders locked up with each other but I feel like the current system has zero means to escape unless people start mass forgiving and that's an awful idea.

Clearing everyone's curses already happened as a result of a mistake and the consequences were very very bad. Every Reformed/Bluehawk/Ian/Shady alt was completely free from Donkey Town and they made sure we knew about it. Worst griefing I've ever seen in a one week period. I think this suggestion is fine. It allows old curses to slowly fall off as long as the player is only logging 1 every 90 days, which according to Jason is the average.

**Comment by TheMingo888** [comment]
I agree that there should be some counter to curses lasting five years, permanently impacting the target's curse score for that entire period. Even good players will slowly acquire curses over time, especially if they are actively involved in exiling and killing the griefers that show up from time to time. Especially since we still have three month's worth of "Curse my baby" curses hanging around in the database for another 5 years.

However, I don't like this idea, since it means the length of time a personal curse lasts will be unpredictable depending on how many people have cursed someone before you. When I curse someone, I want a guarantee that they will stay cursed for a fixed amount of time. Under this system, I wouldn't know whether my curse will last 90 days or 5 years.

---

I have an alternative idea: leave personal curses alone until they expire or are forgiven, but instead change the way the curse score is calculated. As of your fix to #861, the server now sums up the total number of curses for each player on startup to produce each player's curse score. Since the square of this score contributes to the curse blocking radius, it is quite significant and is the reason many players now find themselves in DT.

I considered proposing that curse score is only calculated from "recent" (e.g. past 90 days) curses. In other words, if a player has 20 recent curses and 30 older curses, their curse score would be 20 and not 50. However, this would just return us to the situation we had before where players with many alt accounts can just rotate between them. You shouldn't be able to just shrug off 30 curses by waiting a few months. I think an ideal scenario would be to calculate curse score only from curses that were issued by players who are still active (those who have played at least one "recent" life), but this might be too difficult to implement.

Instead, I think the best way to handle this would be to _weight_ curses. The most recent curses should have the most weight, and curses that are old and close to expiring should have the least weight. For example, a curse that was issued a moment ago would have a weight of 1, a curse that is 2.5 years old would have a weight of 0.5, and a curse that is about to expire would have a weight of nearly 0. These weights can be calculated by taking the difference between the current time and the curse time, and then dividing by 5 years (though, a shorter interval can be used too). To calculate a player's curse score, just sum up the weight of every curse and then round to the nearest whole number.

This system of weighting curses has several great benefits:
1. Prolific griefers won't just magically get out of DT by waiting a few months. Those with tens or hundreds of curses (see 901f8a2980ac03bda7a303f33e5b39fdafe0275c in this [curse log](http://publicdata.onehouronelife.com/publicLifeLogData/curseLog_bigserver2.onehouronelife.com/2023_07July_13_Thursday.txt)) will remain there, since the curse weights decay slowly.
2. Ordinary players, who acquire a curse maybe every 90 days, won't end up with a high curse score 4 years later, saving them from visiting Donkey Town.
3. The lengths of personal curses are respected. Once you curse someone, you can guarantee your curse will stick with them for the whole five years (unless, of course, you choose to forgive them or everyone).
4. If you encounter someone you already have cursed continuing to be a nuisance, you can choose to re-curse them to refresh the weight of your curse back to its full effect. Thus, unless those who cause trouble change their ways, they will continue to maintain a high curse score.

**Comment by squishysquid** [comment]
how about instead of oldest, least total curses on the person. That should roughly forgive the people who have a few too many low impact curse events(eg /died too much or picked the carrots), and keep the guys that sweaty nolife destroy towns at 4am etc in donkey town. Those guys probably are the oldest curses for a lot of people.

personally I'd want to opt out though, I'm not that forgiving. Kind of like the big flashing this guy's an asshole warning. I could live with a decaying radius though.

that 5 year change is the first time I've ever felt like "wow I don't need to write down curse names anymore to remember who that is in 3 months" because I'll just never see that account again anyway and that's a huge burden lifted.

if you want to lessen the suck to something they'd enjoy, flip donkey town lives to no possee old style pvp. the ones that show up on the discord seem obsessed with that being super fun. maybe flip off external curse name visibility while you're there so you only have your own. Persistent id wrecks it if you're explicitly playing a pvp version of the game, apparently 2-3 guys have been camping out killing all babies not one of their accounts, from the complaints I've been reading.

**Comment by jasonrohrer** [comment]
There are currently 272 accounts that have more than 10 total curses.

And 10 total curses makes the offline component of your curse radius +100, which isn't very big.

I feel like I've spent way too much time worrying about the Donkeytown experience.

It's already much more interesting than it used to be.  They can have a town out there, and do whatever out there.

In terms of mechanisms for old curses to expire.... let's find ONE trusted player who's actually affected by this unfairly before I spend any time modifying the curse system.


Even dropping one curse every 90 days is non-trivial, because sometimes the server runs for 90+ days straight with no restarts.  I'd have to build a mechanism for timing the last purge *while the server is running* (so that it happens every 90 days) and also keeping track of that timing across restarts.

This can't just happen with a separate cron job, because then the database file would be changed out from underneath the running server.

So, I could spend a bunch of hours doing this... but I'd rather spend those hours fixing something else.
