### ISSUE TITLE
Flush buffer for public data files before publishing

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#880]
This probably affects all of the public data files, but is only really noticeable on the lifeLog names files since they are small. For example, take a look at the [partial Thursday log](http://publicdata.onehouronelife.com/publicLifeLogData/lifeLog_bigserver2.onehouronelife.com/2023_07July_20_Thursday_names.txt) that was made available a few hours ago (or see [this copy](https://pastebin.com/raw/uxafScZ6) made at the time of this issue). It gets to ID 6479043, and then cuts off the next ID. Meanwhile, the [corresponding non-names lifeLog](http://publicdata.onehouronelife.com/publicLifeLogData/lifeLog_bigserver2.onehouronelife.com/2023_07July_20_Thursday.txt) goes all the way to 6479195.

On this topic, is there a reason the public data files are published so infrequently? Having access to the map change data and life logs is hugely powerful and allows us to create applications that can rebuild the state of the server (e.g. [Wondible's map](http://onemap.wondible.com)). However, the age of the data means that these tools are always going to be lagging behind the server by many hours (expect for the period immediately after the server provides the new files). Obviously real-time data would be the best, but even just increasing the frequency from once to twice per day would be a significant improvement.

**Comment by jasonrohrer** [comment]
There's a cron job that does this.  It copies the files to the public server and sanitizes them to remove email addresses.

I don't think it's a matter of flushing... the cron job runs when it runs, and it sounds like it's pulling the file while it's still being actively written by the server.  Which is going to happen, because they are independent processes

There may be a bug here, in that it should only pull yesterday's files to avoid this.

But doing it only with day-old files to fix this issue would further increase the latency of these logs.

**Comment by selb** [comment]
`lifeLog.cpp` `logName()` is missing the `fflush()` that the other log functions do. It looks like `logName()` is called as soon as a baby is named, but I can confirm that it lags far behind even player death.

**Comment by jasonrohrer** [comment]
Nice find!
