### ISSUE TITLE
Make Photos Hangable on Walls

### ISSUE THREAD

**Issue by skps2010** [jasonrohrer/OneLife#888]
I don't know if it's a right place to write suggestion, but I saw someone brought my suggestion here, so here I go.  

https://www.reddit.com/r/onehouronelife/comments/156npu0/make_photos_hangable_on_walls/
When you take a photo, not only your photo is uploaded to the website, you also get a photo "item", which can be displayed on a wall for everyone in the game to see.

I think this idea can make photos useful, because not everyone will go to the website to see them.

**Comment by jasonrohrer** [comment]
Interesting idea!

Not sure about making them hangable on walls, because they would be too tiny to see.

But maybe you could pick up a photo and "read" it, and then have some kind of full-sized thing pop into view on the client.

**Comment by skps2010** [comment]
Maybe a photo can occupy 2x2 or 3x3 blocks.

How 2x2 works is that you need 2 walls to put a photo, and the photo will occupy those 2 walls and visually 2 blocks above those 2 walls. "visually" means you can still walk there, put something there, just like trees that are high enough to block the view.

**Comment by jasonrohrer** [comment]
That feels like billboards, not photos...

You have this little slip of photo paper that you can hold in your hand, and then after you hang it, it covers many walls?

I think they will have to be a bit more abstract than that, in terms of how they work.

Also, bear in mind that in order to look at a photo in the game, you will have to develop/fix it, which requires a whole bunch of additional chemistry steps, and care to avoid exposing the unfixed negative to light.

Well, and even after you fix it once, you have a fixed negative (which you can view as a negative), and then you have to make a contact-print with another piece of photo paper, and develop/fix that, to get a fixed positive.

It's quite an involved process!

But it's very cool...

Anyway, the result will be a photograph you can hold in your hand, or store in a box, or whatever... and whenever anyone picks it up, they will "see" the image pop up in their client.

So, for example, you can visit an abandoned village, and rifle through their storage boxes, and find photographs of the people who used to live there.

That's a perfect fit for OHOL.
