### ISSUE TITLE
Legacy Opt-Out

### ISSUE THREAD

**Issue by selb** [jasonrohrer/OneLife#892]
It would be neat if there were a way to opt out of the legacy (respawn to same family) functionality. I really enjoy not knowing where or who I will be when I am born and having to assess the situation and figure out how to be most useful. I currently run through the tutorial between lives to make sure I get a random spawn.

**Comment by jasonrohrer** [comment]
Interesting...

I'm assuming you care about genetic score, etc.

Otherwise, you can just die at age 58 or something, which will prevent you from respawning in the same family.  And dying at 58 won't impact your genetic score too much.

**Comment by jasonrohrer** [comment]
But I guess there could also be a slash command that you could issue near the end of your life to control this....  actually, it might be more interesting if it wasn't a slash command, but a magic phrase you could say as your last words...  like... maybe:

GOODBYE FOREVER

Does that feel like a good solution?

**Comment by selb** [comment]
I definitely think the last words idea is the coolest! Having to state it publicly might open up some interesting interactions, like the kids begging grandma to stay in the family, or troll grandma saying "jk" at 59.9.

On the slash command side, being able to `/die` after 57 or so could be a neat alternative. Would also help with the common situation of getting all undressed and awkwardly standing in the graveyard waiting for time to count down.

I'm not _that_ concerned about gene score, so dying early is probably what I would do if the tutorial workaround didn't exist. As it is, I'm used to running through the tutorial to test Mod Things, so at least to me that feels more straightforward than a planned suicide by boar or starvation. I'm usually panicking at 59 to undress and find a tree to die behind, but that could certainly be chalked up to poor planning on my part. :)

**Comment by jasonrohrer** [comment]
Well, I don't want /die later in life, b/c how does that work?  Maybe if you were holding a knife or something, you could stab yourself...

But as a baby, /die makes sense, because SIDS exists.

**Comment by TheMingo888** [comment]
I support this idea. I often want to visit the other towns instead of being born over and over again to the same family. I don't think using special last words is the best idea though, since last words show up on the website and can make for really interesting stories. This would lead to many players having the same last words as they take advantage of this mechanic, which is boring.

But certainly, a special phrase you can say at some point during your life, maybe anytime or maybe just when you are above a certain age, would be a good feature. It just shouldn't have to be the last thing you say.
