### ISSUE TITLE
Accessibility: Add a small, circular, clickable region for small / tiny objects, so the players have an easier time clicking on them.

### ISSUE THREAD

**Issue by tommai78101** [jasonrohrer/OneLife#895]
I would like to suggest for an accessibility feature in the game, where small or tiny objects have a larger click radius / region than the objects themselves, but not big enough to cover the entire tile. I'm thinking of a click region the size of a clay bowl, which I think should be enough.

This accessibility feature will allow players with a difficult time clicking on small objects to click and interact with the objects a bit easier, without them having to be more precise in their mouse clicking aims. 

Example objects that have tiny click regions:

- Steel Valve
- Fuel Injection Nozzle
- Fuel Nozzle Body
- Gooseberry
- Gooseberry Seed
- Pepper Seed
- Tomato Seed
- Thread
- Leaf

And there are many more small objects in the game that may have this issue. I can't list them all, but the ones I have listed above are the common ones I have seen.

Thank you for considering this.

**Comment by jasonrohrer** [comment]
I understand the plight of those with accessibility issues.

However, the "picky" aspect of the game is an intentional aesthetic choice.  If you drop a seed on the ground in real life and try to pick it up, it's a very fiddly experience.  I want tiny objects in the game to be difficult to pick up, and require very careful, tedious clicking.  Because it feels like working with tiny, delicate objects in real life.

I don't want to completely dismiss those who struggle with a real disability, but I'm assuming that those people have other tools at their disposal to help, like a variable speed mouse (where they can hold down a button or foot pedal to cause the mouse to switch to slow, high-precision mode).

**Comment by jasonrohrer** [comment]
Actually, I just noticed something that might help.

Right clicking on the tile around an item "swaps what you are holding with the item"  If your hands are empty, you pick up the item.

This kinda flies in the face of the aesthetic that I was talking about earlier, but it should be some some help with accessibility issues.  If you're having trouble picking something up, right-click the ground around it.

**Comment by tommai78101** [comment]
Thanks, will try that method.
