### ISSUE TITLE
Band homelands allow for birth chaining very far away

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#905]
Since the biome bands were introduced, players are now only homesick if they travel above or below their band. There is no limit to how far east or west players can travel while still maintaining the ability to have kids. This has largely been a nice improvement over the previous system, where you had to stay very close to the town well, since it allows families to easily move to other nearby towns if conditions are favourable.

However, in recent times a few individuals have been abusing this mechanic to travel extremely far east (e.g. over 100,000 tiles away). Such distances are too far for one player to reach in their life, but these players have been using a collection of alt accounts so they can keep getting reborn to themselves as they travel farther and farther away. By using sports cars along with the highways that already exist spanning the map, it is possible for them to travel tens of thousands of tiles in one life. This rate slows down once they reach the part of the map that has already been culled, but they can still travel considerable distances in the wild.

Several examples of this activity (some more successful than others) can be seen in the lineage links below:
- http://lineage.onehouronelife.com/server.php?action=character_page&id=9646776
- http://lineage.onehouronelife.com/server.php?action=character_page&id=9654205
- http://lineage.onehouronelife.com/server.php?action=character_page&id=9665102
- http://lineage.onehouronelife.com/server.php?action=character_page&id=9666216

I have linked to the start of these birth chains; follow them down to the end of the chain to see just how many hours these players have been spending doing nothing but travelling east. Evidence to support that it is mostly being done by one or two players with alt accounts is provided by [the last words of one of the chain members](http://lineage.onehouronelife.com/server.php?action=character_page&id=9654455) in the second link. The public life logs provide clear evidence that these chains are being used to travel very far east.

This activity is problematic for several reasons:
- The chainers are poor moms and starve/kill any children they have that are not their own alt accounts or friends. They also end up stealing births away from the rest of the family in the regular game area, which can easily lead to family death.
- Once the portion of the family that remained in the regular game area dies off, other towns would need to travel distances beyond what is possible in one life to trade (assuming they were to set up their own town at such extreme distances).
- Most importantly (and the reason for the above attempts), an apocalypse at such extreme distances could be impossible to stop. Not only does it force other players to use the same birth chaining techniques to follow them, but if they travel far enough away it wouldn't be possible to reach the apocalypse tower even if someone were to start heading after them immediately upon hearing the first apocalypse bell. The only reason the above attempts did not result in an apocalypse is due to other players with alt accounts who spent just as much time travelling the same distances to stop them.

Unfortunately, the current curse system is not equipped to deal with this activity:
- You cannot curse someone who is that far away from yourself. Even if you could, as you can see from the lineage links these birth chainers are mostly nameless.
- The babies that are born to and starved/killed by the chainers are not able to curse them. There are no other good players around to punish this behaviour either.
- Existing curses against the chainers are ineffective since they are far beyond the curse blocking radius, even if they have very high curse scores. They only need a single account to get born in the main game area to start their chain. After that, any other accounts they have become usable again.

I'm not sure what the best solution here is, to be honest. If they systems you put in place for the well-based homelands are still intact, perhaps a hybrid approach could work? Consider this: to be able to have kids, you not only have to be within your own band, but you _additionally_ have to be within a certain distance of your family's well. This distance can be rather generous, say 10,000 tiles, which should avoid ruining the benefits of the band-based homelands while also foiling those who wish to birth chain to larger distances.

**Comment by lorocyproca** [comment]
I agree that this is an issue.

Depending on player behavior, the culled area of the map is usually about 30k tiles East of the living families. With a highway and a sports car, a player who leaves early and wants to visit the old towns already has enough time to make a return trip in a single life. 

There is no reason to go back into the culled map area, and therefore no reason to birth chain beyond 30k tiles (or even 10k) from the family well unless -

- You are specifically trying to set up a place far enough away for cursed out DT players to spawn again.
- Or you are trying to travel such a long distance to set up an Endtower so that any others would have to make the same multi-life journey to take it down. 

I'm typically not a fan of apocalypse strategies that require modded players to respond to them, and this is one of those strategies that vanilla players could not achieve as they would be unable to hold the bell marker between lives.

**Comment by cordy-123** [comment]
> I'm not sure what the best solution here is, to be honest. If they systems you put in place for the well-based homelands are still intact, perhaps a hybrid approach could work? Consider this: to be able to have kids, you not only have to be within your own band, but you _additionally_ have to be within a certain distance of your family's well. This distance can be rather generous, say 10,000 tiles, which should avoid ruining the benefits of the band-based homelands while also foiling those who wish to birth chain to larger distances.
 



Currently, ANY well you make is a family well.

This should **NOT** be removed to accommodate the anti-apocalypse concern. (Too much already has been changed for anti-apocalypse issues.)

Since having the ability to make a secondary (etc) family well helps fams move (in cases of long generation families, because they are too far east compared to other fams), etc. For example, the current longest lasting fam on record was around 12k-15k (maybe closer to 20k? It's been a long time. I can't remember exactly.) east of all the other fams by the time Content fam died off. They could have moved west to be with the other fams. 

Sometimes, you're being chased by a griefer leader (and his friends) and you're the only girl. You need to live in the wild and make food for your family (with generational food decay, you can't just eat wild foods) until the griefers die of old age. Either you're smart enough to bring a shovel or your family still has it's iron unlock (because the eve resettled an old town), so you make do with this new town. You make it work until the griefers are dead and then go back to your old town. (Of course in this example, you wouldn't go 10k. But it shows the importance of the availability of being able to give birth in a different place other than the "main town.")

**Comment by jasonrohrer** [comment]
Yeah, this is an interesting problem.

I do generally love that the apocalypse works how it's supposed to work... it's like a grand battle between the forces of good and evil.  I saw Oppenheimer a few days ago... it reminds me of that.

There may just need to be some modification to the way that the whole apocalypse mechanic works.  Like... maybe the Dark Nosaj thing can only produce end-stones if it's near a population center.  Though I imagine that even that wouldn't work, because they'd just gather all of them near the towns, and then chain-travel across lives with a car full of them.

So maybe the end tower itself just can't seep if it's too far away from the largest population center.  It can still be far enough away to make it tense and interesting.... but just not forever away.


I gather that the vanilla client doesn't show the apoc arrow for long enough.  I will look into that also.

**Comment by jasonrohrer** [comment]
Oh, I see... holding the bell marker between lives.  Looked at the code, and the bell maker is currently permanent during a life.

I'm not sure how the modded clients are doing this, because all the coordinates that the server sends to you are "normalized" around your birth location.  I.e., where you were born is 0,0 for that life.

So if you get a monument call message in one life that says (500,-250), that position won't be valid in the next life.

Maybe there's a coordinate leak somewhere in the protocol?

Or maybe they are kinda re-constructing absolute coordinates from the movements of other known players that exist across lives?

**Comment by squishysquid** [comment]
could try just blocking being born to accounts logged in from the same ip address. while that can be circumvented, we kind of know the people doing this, they aren't figuring it out.

**Comment by TheMingo888** [comment]
> Oh, I see... holding the bell marker between lives. Looked at the code, and the bell maker is currently permanent during a life.
> 
> I'm not sure how the modded clients are doing this, because all the coordinates that the server sends to you are "normalized" around your birth location. I.e., where you were born is 0,0 for that life.
> 
> So if you get a monument call message in one life that says (500,-250), that position won't be valid in the next life.

Modded clients are not holding the bell marker between lives. When the bell happens, they get the coordinates relative to their birth (e.g. 3000 tiles to the right of their birth). If they give birth to one of their alt accounts or friends, they can pass this information on manually (e.g. if they give birth 1000 tiles to the right of their own birth, they know the bell must be an additional 2000 tiles to the right). Such clients generally have a way to create waypoints at manually entered coordinates (relative to your birth) to streamline this process.

> Maybe there's a coordinate leak somewhere in the protocol?

Radios will leak coordinates. Try standing next to a radio transmitter while issuing an order or using a map and look at what comes out of the receiver. Though, I don't know of any modded clients that actually exploit this.

> could try just blocking being born to accounts logged in from the same ip address. while that can be circumvented, we kind of know the people doing this, they aren't figuring it out.

I support any efforts to stop the alt accounts, but this wouldn't prevent two friends from birth chaining since they have different IPs.

**Comment by TwistedHBG** [comment]
Bell markers are inherited by kids from their mothers in certain situations (this was added agessss ago I don't remember the details - maybe if the mom doesn't have a home marker?). This probably works the same for apocalypse bell markers?

**Comment by TwistedHBG** [comment]
https://github.com/jasonrohrer/OneLife/commit/307573a6d82af7d309acfa868c2fcf306899ad23
