### ISSUE TITLE
Tutorial lives are inconsistently logged

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#914]
It appears some tutorial lives are showing up in the public life logs. I can tell they are tutorial lives since the x-coordinate is 5,400,000 (for the first tutorial) or a larger number (for the second tutorial). What is interesting is that it is only ever births that are logged and never deaths. As well, many tutorial lives do not get logged. I am not sure what is causing this strange behaviour.

**Comment by cordy-123** [comment]
From my notes from 2022
     
You only show up in the life logs as a tutorial spawn...  

When you twin (or trip or quad) and your friend doesn't have TutorialDone setting to 2. 

So it's a very rare case.

The one who doesn't have TutorialDone setting to 2 must be the last person to hit the login button in the twin screen for them to spawn in Tutorial.

----
----


My notes also say that the person who DOESN'T need the tutorial shows up in the logs. 
 
But the one who DOES need the tutorial (doesn't have TutorialDone setting to 2) does NOT show up in the life logs.


So these lives SHOW UP on life logs because **THEY ARE NOT TUTORIAL LIVES**. Not in the real sense and, therefore, are logged. They spawned regularly and just got brought to the tutorial area by accident.

------


Rare case. Usually only happens when a player invites their friend to buy the game and play with them. And they twin on their first life. (Or one of their first few lives. Depends. Sometimes, the experienced player hits the login last their first Twin life. Then, when they relogin as twins, the new player hits the login button last.)

---

I've also seen it happen before when Spoonwood would twin/trip/quad with OHOL twitch streamers like Twisted (a few years ago).

Since Spoonwood often would look in tutorial to see if there was an eve spot open because he liked eve-sniping, he would often forget that he would still be set to have tutorial when he would quad with Twisted (or others). And they would all show up in Tutorial.

This would result in Twisted and other people being logged but Spoonwood not showing up on the life logs.

---

Of course, this also happens to people who like to use the tutorial to get rid of lineage legacy (before the 'Goodbye Forever' update) and then they forget and twin. 

Etc, etc. 
(People who use tutorial to see how the fam are doing - using hetuw mod shows the number of fertiles in all the fams in the server, people who use tutorial to talk on the hetuw mod's chat, etc. and then forget that they are in the tutorial setting when they login as a twin in a few days.)

**Comment by cordy-123** [comment]
Example from the latest life logs
http://publicdata.onehouronelife.com/publicLifeLogData/lifeLog_bigserver2.onehouronelife.com/2023_08August_22_Tuesday.txt    

----
c67-hash is the old player. 
0da-hash is the new player friend of c67.

---

c67-hash spawning in regular spawn (NOT as a twin)
B 1692675842 6581639 c679cdfe96b76c0ccce3cc01361ca0afbda06857 F (-457989,211) parent=6581554 pop=47 chain=20 race=D
D 1692679394 6581639 c679cdfe96b76c0ccce3cc01361ca0afbda06857 age=59.19 F (-457989,220) hunger pop=42

----

5 minutes later
Here c67-hash's life is seen on logs because based on settings, it's not an actual tutorial life. He just got brought along by his twin friend.
And because 0da-hash is actually supposed to spawn in tutorial based on their game setting for 'TutorialDone', 0da-hash's ACTUAL tutorial life is not logged. 

B 1692679730 6581759 c679cdfe96b76c0ccce3cc01361ca0afbda06857 F (5400000,8920) noParent pop=41 chain=1 race=C


----

13 minutes later...they spawn in regularly as twins.
This is 0da-hash's 1st life ever in regular spawn.

B 1692680466 6581775 c679cdfe96b76c0ccce3cc01361ca0afbda06857 F (-457430,128) parent=6581724 pop=39 chain=52 race=D 
B 1692680466 6581776 0da6ed0fb6cb3ec39fc53cbfde094410f395fd61 F (-457430,128) parent=6581724 pop=40 chain=52 race=D
