### ISSUE TITLE
 𝐍𝐨𝐛𝐨𝐝𝐲 𝐥𝐢𝐤𝐞𝐬 𝐢𝐭 𝐡𝐞𝐫𝐞.

### ISSUE THREAD

**Issue by NotSoShady116** [jasonrohrer/OneLife#917]
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/4ca4d869-dae2-47d6-a049-cb74438c676a)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/eff22f50-dada-4aa9-a115-3063f4931566)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/c7dbb48c-48ec-4c2b-825b-dcc42b2599ff)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/e224c892-cc28-432f-a066-5059f75702e5)
![image](https://github.com/jasonrohrer/OneLife/assets/126307271/3c28093a-f5e2-4c44-a48b-fb2c4f0a2069)

**Comment by NotSoShady116** [comment]
Anybody who says you all deserve it imagine yourself in our position. Stuck in donkey town with no place to go, just endless Bodrum. Some people even leaving the game forever because they are trapped in there forever.

**Comment by NotSoShady116** [comment]
Five years

**Comment by jasonrohrer** [comment]
Remember, this only affects you if there's no place for you to be born, because you've bothered THAT MANY other players.  I.e., the map is quilted with currently-playing players who don't want you around.  How is that possible?  It's only possible because you have bothered so many people.

This is also, perhaps, why d-town is "lonely."  Because there aren't that many other players who have bothered this many other people.
