### ISSUE TITLE
bugs with buildings on biomes

### ISSUE THREAD

**Issue by D3mon1cblack** [jasonrohrer/OneLife#920]
Wall shelves on a biome are not accessible for non specialists.
Also auto floored vertical doors and horizontal not floored doors can not be used by non specialists aswell.
The auto floored vertical doors were usable before the indoor bonus overhaul and become ugly if you would floor them (full tile of flooring instead of the 2 adjacent tiles joining on the door).
This is a clip i made demonstrating it. https://www.twitch.tv/d3mon1cblack/clip/RelievedGleamingMeerkatVoteNay-17H2jM6b6pHE_Q0s

**Comment by cordy-123** [comment]
Whenever I build doors or horizontal adobe walls with shelves) in hostile biomes, I place floors under them.

I don't think it needs to be changed.

I think people should just teach the game mechanics associated with it.

**Comment by jasonrohrer** [comment]
Yeah, I see how this is counter-intuitive, since the floor is depicted visually as going right up to it, especially on the door.  And it's pretty weird to extend the floor out under/behind horizontal walls.  

I'll look into making it so that if you're standing on a floor, you can manipulate things in a bad biome.

I'll still try to keep the "edge effect" in place if there's no floor around.  So you can't stand right outside the jungle and pick a banana.  But if you build a floor there, you still could, which is weird.  But there's no way around this side-effect without introducing other edge-case weirdness.  The most important thing is that people don't get stuck unexpectedly.

**Comment by jasonrohrer** [comment]
Actually, it's better to use the "floor hugging" feature to detect these cases.  All walls are currently marked that way.
