### ISSUE TITLE
Note works like a map.

### ISSUE THREAD

**Issue by MrMendeleev2** [jasonrohrer/OneLife#923]
At x=-400674&y=-357, or really close there was a Paper with Permanent Writing. It works like a map produces map pointer, and changes content if used at different positions. This place may be already wiped, but it was there nonetheless.
I suppose it's not intended behavior. I wasn't able to reproduce it, and 100% sure it's not problem with textures on my side. Wondible's map proves that it's a paper and not a map. 
![Screenshot_116](https://github.com/jasonrohrer/OneLifeData7/assets/91346213/2ec3ebfd-4e3c-4e8a-8c8e-ba94d7687b9e)
![image](https://github.com/jasonrohrer/OneLifeData7/assets/91346213/da6129f7-d18c-4a55-89eb-82393f8f162d)

**Comment by MrMendeleev2** [comment]
by 
> changes content if used at different positions

i mean distance, of course. As expected of map

**Comment by jasonrohrer** [comment]
Oh... I know what causes this problem.  It's the limited address space in the metadata database, and what happens when it wraps around eventually and re-uses ID, overwriting the old ones with new content.  Thus, someone made a map, and we had wrapped around, so this old note paper was overwritten with map data.

https://github.com/jasonrohrer/OneLife/issues/901

This is inherent in the way that metadata is implemented, unfortunately.
