### ISSUE TITLE
Name choice system

### ISSUE THREAD

**Issue by MrMendeleev2** [jasonrohrer/OneLife#925]
As of now when you try to name someone and name isn't present in name list next in lexicographical order name is chosen.

Problem is, it often poorly represents namer's intentions and really prone to misspelling. in the other words first letters are much more influential in comparison to the later ones. At the same time original name often 'grows' due to nature of name list sorting.

There are a few things that can be done to improve current system.
One that comes to mind naturally is to use Levenshtein distance instead of lexicographical order. Problem with that is, something like agrep or similar algorithms in C work with worst case time of $O(M^2N)$ where M is the length of original name (in our case) and N is the length of dictionary. 
Not $O(1)$ as before of course, but can be improved. We can improve it by building a Trie over the dictionary, yielding $O(MK)$ K is the size of Trie (often much smaller than Dictionary itself)

Other problem is to choose one of multiple closest names, but we always can cast it randomly or do it in lexicographical order.

maybe it's not an optimal way, I can understand it, but it will better convey parent will to name their child. Nontheless something to consider

**Comment by jasonrohrer** [comment]
Hmm... I tried using an efficient Levenshtein implementation, that uses memoization, and even that one is very slow.

We have 150,000 last names on the list, for example.  Finding the closest match using Levenstein is taking 21 seconds.  That's for processing ONE player-submitted name.

I see how the Trie would help, since it would let us re-use the memoization table in many cases instead of re-building it for each pair of words we need to compare.

But my goodness, that's a lot of complexity.

And it also produces weird results in a different way... 

Let's say you pick the name RASON.   Well, the current algorithm is going to assign you the name RASO, which makes quite a bit of sense.  But Levenshtein is going to give you BASON instead.  Add one letter, and it comes first in the list.

I'm guessing that if people make typos, they are probably going to do it in the middle of the name, and not at the beginning, right?  So the current method is more likely to find the name that they meant to type.

**Comment by jasonrohrer** [comment]
Just to give a more relevant example, let's say someone picks the last name PUSSY, which is currently not on the list.

The current code assigns them the name EVE PUSSER, which seems fine to me.

Levenshtein would assign them EVE BUSSY.  I guess that's okay, but it seems less close to PUSSY than PUSSER to me.  Levenshtein doesn't account for whether words sound similar or not.
