### ISSUE TITLE
Add Unicode and Translation to the Game

### ISSUE THREAD

**Issue by skps2010** [jasonrohrer/OneLife#931]
In China, there's a lot of people playing OHOL-like games everyday.
They are: 希望之村、華夏人生、希望之村2. They are free(in China, paid elsewhere) mobile games. Thier player count is 520, 489, 284 at one point this year.
One of the reason they play them instead of official OHOL is because their English is bad. I have seen them complaining about official OHOL has more stuffs and is friendlier than mobile version, but they can't play because of language barrier.
So if you add Unicode support and translation to the game, and make videos to promote it in China, many players may join.

I have added Unicode support and translation to the game in my mod: https://github.com/skps2010/OneLife
You just need to accept my merge requests in [here](https://github.com/jasonrohrer/minorGems/pull/13) and [here](https://github.com/jasonrohrer/OneLife/pull/930)

I know you don't want to put efforts into translating, but you can leave the job to your players.

Here is how my mod and translation work:
- We maintain the translations in this [Google sheet](https://docs.google.com/spreadsheets/d/1AH6eZJJ5zkB1zT-iwlomVAUxsa4f7gIgYFS0X265GyM/edit#gid=0). Everyone can ask me to become an editor of this sheet. We use [Discord](https://discord.gg/UFZg3WXGrU) to discuss translating stuff.
- Currently we have Traditional Chinese, Simplified Chinese and Ukrainian translation. The Google sheet automatically pull the newest stuff from your Github, so our translators can focus on translation only.
- My mod has a translator that can pull the newest content from the Google sheet. It will replace texts in `objects/xxx.txt` and `languages/English.txt`. It also replace images in`graphics/` and change value in `settings/`
- My mod supports displaying UFT-8 strings, so it will just display them. All fonts use the same Unicode font when the codepoint is >128. Unicode char wide, size, offset are all the same and is decided by settings.
- The font.ttf I use is called [小賴字體](https://github.com/lxgw/kose-font). It's hand-written style and is free for commercial use.

Here's some images:
![Imgur](https://i.imgur.com/LHcp2Qy.png)
![Imgur](https://i.imgur.com/9AjlblQ.png)

**Comment by is52hertz** [comment]
I've always thought that,
_(Please read it carefully, don't skip it, it took me three whole years to write it. You can see why below)_
OneHourOneLife is a game with the most potential.
He has a chance to surpass games similar to Minecraft.
Because OneHourOneLife, like Minecraft, was once like this - a small, popular, and full of potential. (Early development version of Minecraft)

But sadly, OHOL stopped at the beginning, that time when it was popular. Why? There are many reasons, on the one hand there is no use of more language support, on the other hand - deeper, OHOL has not been used with amazing features for a long time.

If the developer is thinking "OHOL is no longer popular, I don't care about OHOL anymore!" then you don't need to read any further, because the developers have already given up on the game ("Everyone is looking forward to it, but you're not looking back"), and can just close the issue and type "Done!"
_
_
_
Okay, you're still reading these words. So I'll go into detail - OHOL's potential, how OHOL is secondarily popular.

OHOL's potential:
Skps2010 is a bit of a euphemism.
In China right now, just "希望之村" (YouAreHope's Chinese proxy version) has a few hundred people during the inactive period. Not to mention that there are many other OHOL-like games out there.
For example, NextLife, which just came out in China, had tens of thousands of downloads in its beta test (and attracted millions of fans to make gameplay videos).
A year ago, the average daily players of "希望之村" could reach a staggering 1,000+ people!
This is a strong proof that OHOL gameplay is very popular and has potential.

Improvement measures for OHOL:
First, one person is always better than a team. I know it's hard to hear players praise "OHOL was developed by one person!" I know it's a sense of honor to hear players praise "OHOL was developed by one person!" or something like that. But one person is not enough to develop a game the size (yes, I, we, think so) of OHOL. We need a team, or even a community to suggest or participate in the development of OHOL.
Now, to be honest, I am an honest follower of OHOL. I want to make OHOL better too, and if you want, we can help develop OHOL together.

Second, OHOL must have a core development direction.
It's simple - follow the original idea and make OHOL the world's first 2D reality-like game! I'm not talking about a reality-like game that looks like reality, but at its core is a 1+1=2 game, OHOL should aim to mimic reality, such as a fully automated, real-time weather system, where the weather in every place is traceable.
_
Okay, when you read that, you can forget about the suggestions made in point 2 above, because those are too difficult to realize.OHOL should go towards the big goal of imitating reality, not immediately making something big and nonsensical.OHOL should not derail from imitating reality. That's a big problem with OHOL right now.

Third, emotion - life and death.
The second major gameplay aspect of OHOL is that players can experience a variety of emotions in the game (family, friendship...) , which is another big reason why OHOL endures.

In conclusion, OHOL should define the overall development direction, main idea, gameplay, and then have a group of people that love OHOL and develop OHOL for that purpose.

What to do, a final reiteration:
First, a group of people is bigger than one person.
Second, prove to the players that they are alive.
Third, abide by the heart.
Fourth, "I'd like to continue developing OHOL because it's my favorite game, not because of how much more money I can make, simply loving it is enough."

If you're reading this, it means you love OHOL as much as I do:
Let's join together: https://discord.gg/Gf4JHTWj

Notes:
OHOL in the text refers to OneHourOneLife (there won't be anyone who doesn't know that)
There are various kinds of sarcasm, quotes, parodies, etc. within the quotes in the text, and the 'I' part within the quotes refers to 'you'.
Reference:
http://ofw.yzy3.top/
https://zhuanlan.zhihu.com/p/61209734
https://www.bilibili.com/video/BV1eh4y1Q7Ar
https://www.bilibili.com/video/BV1XW41137QW
OHOL's Steam China comment section.
A tall tale from someone at the "希望之村" forums.
Here you are in the topic wanting to make OHOL hot again.

If you're skipping reading this, it's definitely unclear. I really hope you can read it carefully, in order to write it and write it well, I spent 3 whole years.

52Hertz,
Zhejiang, China
September, 2023
OneHourOneLife

**Comment by is52hertz** [comment]
The entire article was translated using DeepL.
There may be some parts that are not in line with the sentiments I need to express.
As a 'qualified' author.
I need to write a post-viewing quote here.
This is the original Chinese version (I modified it a bit to make it easier to be translated, the original text may be too highbrow)
我一直这么认为，
OneHourOneLife是一部最有潜力的游戏。
他有机会超过类似于Minecraft的游戏。
因为OneHourOneLife和Minecraft一样，曾经都是这样——一个小的，受欢迎过的，并且充满潜力的。（Minecraft早期开发版本）

但是很遗憾，OHOL止步于起点，那次热门的时候。为什么？有很多原因，一方面是没用更多语言支持，另一方面——更深层次的，OHOL已经很久没用出过令人惊讶的功能了。

如果开发者是觉得"OHOL已经不受欢迎了，我也就不管OHOL了！"那么下面的话也无须多看，因为开发者已经放弃了这款("众人都期盼唯你不回头")游戏，大可关闭这个议题，然后打上"已完成！"
_
_
_
好吧，你还在看这些话。那么我就详细说说——OHOL的潜力、OHOL怎么二次受欢迎。

OHOL的潜力：
Skps2010说的有些委婉了。
在中国的现在，仅仅“希望之村”（YouAreHope中国代理版本）在不活跃时期就有几百人。更何况类OHOL的游戏还有很多。
就再比如刚刚出的NextLife中国代理版，内测下载就达几万（引来了几百万粉丝的播主来拍摄游戏视频）。
在1年前，"希望之村"日平均玩家都可以达到惊人的1000多人！
这已经有力的证明OHOL玩法是及其受欢迎的，也是及其有潜力的。

OHOL的改进措施：
第一，一个人总比不上一个团队。我知道，听玩家赞美"OHOL是一个人独立开发出来的！"之类的话确实让人觉得有荣誉感。但是一个人不足以开发OHOL这么大体量（是的，我，我们，这么觉得）的游戏。我们需要一个团队，甚至一个社区来为OHOL提出建议或参与开发。
现在，讲真的，我是OHOL的诚实追随者。我也想让OHOL更好，如果你愿意，我们可以一起帮助开发OHOL。

第二，OHOL必须要有一个核心开发方向。
这很简单——遵循初心，让OHOL成为世界首个2D类现实游戏吧！我说的类现实游戏不是那些看着画面像现实，但是核心就是一个1+1=2游戏的那种。OHOL应该向着模仿现实这个大目标走，比如一个全自动实时运算的天气系统，每个地方的天气都有迹可寻。
_
好的，当你看到这句话，你可以把上面第二点提出的建议忘掉，因为这些太难以实现了。OHOL应该向着模仿现实这个大方向走，而不是立马做出一些无厘头的大东西。OHOL不应该从模仿现实中脱轨。这也是现在OHOL的一大问题。

第三，情感——生死离别。
OHOL第二大的玩法就是玩家能在游戏里体验到各种情感（亲情、友情...），这也是OHOL经久不衰的又一大原因。

总之，OHOL应该确定总体开发方向、主旨、玩法，然后有一群人，喜爱着OHOL，并为此开发OHOL。

该怎么做，最后的重申：
第一，一群人大于一个人。
第二，向玩家证明自己活着。
第三，遵守本心。
第四，"我还愿意继续开发OHOL，因为这是我最喜爱的游戏，不是因为能再赚多少，单纯热爱，就足够了。"

如果你看到这，说明你对OHOL的热爱程度和我一样：
让我们一起：https://discord.gg/Gf4JHTWj

注:
文中OHOL指OneHourOneLife（不会有人不知道）
文中引号内有讽刺，引用，模仿等多种，引号内的「我」部分指的是「你」。
参考资料：
http://ofw.yzy3.top/
https://zhuanlan.zhihu.com/p/61209734
https://www.bilibili.com/video/BV1eh4y1Q7Ar
https://www.bilibili.com/video/BV1XW41137QW
OHOL的Steam中国区评论区。
希望之村论坛某个人的高谈阔论。
在这里，议题中想让OHOL再火一次的你。

如果你是跳读过来的，肯定是不明不白。我真切的希望你能认真读完它，为了写它，写好它，我花了整整3年。

52Hertz,
中国浙江
九月，2023
OneHourOneLife

**Comment by jasonrohrer** [comment]
Ah!  This is really great!  Thank you for doing this work.

Looking at the changes, though, this is a very deep change that touches so many parts of the game AND my underlying frameworks that are used in other games of mine (like Font.cpp from minorGems).

Also, I'd be worried about the contents of a collaborative google sheet getting pulled automatically into the official OHOL game for some players.  Official means that I approved it.  What if a bad translation slips through?


What are your thoughts on maintaining this mod as a separate thing that people can download going forward into the future?

I could link to your mod from the main home page, so that people could find it.

The one problem is in the future, when the OHOL version changes, how will your mod keep up?

Can you have an automated script in place somewhere that builds/updates your version through github, when the main OHOL version changes?

**Comment by skps2010** [comment]
I think you can add an Attention Page saying that "Translation is not official made, and is not associated with the owner. Use it at your own risk"

Adding a link to my mod is also great.
Right now I manually update my mod (by pulling code from your master branch) when you update the game. It should be possible to make an automated script for it, but I haven't figure it out.

**Comment by skps2010** [comment]
For the change part, I think my change is not that deep, most of them are scripts and makefile that can be discard if you want. For minorGem, I think my change will effect nothing If you only use ASCII. You still need Freetype library though, maybe I can make an option to turn it off? so it can still apply to every other games. I can make my change minimal(remove all scripts, readme, etc.) if you wish.

For official part, I think you can add an Attention Page saying that "Translation is not official made, and is not associated with the owner. Use it at your own risk"

I think making translation an integral part of the game is necessary, because althouth my mod's instructions are really clear, Some players will still don't know how to use it, or just afraid to use it.

Adding a link to my mod is also great, althought not the best.
Right now I manually update my mod by pulling code from your master branch when you update the game. It should be possible to make an automated script for it, but I haven't figure it out. I think I can do that by using Github action.

Also my mod has Mac version, so maybe you can also add a notice somewhere to tell people to download my mod for unoffical Mac version

**Comment by jasonrohrer** [comment]
Please understand that, since I wrote all this code myself, it is very personal to me.  I can't just merge huge changes like this without going through them, line-by-line, to understand what they are actually doing.  And the reality is that I don't have time to do that, for very big changes made by others.  I need to understand all this code myself if I'm going to work on it and maintain it.

Also, I have many other games depending on the same code.  Making sure the merged changes work okay with all those other games is a huge task.

Anyway, I'm going to add a link to "Unicode Mod" at the top of the main home page.  That should hopefully be a start.

Also, regarding the Mac version, Mac is no longer a supported platform, and I don't want to give customers the impression that Mac is still supported through the mod.  I don't even have a modern Mac that I could test the mod on myself, and I can't promise customers a working Mac version that I myself haven't even tested.

It's great that there is a Mac version of the mod, however!
