### ISSUE TITLE
Forgiveness Radius

### ISSUE THREAD

**Issue by cordy-123** [jasonrohrer/OneLife#933]
Currently, there is NO forgiveness radius.

You can forgive people from millions of tiles away.

It definitely needs to have a radius.

And I'd suggest to MATCH it to the curse radius (which is **200 tiles**) as it makes sense since cursing and forgiveness are 2 sides of the same coin.

----------- 
-----------

Why should there be a forgiveness radius?

- **VERY Inconsistent** with the other game mechanics

It just doesn't make a whole lot of sense for people to be forgiving people that are thousands, millions of tiles away. It's simply not logical to forgive someone you haven't ever seen.

Cursing is 200 tiles. Getting leader/property is adjusted to those nearby. Even making the endtower has a radius of 10k. 
But nah, you can weirdly forgive someone millions of tiles away. People you never met.

- Creates weird gameplay. 

Currently some phex chat _(phex is the in-game chat box of the hetuw mod)_ users that are constantly in dt have been hounding people on phex to say "I forgive Eve _____ (their dt eve name)" whenever they are in dt. 

And ALSO, telling the non-dt phex players to tell the people in their towns to say it.

---> Doesn't really make sense to forgive someone 200 million tiles away (which is how far dt is), right?

---> It's already weird meta gameplay for phex players to forgive a dt phex player from far away. 

But I think it's even very much weirder for a vanilla player just regularly playing and then just have a bunch of phex players come to each player in town and saying please say "I forgive Eve ______". 

The vanilla player would be all like, "Who? Who's that?"

And the phex player would be like, "Just say it! It's for my (phex) friend! He's innocent I tell you!" 

- It also happens within different fams/towns, not just from dt to regular spawn.

I've seen someone say (in phex chat) "Hey, I can't spawn in white fam and brown fam. Can you guys ask if they would forgive blank name?"

---> I really think that mod users shouldn't have that much more advantage over vanilla users. (Well, not more than they already have now.) Having an extra no-effort at all way to ask for forgiveness.

---> Again, weird asking/harassing of non-mod users to forgive mod users.

-----------
-----------

To be fair, this is not a common situation. 

I've only seen this happen maybe once, twice a week for the last couple of months. (Ofc, forgiveness is a fairly new game mechanic.)

But that's because MOST mod users don't know that forgiveness has no radius.

Once word gets out (and it will because quite a few people read github issues and share exploits/game mechanics on discord or phex chat), this will become more common.

-----------
-----------

Forgiveness should be FREELY GIVEN and/ or earned. 
Not harassed or outsourced to other mod users.
Or at the very least the cursed should make an effort and come to the town and ask for forgiveness.
It's quite unfair for cursed vanilla players who don't have this SECRET 'special' recourse that mod users have.

**Comment by TheMingo888** [comment]
I think this should remain as it is, actually. First of all, forgiveness isn't a new mechanic at all, and I have never seen players harassing others to forgive their friend in donkey town as you describe above. Of course, it may just be a suitably rare event that I haven't yet witnessed, but even so, most players are well aware of the impacts of cursing and forgiveness, so they would only forgive someone if they felt it necessary.

And there are lots of legitimate reasons to forgive someone that is far away from you, too. Consider these three scenarios which I have personally experienced in the past few months:
- I witnessed a player kill someone, and so I killed them and we naturally exchanged curses. Later, we chatted about the incident. It turns out they were killing a problem player and I had jumped to the wrong conclusion. We exchanged names using Phex and were able to forgive each other, even though we were very far apart (since we had each other cursed and thus were guaranteed not be born near each other).
- I tried to curse a griefer called Sophia, but made a typo and cursed Sophie instead, who it turns out was a friend! I only realized this after my life was over. They told me the name of their new character over Discord, and I was able to login and forgive them.
- Due to a miscommunication, myself and other town members thought a new baby that was born was the same person who was leading bears to our town earlier, so we all killed and cursed the child. This miscommunication was realized afterwards, but by then the damage was already done and this person now had an extra 5+ curses. We were able to resolve this situation by asking them for their new in-game name in Phex and forgiving them from far away.

Now that curses last 5 years and impact your curse score for the entire period, it is extremely important to avoid cursing innocent players. Mistakes do happen, though, so being able to forgive them from anywhere is necessary (since cursing them will naturally prevent them from being born near you). There isn't any sound or coloured text when you forgive someone to indicate if it worked or not, so making it always work if the name is correct is very convenient. I understand the desire to prevent griefers from tricking players into forgiving them, but this is a much smaller concern than leaving innocent players with undeserved curses.

As well, some players do genuinely get stuck in donkey town 200 million tiles away. While most of these players probably deserve to be there, there may be a time when we feel remorse for their situation and want to play with them again, especially if the curse was for something minor. If we can't forgive from far away, it would be impossible to undo their plight (beyond using "I forgive everyone", but there are lots of players I certainly _do not_ want to forgive).

**Comment by cordy-123** [comment]
Mingo I've seen your hash forgive from what I can only assume is tutorial.

Because that life id of yours that forgave was not logged in the life logs. (Currently, only tutorial lives are not logged in the life logs.)

Tutorial is 5 million tiles away from regular spawn.

I certainly don't think that is logical to be able to forgive from that far away.

----

I think I noted it somewhere. I'd have to find it later if I need to and post the link to that day's curse logs.

**Comment by cordy-123** [comment]
> 
> 
> And there are lots of legitimate reasons to forgive someone that is far away from you, too. Consider these three scenarios which I have personally experienced in the past few months:
> 
> * I witnessed a player kill someone, and so I killed them and we naturally exchanged curses. Later, we chatted about the incident. It turns out they were killing a problem player and I had jumped to the wrong conclusion. We exchanged names using Phex and were able to forgive each other, even though we were very far apart (since we had each other cursed and thus were guaranteed not be born near each other).

If you're a mod user, you definitely can take the 5-15 minutes it takes to go that person's town. Seeing as you already know that person's race.

If you think that's too inconvenient, the player who was cursed could come to you. As you are communicating on phex chat, you can tell them which town you are in. And since they are the one who has something to gain (one less curse), they can certainly take the 5-15 mins trip.

**Comment by cordy-123** [comment]
> 
>There isn't any sound or coloured text when you forgive someone to indicate if it worked or not, so making it always work if the name is correct is very convenient. I understand the desire to prevent griefers from tricking players into forgiving them, but this is a much smaller concern than leaving innocent players with undeserved curses.
> 

Certainly, adding a sound or colored text to forgiveness would be a welcome change.

**Comment by cordy-123** [comment]
> * I tried to curse a griefer called Sophia, but made a typo and cursed Sophie instead, who it turns out was a friend! I only realized this after my life was over. They told me the new of their new character over Discord, and I was able to login and forgive them.

Since you already knew their in-game name, you knew their race. As you are a seasoned pro with a mod, you can definitely go to their town and forgive them. (Or vice versa.)

**Comment by cordy-123** [comment]
> I have never seen players harassing others to forgive their friend in donkey town as you describe above. Of course, it may just be a suitably rare event that I haven't yet witnessed 
   
------  

> * Due to a miscommunication, myself and other town members thought a new baby that was born was the same person who was leading bears to our town earlier, so we all killed and cursed the child. This miscommunication was realized afterwards, but by then the damage was already done and this person now had an extra 5+ curses. We were able to resolve this situation by asking them for their new in-game name in Phex and forgiving them from far away.
> 

------

You just gave an example yourself of this happening. (Ok, it wasn't a donkey town to regular spawn. It was from different fams.)

You were asking people in your town to forgive this mod user. (Presumably, at least some of the people asked were vanilla players.)


------

Ah yes, the privilege of the mod user! The cream of the crop getting even more advantages! Getting 5-10 curses taken off because of a sob story they tell on phex chat.

------ 
 
And yes, I've definitely seen people asking for forgiveness in phex chat from DT. (example Eve Falkenberg)

**Comment by cordy-123** [comment]
The issue is not how to make it more convenient for you and players like you who are pro mod users (with all the special abilities that entails).

The issue is making sure that mod users don't have another special advantage vs. vanilla players.

And make no mistake, this IS a very big advantage.

-----

Additionally, the issue is also that it makes no logical sense to be able to forgive from thousands or millions of tiles away.

**Comment by TheMingo888** [comment]
> Since you already knew their in-game name, you knew their race. As you are a seasoned pro with a mod, you can definitely go to their town and forgive them. (Or vice versa.)

Oh, certainly. I am very determined person, so if I want to forgive someone, I will make sure it gets done. But remember, I was already dead by the time I realized my Sophia/Sophie mix-up. Forgiving them with such a small range limit would force me to be reborn, grow up to an age where I can say the full forgiveness phrase, and then trek over to the town where my friend is currently to forgive them. (Since I tend to care about my gene score, I won't use /die to land in their town, and if we had each other mutually cursed like in my first example, this wouldn't work anyways.) Afterwards, I still have the rest of my life to live if I don't want to die young and hurt my score (and we have enough AFK players by the fire as is, frankly).

But as you realize, this is very inconvenient. I may have the determination to do it, but many other players won't! The result is that lots of innocent players will end up with accidental curses they don't deserve. Cursing is a very powerful mechanic now, so it makes sense to limit it to 200 tiles (and one token per 15 minutes) to prevent abuse. It is _intentionally_ inconvenient. Forgiveness, on the other hand, is the inverse, and ought to be convenient so mistakes can easily be rectified.

> You just gave an example yourself of this happening. (Ok, it wasn't a donkey town to regular spawn. It was from different fams.)
>
> You were asking people in your town to forgive this mod user. (Presumably, at least some of the people asked were vanilla players.)
>
> I'm pretty sure I saw that incident in the logs and phex and that account you killed and cursed as a child was later revealed to be a bluehawk alt.

Yeah that's exactly right! Good memory. In this case though, I was the one who asked people to curse the baby, thinking they were the bear lurer from before. So yes, I did ask people to forgive his new life from far away, but only because I had made a mistake and caused (what I thought was) an innocent player to get undeserved curses. I would hate to be the reason an innocent player gets stuck in donkey town.

The reason I thought they were the bear lurer is actually really interesting. When they logged in as the baby, they had the Phex name of the bear lurer, but I thought it was some weird bug that caused the Phex name to get associated with the wrong life. It turns out, after investigation, that this was actually caused by Kaden (Bluehawk) not closing the game while he was switching between alts, and Phex remaining connected even while you are in the menus. Since he never disconnected and reconnected to Phex, he kept the Phex name of his old bear luring alt (summer_days) even though he switched to his new alt (typical_farmer).

> Ah yes, the privilege of the mod user. Getting 5-10 curses taken off because of a sob story they tell on phex chat.

No sob story and no privilege at all. I was just unaware of what happened and genuinely felt bad for giving the baby curses for something I thought they didn't do. I was the one who prompted the forgiveness, not him.

> And yes, I've definitely seen people asking for forgiveness in phex chat from DT. (example Eve Falkenberg)

Falkenberg is an excellent example! I know he was up to some weird shenanigans, like trying to force people to wear only fur clothing. I know some people who cursed him over this. However, some of them expressed that they felt bad for him being stuck in donkey town, and forgave him, since his crimes were minor compared to other griefers. _This might not have been possible if forgiveness was range limited._

I strongly believe there needs to be a path for people to leave donkey town, and right now forgiveness is that path. If forgiveness had a range limit, some other method would need to be implemented instead. Frankly, though, I think this method is best since it gives players complete control over who they want to play with.

> The issue is not how to make it more convenient for you and players like you who are pro mod users (with all the special abilities that entails).
>
> The issue is making sure that mod users don't have another special advantage vs. vanilla players.
>
> And make no mistake, this IS a very big advantage.

Mods are definitely a big advantage, since they allow zooming out and searching for items and chatting globally with Phex. I don't deny this at all.

But limiting cursing to 200 tiles is going to harm the vanilla players far more than it hurts us modded players. If we get cursed unjustly, we have the tools needed to communicate with other players (Phex) and explain what happened. We also have coordinates so we can easily navigate between towns to get within that 200 tile radius.

If a vanilla player gets cursed unjustly, it is much much harder for them to offer an explanation and get forgiven. They don't have a way of telling those that cursed them what their new in-game name is and what town they are in. Many vanilla players don't know how to navigate between towns, so they might not be able to return to the town they were cursed in. The result is that they will probably not end up having those unjust curses get forgiven.

**Comment by cordy-123** [comment]
> 
> > And yes, I've definitely seen people asking for forgiveness in phex chat from DT. (example Eve Falkenberg)
> 
> Falkenberg is an excellent example! I know he was up to some weird shenanigans, like trying to force people to wear only fur clothing. I know some people who cursed him over this. However, some of them expressed that they felt bad for him being stuck in donkey town, and forgave him, since his crimes were minor compared to other griefers. _This might not have been possible if forgiveness was range limited._
> 

Didn't falkenberg (phex username) later turn out to be an anger / 'I want revenge' griefer and tried to kill a fam by luring a bear.

**Comment by TheMingo888** [comment]
> Didn't falkenberg (phex username) later turn out to be an anger / 'I want revenge' griefer and tried to kill a fam by luring a bear.

I think that's right, heh, but we can only judge people based off what we know at the time. There are probably also scenarios where someone is forgiven from DT and turns out to be a pretty cool player. Misunderstandings happen, so it's nice to have tools we can use to rectify them.

**Comment by cordy-123** [comment]
We aren't gonna agree.

You think that players should have this privilege that greatly benefits the 'rich', ie. mod users, disproportionately.

I think not.

We presented both sides.

Mr. Rohrer can be decide what he wants to do.

**Comment by TheMingo888** [comment]
I disagree that this benefits _only_ mod users. It benefits vanilla players too. But only us modded players have the tools to easily navigate within 200 tiles of someone to forgive them (and indeed even know what name to forgive in the first place). Your suggested change would make things harder for vanilla players since they lack these tools to acquire forgiveness.

We have both argued our cases well. As always, I will leave the final decision to Mr. Rohrer.

**Comment by cordy-123** [comment]
How will people take cursing more seriously if forgiveness is so cheap.

**Comment by TheMingo888** [comment]
A 15-minute timer to acquire a new token is already a steep enough cost for people not to waste it. We don't want to make forgiveness more "expensive" since this would make it more difficult to correct any mistakes we make.

**Comment by cordy-123** [comment]
Then the issue isn't that forgiveness is cheap. 
        
It's that cursing is too cheap or too harsh.  

----

The ability to gain forgiveness should be the same across the board.

It's been 2 and half months since the update to the 5 year curse.

Perhaps, a little look into cursing and if they were any changes that the update brought about. (Probably look at the month before the curse update and then start again a few weeks after the curse update. [Since the first few weeks directly after the update, people were still being told about the update and the game culture was still adjusting.])

Relevant stats could include 
comparison on the amount of murders
comparison on the amount of curses per day
comparison on the amount of curses accounts are getting
comparison on the amount of people being sent into DT
curse scores (no comparison can be made because around the time that the 'long curse' update was made was when total curse score was actually fixed)
etc

But of course this would probably take a long time to check. So maybe not check it. Idk. 

----

My observations:

Some of the "major griefers" (ie. people with 5 or more accounts who actually succeed in killing towns. not griefers who attempt to kill the town with one bear.) have either mostly stopped playing or have started playing on an new account where they don't grief (if they want to grief, they switch to their "griefer account").

New accounts of "major griefers" get sent to DT quicker. 
(But this is mostly due to the CORRECTED total curse score fix. Previously curse score would just lower your curse score every time you played a certain amount of hours.)

I've seen a few people in-game discourage cursing "noob griefers" (how do i kill, sheep killers, babynappers, etc), spreading the word that the update changed it to 5 years.
(This is not to say that "noob griefers" don't get disproportionately get more curses per grief action vs experienced griefers. This can't be changed since they are noob griefers and therefore, they get easily caught griefing.)

More forgiveness happening since more cursers feel the weight of the 5 year curse.

A brief check of the amount of curses show that curses per day has sometimes shown it being around half vs before the update.
(Of course, the corrected curse score also has a major effect on this. Since an accurate curse score keeps more people in DT and therefore, there are less griefers to curse in regular spawns.)

----

Maybe a look back at the ideas of people in this previous github issue about the curse update: https://github.com/jasonrohrer/OneLife/issues/855

**Comment by is52hertz** [comment]
So what's the conclusion?

**Comment by cordy-123** [comment]
It depends on Mr. Rohrer.
           
If he thinks that it's fair for mod users should get their curses DISPROPORTIONATELY forgiven through using phex mod, then it stays infinite.    

(To clarify, the keyword here is 'disproportionately'. I'm not saying there isn't an odd use case of people using infinite radius to forgive a vanilla player. I'm saying 95% of the time, the infinite radius forgiven is gonna be a phex player. 
Most of the forgiven vanilla players are gonna be from ingame nearby forgiveness.)

I think the noob sheep killers of the world should get **EQUAL** recourse / appeal / pardon as the advantaged 'rich' (mod users) of the game.

But hey, maybe that's just me.

Noob 'how do I kill' griefers should get sent to DT for a long, long time?

But people with lots of friends and extra means / ways should get free passes? 
(Bear in mind, most mod users that get sent to DT are sent there for more serious reasons than the usual noob stabbing a sheep.)

It's not even like it's that hard for mod users to forgive people esp. with horses and the newly (pretty much) indestructible roads. Takes an average of 10 mins. But yeah, the rich don't like getting inconvenience.

Eat the rich, I say. Eat the rich.

**Comment by is52hertz** [comment]
> It depends on Mr. Rohrer.
>            
> If he thinks that it's fair for mod users should get their curses DISPROPORTIONATELY forgiven through using phex mod, then it stays infinite.    
> 
> (To clarify, the keyword here is 'disproportionately'. I'm not saying there isn't an odd use case of people using infinite radius to forgive a vanilla player. I'm saying 95% of the time, the infinite radius forgiven is gonna be a phex player. 
> Most of the forgiven vanilla players are gonna be from ingame nearby forgiveness.)
> 
> I think the noob sheep killers of the world should get **EQUAL** recourse / appeal / pardon as the advantaged 'rich' (mod users) of the game.
> 
> But hey, maybe that's just me.
> 
> Noob 'how do I kill' griefers should get sent to DT for a long, long time?
> 
> But people with lots of friends and extra means / ways should get free passes? 
> (Bear in mind, most mod users that get sent to DT are sent there for more serious reasons than the usual noob stabbing a sheep.)
> 
> It's not even like it's that hard for mod users to forgive people esp. with horses and the newly (pretty much) indestructible roads. Takes an average of 10 mins. But yeah, the rich don't like getting inconvenience.
> 
> Eat the rich, I say. Eat the rich.
> 
> 

It works too, it needs a more complex mechanism.
Not a few strings of words.
We need to judge, to think.
On the other hand, it's not about class, it's not about whether or not to use a mod.
Rather, it's about whether those who are cursed, those who are forgiven, are truly hateful, whether they are truly forgivable.

**Comment by is52hertz** [comment]
The "Report" feature is found in many games, but none of them do it very well.
It can be a tool for bad guys to oppress good guys, or it can be a starting point for public opinion

**Comment by cordy-123** [comment]
> It works too, it needs a more complex mechanism. Not a few strings of words. We need to judge, to think. On the other hand, it's not about class, it's not about whether or not to use a mod. 

To clarify I'm not saying forgiveness doesn't work.

I'm saying that mod users get forgiven **MORE** vs vanilla players IF the infinite range of forgiveness is not changed to a FINITE distance.
- Donkey town (200 million tiles away) mod users can name themselves Eve Something and ask phex chat mod users to ask people to forgive them,
- Cursed mod users can ask people in phex chat to forgive them (and ask the mod users to ask other people in town) from another town that is thousand of tiles away.
- You can currently forgive from tutorial (5 million tiles away) (yes, you can still access phex chat from tutorial).

**Comment by is52hertz** [comment]
Thoughts that
Does OneIife need the 'report' feature?
First of all, OneLife's main gameplay is to mimic reality.
Looking at reality, there is no "report" function.
What I mean is that "reporting" is human-made, according to law or morality, and ultimately, it's still made by people.
You can't say "I curse XXX" in reality, and then XXX is really sent to a horrible place, right?

So we need to look at the essence through the phenomenon.
If OneLife is more free, not a knife can be a painful death of a person, the fence is placed there people can still climb over ......
At the end of the day, OneLife's gameplay is still not done well enough to cause this phenomenon.

**Comment by TheMingo888** [comment]
> If he thinks that it's fair for mod users should get their curses DISPROPORTIONATELY forgiven through using phex mod, then it stays infinite.

This isn't something brought on only because of mods, though. Phex is integrated into YumLife/Hetuw for convenience, but it could just as easily have been a standalone program or a website or even a companion app on your phone. The protocol that drives Phex has nothing to do with the OneLife protocol.

I believe you are arguing that those who are cursed, but have a way to easily communicate with those who cursed them, have a greater probability of being forgiven. I agree with you that this is true. Whether this method is through Phex, or Discord, or some other communication platform is irrelevant. All that matters is that there is some way for the individuals involved to discuss the incident outside of the context of the game.

But is this a problem? Not at all! This is actually _wonderful_ and should be celebrated! The fact that individuals have a method to discuss their disagreements, and potentially resolve the conflict that led to the cursing, is a hallmark of mature and healthy communication. In a perfect world, we would always be able to reach some resolution, and cursing wouldn't be needed. Of course, in reality this will not always happen, so there will be some people we leave cursed. But certainly providing an opportunity to resolve things diplomatically helps to resolve a lot of misunderstandings and encourages forgiveness.

> I think the noob sheep killers of the world should get EQUAL recourse / appeal / pardon as the advantaged 'rich' (mod users) of the game.

I agree with you on this point as well. Where we disagree is on the method to obtain this "equality". Your suggestion is to make forgiveness more difficult and more inconvenient for _everyone_ to acquire. On the other hand, I'd actually like to make it easier for everyone to be forgiven. This was exactly my intention when I suggested the "I forgive everyone" phrase in #858.

If it were possible without much difficulty, I'd even suggest creating a button on the main menu that allows you to view a list of everyone you have cursed. Each entry would include the date, their curse name, perhaps their in-game name at the time of the curse, and maybe even a field for user-added comments. (I know you are I are very organized people that keep good track of who we curse and for why, but very frequently those I speak with have no idea why they have someone cursed. Providing an in-game way to keep notes on why I cursed someone would be awesome, so we can distinguish the "berry munchers" from the "town killers".)

Most importantly, such a list should have an option allowing you to forgive any of your curses at any time, even if the person you are forgiving is offline. Forgiving offline players is already possible by using the "I forgive everyone" phrase, but it doesn't allow you to forgive specific players.

The curse system is designed to allow us to choose who we do and do not wish to play with. If I decide I don't want to play with someone, I should be able to change my mind at any time. Limiting forgiveness would just make it harder for people to play together again.

> Noob 'how do I kill' griefers should get sent to DT for a long, long time?

And your suggestion does nothing to improve this! In fact, it makes it far worse. If we cannot forgive people far away, it is not just inconvenient to get people out of donkey town, but potentially _impossible_. While I believe someone that has gotten stuck in donkey town probably deserve to be there, there is always the possibility that we make a mistake or just change our minds. Right now, forgiveness is _the only_ way to resolve that situation. If you are going to suggest a change that breaks this, you need to provide some alternative.

> But people with lots of friends and extra means / ways should get free passes?

There is no free pass. Those that use Phex/Discord/whatever to communicate and beg for forgiveness are entirely reliant on those that cursed them to forgive them. I, personally, don't forgive people who engage in such antics, but everyone is free to act as they see fit. Chances are, if someone cursed someone, they know _why_ that person has ended up in donkey town and will feel no sympathy.

> But yeah, the rich don't like getting inconvenience.

Remember, you are suggesting making some things impossible, not just inconvenient. This is a hugely important consideration.

**Comment by DopiePanda** [comment]
If I understand you correctly, you wish that people in DT never should be able to be forgiven by non-DT players? (Just want to make sure I'm not misunderstanding)

And what about the "I forgive all" command? That should only apply to the players within a radius around you equalling the radius in which they can't spawn, because of your curse?

I believe your intentions are good, but I also think this is not a good solution.

In the first couple of months of playing OHOL, I cursed some babies that used the /die command, due to me not understanding the dynamics of the game (ie. Why they did it, and what consequences it would have later down the line).

With this suggestion I would likely never have been able to forgive them, as I had no curse names on them and no idea who they were.

**Comment by Hopie-OHOL** [comment]
Sometimes you can’t or shouldn’t leave town, like when you’re a fertile in a lowpop fam or when there are a bunch of new players looking to be taught. There have been plenty of times I’ve yummed up for a intertown trip just to realize that my family is out of food and I’ve had to stop and start cooking. Ideally you wouldn’t have to choose between leaving your fam in a precarious situation or leaving an innocent person cursed. Because curses now last five years and some players may give up on the game after a few lives stuck in Donkey Town, I think the benefits of being able to forgive (edit: forgive not curse) regardless of range outweigh the cons.

**Comment by is52hertz** [comment]
I don't think the 'curse' will do OHOL any favors.
It is going to become a tool.
It will punish the bad guys, and it will kill the good guys by mistake.

This will happen with or without PHEX!

**Comment by jasonrohrer** [comment]
This is an interesting issue!

I can definitely see both sides here.  It is weird for it to work from so far away, but it also makes sense to be able to forgive someone at whatever distance, especially if you realize that you cursed them in error.

Cursing from a great distance serves no purpose other than ganging up outside the game.

**Comment by squishysquid** [comment]
socially pressuring to forgive people with a meta tool that's not really supposed to be in the game is probably bad.

However forgiving people itself isn't going to be easy, you're not meant to be near them by the nature of the mechanic.

I think it'd be a good idea to put the radius, however add an outside game panel maybe on your download the game account link page that lists out the curse names you have cursed and gives the option to forgive from there. It'd be unverifiable from in game to prevent the social pressuring, and save you the effort of hunting people down or meta gaming to get the name.

That's my shot at an implementation idea and reasoning.

**Comment by path-to-aaru** [comment]
I personally have seen instances of players journeying to other villages to forgive someone after it came to light that the cursed person was falsely accused. The forgiver was under the impression that there did exist a limit, and the gameplay story that this incident generated was more interesting and personal than a random spoken word command that nobody would have seen. I am generally in favor of mechanics that generate interesting gameplay, and I also think that making forgiveness too easy will lessen the impact and severity of a curse and that's not really fun to me either.

**Comment by ghost** [comment]
I respectfully disagree with this suggestion. The current forgiveness mechanics allow for flexibility and practicality in various situations. While it's true that forgiveness can occur over long distances, this feature is essential for resolving misunderstandings and correcting unintentional curses. I can think of countless scenarios that illustrate the usefulness of remote forgiveness in preventing innocent players from being burdened with undeserved curses, especially now that curses have a significant impact on gameplay over a prolonged period. It also serves as a means of reconnecting with players stuck in Donkey Town, which can be a valuable aspect of community and gameplay. While there may be isolated incidents of misuse, the benefits of remote forgiveness far outweigh the potential drawbacks, ensuring a fair and enjoyable gaming experience for all. You don't have to forgive someone just because they or their friends ask you to.

**Comment by Rukhmar** [comment]
With the recent extension of curses to 5 years as opposed to 3 months, I feel it is best if we try to forgive people on mistaken curses, but this will just make it harder to. It is hard enough as it is to get some people to forgive, since it feels awkward going up to their faces to forgive, meaning they cursed them before which leads to the other person asking why and making them feel bad. Sometimes you realize too late you mistakenly cursed the wrong person, but your family now needs you, whether you are the last fertile woman, or the only person that has the knowledge to upgrade your town's well, and frankly, your own family seems to take priority over this stranger even if you might feel bad. This whole proposal seems to just be adding an extra layer of difficulty for no reason other than spite for those that use discord/phex/forums as opposed to just plain vanilla gameplay.

Mistakes do happen, I have accidental cursed people plenty of times. Whether it is a "curse you" hitting the wrong target when you are too young, or a person that was unfortunately was named something similar to a griefer (Allen and Allan, or Mika and Miko for example). With the low playerbase of this game, it feels counterproductive to make it more difficult for people to play normally. I have forgiven plenty of vanilla people I have accidently hit once I realized my mistake before.

People here keep mentioning about how a couple curses won't get you into DT, but what about locking them out of one town? It can still hurt to be locked out of a family you have spent many lives in, one where you built a monument, or just had a lot of positive interactions in your past life and wanted to make friends. We should all try to forgive our mistaken curses, because even if not DT, it can still ruin a player's night.

Not to mention that as people start out the game, usually they might be more eager to curse, but as they get experience maybe want to forgive some of those they jumped to conclusions on before. I know while curses were 3 months, people would more quickly jump on cursing the guy who killed the sheep, said a rude word, or was refusing to yum or listen to us when we try to explain it to them. But most sheep griefers will calm down and they should have a path to forgiveness too, once they see this game is not one about killing things, and if they stick with the game they will catch on to the yum system. Keep the forgiveness as it is, the more hurdles you add in, the less forgiveness will be used, which would be a negative to the game overall.

**Comment by Tarr-OHOL** [comment]
Lord this is a big thread. 

I think forgiveness shouldn't have a range limit. You gave us a command to forgive everyone and it seems goofy to not be able to use it. I really dislike the idea of donkeys basically spamming people in chat to get their accounts forgiven but I can never forgive a perma donkey (not like I want to) if there's a range limit. When are you going to be in an area with  donkey let alone a few where you would otherwise use the command to forgive them all? 

I think this is mostly a community should know better than to be blanket forgiving or going out of their way to forgive people who are already in donkey town. While I'm against letting them worm themselves out of their punishment I think if you're going to allow a blanket forgiveness it should be everyone including the assholes. If you're at the point you've cursed so many people that you need to forgive everyone that's sort of a you issue.

**Comment by SoloAceMouse** [comment]
I am a vanilla player with a lot of OHOL experience.

I feel confident that not a single vanilla players game experience will be improved by a forgiveness radius. There is not a current problem to be fixed here, as far as I can see.

Why waste time fixing what isn't broke? [Especially if this attempt to rectify a non-issue results in unforseen problems later]

**Comment by jasonrohrer** [comment]
Yeah, it seems like it's okay as it is.
