### ISSUE TITLE
Spooky deaths

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#934]
On rare occasions, I have noticed some deaths aptly described as "spooky". Such deaths gets marked as starvation in the lineage server, but they are clearly caused by something else. The last time I observed this was when four quadruplets, all under 3 years old, "starved" to death all at the exact same moment. I know that they were all well fed, but even if they weren't, it wouldn't cause all four of them to die synchronously. To make matters worse, four infant deaths caused a huge hit to my gene score, even though this was out of my control.

After looking through the server code, I think it's pretty likely this was caused by the four quadruplets disconnecting and then reconnecting using the quadruplets option, triggering the server to kill their previous life.
https://github.com/jasonrohrer/OneLife/blob/d3ac98f087708842d1c4cfa2064168f8a3225f9b/server/server.cpp#L8665-L8670

To make these deaths less spooky, it would be nice to have a few changes:
- The cause of death should not be starvation, since this is clearly not true.
  - You could set the killer to be themselves, just like SIDs. This shows up as "suicide" in the life logs, but you might want to adjust the fitness server so that it doesn't show up as "Sudden Infant Death" since my understanding is that this could happen even for adults.
  - You could invent a new death type. Maybe some sort of disease? Tuberculosis, perhaps?
- These types of death shouldn't have a negative impact on others' gene score, much like SIDs. However, they should still get logged properly to the fitness server, since it would be weird if this happened later in life and they never appeared in your leaderboard.
  - They should probably still have a negative impact on their own gene score to prevent abuse, also like SIDs.
  - It is fine (and preferable!) if they still had a _positive_ impact on others' gene score. For example, if I helped my child live to nearly 60 but they died due to this spooky cause, I would be a little upset if I didn't gain score from my efforts.

**Comment by cordy-123** [comment]
Yeah, that's an old issue.
  
It shows up in the hetuw mod's UI death notifications as "Killed by Unknown".
(But yes, it shows in the family tree as death by starvation.)

It's quite rare.

-------

I'd say a fix for it would be if the twins (/trip/quad) relogins as twins again with the same two accounts, just make the game relogin them in the same previous life.

It would be super rare for someone to twin (/trip/quad) again with a different set of players.
---> this usually only happens if "twinners" from the ohol discord (or a private discord) got a discord messaging that they are able to twin while one of the people are already in a life.

-----

Or another possible fix would be a message when they try to login as twins saying "you are still in a life now, you cannot currently twin".

-----
 
But yes, I have definitely seen (maybe once a year I witness it) a mother holding their child and the child just suddenly dies (even if they are over the age of being able to SIDs). 
And the mother is baffled because they weren't 40 years old yet.

Usually when an adult "twinner" does it, people just assume that that person starved. (Of course, unless you are a mod user with the death notifications turned on because you'll see the "Killed by Unknown")

**Comment by TheMingo888** [comment]
I don't think preventing people from twinning is a good solution here. If that were to happen, people would just reconnect to their old life and run off to the nearest wolf/snake/hog/bear, which is inconvenient for them. If there are also a baby at the time, this would cause the mother grief as she chases after her newborn, which is inconvenient for her.

And it is probably not possible to reconnect twins to their existing lives, since there is no guarantee they are twinning with the same players. (Even if it is super rare, it still needs to be accounted for.)

The current "magical death" is not a bad solution, to be honest. It just needs to be less spooky per my two points above.

**Comment by cordy-123** [comment]
I think it's weird that you're so bothered by this type of 'spooky death' when you have been considering adding a /die (or /forcedie) command (that allows anyone to immediately die regardless of age) to the currently most used, most updated version of the hetuw mod, where you are a co-developer. 
 
https://discord.com/channels/328215300279500800/328215300279500800/1155384730104102952

mingo888:
what if there was a suicide button
like /die but it would always work, regardless of age
is there desire for such a feature?

----

It's basically the same.

**Comment by TheMingo888** [comment]
That's... why I'm here. I noticed the spooky deaths a while ago, but never figured it out until yesterday. Someone responded to my question above by saying that AWBZ had a similar feature a long time ago, so I was looking through the server code to see how death is handled. I finally put two and two together, hence my bug report above.

**Comment by jasonrohrer** [comment]
Yes, this sounds like a bug!

Essentially, if you ever have a life going on the server that you're connecting to, you should always re-join that life, even if you're trying to twin when you re-join or whatever.  If you're still alive, you should continue that life, always.
