### ISSUE TITLE
Twinning players still start with a curse token

### ISSUE THREAD

**Issue by TheMingo888** [jasonrohrer/OneLife#937]
For a while, there has been a restriction in place to prevent new curse tokens from being given to twins/triplets/quadruplets. This makes sense, since it is otherwise very easy for them to all gang up on a poor player. This is especially important now that curses last longer and increase the curse score for the entire 5 year period.
https://github.com/jasonrohrer/OneLife/blob/d3ac98f087708842d1c4cfa2064168f8a3225f9b/server/server.cpp#L27909-L27918

However, some time ago I witnessed three rude triplets all curse one player that told them off. It seems that this is possible because even though twinning players won't get _new_ tokens while playing, they still start with a token if they had one at the end of their previous life.

Perhaps this should be adjusted?

**Comment by cordy-123** [comment]
> It seems that this is possible because even though twinning players won't get _new_ tokens while playing, they still start with a token if they had one at the end of their previous life.  
          
     
Since 2021, Mr. Rohrer has unblocked all anti-cursing stuff for twins (etc) due to demand at that time from discord users. (You can check using discord search for a bunch of the more vocal discord users asking for it. Mostly twinners.). 


Twins (etc) can currently earn new curse tokens. 
https://github.com/jasonrohrer/OneLife/commit/34369b1510f90712bdd12a09cfcf79bcbd4e928f

And twins (etc) can currently curse people. 
https://github.com/jasonrohrer/OneLife/commit/33014e2e9363208d4f1a85e2d568e308fa45e5d3

(Another proof that this change was due to discord members asking for it is the fact that the code change doesn't have the usual link at the end of the code change title/description saying Fixes#BlankNumberGithubIssue.)

-----

Because the rift ended already. He agreed to unblock it.

Should Mr. Rohrer reconsider it in light of the 5 year curse update? If he wants to, sure. 
But presumably, at least some of the usual twinners would get upset at not being able to curse again. IDK.
There are actually some players that mostly play with a twin. Like over 90% of their OHOL lives, they play with a regular twin partner. (Presumably, they are IRL friends, etc.)
There are also "twinners" that really like to play as twins (etc) but find twin partners through the public ohol main discord or private ohol discords.

-----

Both options (removing twin cursing or letting it stay) have disadvantages and advantages. 

But mainly the issue is less that twins (etc) can curse a chosen person multiple curses. It's that cursing is harsher now.

**Comment by TheMingo888** [comment]
Ah, thank you for pointing that out, I wasn't aware.

In this case, the bug is actually that twinning players do not get new tokens mid-life, then (as you can see from the code snippet linked above).
