### ISSUE TITLE
A change to the war system.

### ISSUE THREAD

**Issue by Kaden56** [jasonrohrer/OneLife#940]
There hasn't been a war in the game for a very long time. Thats mostly because people like to play peacefully. But its also because the war mechanic kind of sucks. War swords still take 12 seconds to stab and the ally system just prevents you from stabbing the other family all together. I'd say that during war the war sword should be instant stab, and the ally system should be turned off for the opposing family. In real life you won't go up to the opposing side and wait 12 seconds to stab them only to realize that you can't stab them because they have allies protecting them.

**Comment by Tarr-OHOL** [comment]
This would be awful because you can just juggle swords. It would be a return to the wild days of just carrying multiple swords to kill folks which again is awful.

**Comment by SoloAceMouse** [comment]
For war to work, you'd need the game to be functional when families aren't able to trade.

As it stands, even if war was streamlined, it would basically be two towns committing suicide for no reason just to appease some people who got to stand around and wave swords for a few minutes.

While conflict can be a good driver for stories, if implemented well, I don't see how you could implement war without radically altering the entire way this game works. There's essentially nothing to be gained from it, and it only hurts your fam to be engaged in one.

**Comment by Kaden56** [comment]
How do you juggle swords when after you stab someone it takes 60 seconds for the sword to not be bloody and you can finally drop it.

**Comment by Tarr-OHOL** [comment]
Because you can drop a bloody sword. 

Hold one sword in hand
Put second sword on backpack
Stab someone
Drop bloody sword
Take second sword off backpack and stab someone else
First sword becomes unbloody because the blood comes off in 10 seconds

Rinse and repeat. If you don't know the mechanics of something I wouldn't recommend making suggestions around them because it leads to bad stuff like the lock changes. I had to fight for swords get get nerfed to the current state and anything that reenables that shenanigans is an awful change.

**Comment by ghost** [comment]
> Thats mostly because people like to play peacefully. 

Yes. The war mechanic in a multiplayer survival game centered around parenting and civilization building tends to be unpopular and often deemed useless for several reasons. First and foremost, the game's primary focus is nurturing and developing a thriving society, which typically involves cooperative efforts and diplomacy. War introduces a disruptive element that distracts from the core gameplay, potentially leading to player frustration and animosity. Additionally, in a game where players are nurturing generations and raising families, the violence and destruction associated with warfare can be discordant with the nurturing and cooperative aspects of the game, making it unattractive to many players. Instead of enhancing the gaming experience, the war mechanic often detracts from the immersive and constructive aspects of the game. If the war sword were buffed again, anyone who uses it will almost certainly land themselves in Donkey Town very quickly.

**Comment by Kaden56** [comment]
You cant just "use" a warsword you have to have 2 elders agree and say "War" to activate the war to be able to use them. Then you have to lure someone out of town to be able to even have a chance to stab them, cus of the ally system.

**Comment by jasonrohrer** [comment]
Yeah, unfortunately, the war system is pretty much vestigial at this point.  There are lots of little things in the game that are like that.  Various experiments were tried, but over time, they were phased out, or replaced with other systems.
