### ISSUE TITLE
WAIT... Is there a misunderstanding!

### ISSUE THREAD

**Issue by is52hertz** [jasonrohrer/OneLife#951]
***
`English`
> This `lssues` is from #944.

**WAIT!** You @jasonrohrer may have misunderstood what I said.
You don't have to focus on this option.
___  
**What I meant was:**
**by me.** The most you'll need to do is throw me a little work and answer some of my questions, which won't waste much of your time or OHOL's.
**I will (want to) do it this way:**
- Register an **official OHOL China** account in China.
- Produce and post a Chineseization video about OHOL (_Chineseization is also produced by me_).
- Make cumulative update videos of OHOL every month.
- Focus on the Chinese player base.
- _More..._

**Note:**
- I would like to submit a video in the name of official OHOL.
- You don't need to spend extra time and effort.
___
**END:**
Can you add a contact form to discuss about OHOL China related issues? (Just take the time to answer) I don't think it's appropriate to discuss here.
E-mail: is.52hertz@gmail.com_
Discord: is52hertz_

***

***
`zh_cn`
> 此 `lssues` 来自 #944 。

**WAIT!** 你 @jasonrohrer  可能误解了我的话。
这个选项并不需要你重点关注。
___  
**我的意思是：**
**由我来做。**你最多只需要给我丢一点工作，回答我一些疑问，这不需要浪费你和OHOL多少时间。
**我将（想）这么做：**
- 在中国，注册一个OHOL**中国官方**账号。
- 制作关于OHOL的汉化视频并发布（_汉化也由我制作_）。
- 每月制作OHOL的累计更新视频
- 关注中国玩家群体。
- _more..._

**注意点：**
- 我想代表OHOL官方来投递视频。
- 你不需要花费额外的精力和时间。
___
**END：**
能加个联系方式以讨论关于OHOL中国相关的问题吗？（仅需抽空回复）我认为在此讨论并不合适。
_e-mail: is.52hertz@gmail.com_
_discord: is52hertz_
***

**Comment by jasonrohrer** [comment]
This is all fine, but I wouldn't want to make it "official," since it's not made by me, and I won't even be able to understand what you're making.

I really appreciate anyone making videos about the game, or helping whoever learn about the game.  And I welcome Chinese players, certainly.

But even the mighty Twisted, as amazing as his videos have been for OHOL.... even Twisted is not making "official" videos.

Thus, it's probably best for you to reach out to Chinese players through Chinese gaming forums, etc.

**Comment by is52hertz** [comment]
umm, You mean you can't accept others in the official OHOL name? Maybe this is overseen by you and I think if any account exists it should belong to you as well. Would that be okay?
@jasonrohrer Or do you have a better idea?

**Comment by is52hertz** [comment]
You know, not being official doesn't attract much attention.
