### ISSUE TITLE
Terrain Generation Errors

### ISSUE THREAD

**Issue by Shadie116** [jasonrohrer/OneLife#959]
![image](https://github.com/jasonrohrer/OneLife/assets/126846097/2d3325e9-48a9-4fd4-b8f6-0e711cf58ed0)
I know you want a clean issue box so you can do whatever you want with this at any time, I don't expect immediate responses. Just disregard till Wednesday

**Comment by cordy-123** [comment]
It's not an error.

The OHOL world is in bands.

You just reached the top border of the snow band.

**Comment by Shadie116** [comment]
> It's not an error.
> 
> The OHOL world is in bands.
> 
> You just reached the top border of the snow band.

Just really awkward looking though

**Comment by jasonrohrer** [comment]
Yeah, I will think about how to rough this up somewhat.

**Comment by jasonrohrer** [comment]
Actually, is there any reason the snow to the north and the desert to the far south doesn't just continue forever?

Anyone have any insights into problems that would be caused if we made both infinite above and below the central bands?

**Comment by SoloAceMouse** [comment]
> This is bad because this means gingers can stay in an area much longer than other families as once they’re at the kerosene stage they can basically sit in one spot. The only rubber they require for kerosene is one for the oil striking stage (which can be reused) and one for an engine (which can be reused).

I agree with this statement if Jason intends to overwrite terrain generation to the North with arctic. However, I'm not positive that is what he is suggesting here. [hopefully, Jason can clarify this point]

Assuming terrain generation stays the same [eg: Tundra only appears inside of badlands] then I think you still preserve resource scarcity due to the inherent limitation of biome availability.

**Comment by jasonrohrer** [comment]
Oh, yeah, the whole north would not be solid snow!

The way that it works is there's a kind of "altitude" for each tile on the map.  The lowest points are swamp, the next are grass, the next are prairie, the next are grey, and then the highest are specialty, which might be desert, jungle, or snow, depending on the band.

But in the middle, the highest is just more gray area.  And above and below (infinitely far north and infinitely far south, the highest is just more gray area.  The snow stops above a certain point, and the desert stops below a certain point.

**Comment by Tarr-OHOL** [comment]
Okay that’s good but does that not still encourage people to look north for oil? I mean it’s nice to not be potentially tapping out new ginger tarry spots like in the current system (since tarry taps out 160 east and west vs looking like 40 x 40 north/south) 

I personally don’t mind the change but this really opens up the amount of oil available to an area before it becomes too difficult for an area to be kept alive. 

It probably isn’t a problem at all in the end.

**Comment by SoloAceMouse** [comment]
My thoughts on the current system are that it penalizes you for longevity with Gingers, more so than other races.

If a Ginger family lasts too long, it can drain oil from areas where future Ginger eves spawn. This is unfair to future families since they have to go farther and they don't benefit from the previously extracted oil. I don't think a new family should be punished because the old family was too successful, as this creates a negative incentive to not have long-lasting families, which goes against the core conceit of the game.

By opening tundra to the North, this problem could be ameliorated by extra Tarry spots outside the fertility band.

For this reason, I support opening Northward tarry spots. 
[Also, I would love to drill for oil outside of fertility band so I don't doom my kids, lol]

**Comment by Shadie116** [comment]
Jeez this was empty like 10 hours ago

**Comment by cordy-123** [comment]
It would make TRADING way harder if fertility / homeband is extended infinitely. 

Some troll or some noob would go 10,000 or more away.

**Comment by SoloAceMouse** [comment]
> It would make TRADING way harder if fertility / homeband is extended infinitely.
> 
> Some troll or some noob would go settle 10,000 or more away.

I think this proposed change would affect terrain generation, but keep the fertility bands where they are currently.

**Comment by Shadie116** [comment]
Also why don't wells spawn in jungles, they're full of rain anyways

**Comment by jasonrohrer** [comment]
Anyway, I think this is too fragile of a thing to mess with.  There are all kinds of possible side-effects to infinite oil to the North.

Tarr pointed out how families will move West at different paces, etc.

As for the sharp line between bands, I don't love the way that it looks, but it is an important clue for people to know what's going on, and why they are homesick, etc.  It's good that everyone knows where the line is, or that the line can be easily seen.

I thought about making the line "rough" to make it look better (or even having it be on a sine wave or whatever).

But the problem with this is that, while the curvy line would still be visible in the specialty biomes (where the desert becomes jungle), the same line applies, invisibly, to homelands elsewhere, where there are no specialty biomes.  If this line is straight, this isn't a problem, because it's easy to extrapolate from the straight line seen in the specialty biomes.  But if the line is curved, or rough, or random, it will be very mysterious where it's not visible.  People will have to test it by noticing home-sickness as they walk back and forth, and even that will be messier to test on a curvy invisible line (it's pretty easy on a straight invisible line).

So I'm going to leave this for now.

**Comment by Shadie116** [comment]
▌│█║▌║▌║ 𝕆𝕂 ║▌║▌║█│▌
