### ISSUE TITLE
Score should be measured by total hours played

### ISSUE THREAD

**Issue by Forman9** [jasonrohrer/OneLife#966]
Surviving until 60 and not using /die simply does not predict skill or experience (or anything significant honestly).

Score determines Eve and Leadership roles, which are important so there should be some other mechanism for determining score.

I think the simplest is total hours played.

**Comment by skps2010** [comment]
Players that are "relative" new should have a chance to be a leader or an eve.
Players like me that start playing lately (2023) will never have the chance

**Comment by ghost** [comment]
I don't want to be forced to be leader every time I play just because I've been playing for so long. Being leader is useful, but also stressful. It's nice to have a break sometimes.

**Comment by Tarr-OHOL** [comment]
While the current system does push newer players up to leader maybe new accounts should just have an hour played requirement before their high gene score allows them to get leadership? By 10 to 25 hours of gameplay maybe it lets them inherit leadership like a normal account. 

New accounts can easily skyrocket since they start at 0 score + 0 average lifespan. These players always gain score unless they’re just instantly dying. Add in reduced food requirements for their first hours of play and it’s hard for them to lose but easy to gain.

**Comment by jasonrohrer** [comment]
Makes sense that new players should be blocked from these benefits until they have logged more hours.

It's like a Chess Elo.... early on, the number is garbage, and we have to wait for them to play a bunch of games before their Elo tells us something useful about them.
