### ISSUE TITLE
SID on Low Pop Server

### ISSUE THREAD

**Issue by oholseven** [jasonrohrer/OneLife#985]
Will the game allow up to 4 Eves on Low Pop, considering the SID change?  If you want to Eve to your own base, it sounds like bouncing between 2 fertiles could throw you into DT.

**Comment by MooseSeven** [comment]
Tarr's original suggestion would solve (or at least reduce) a problem without introducing new ones:
"Just make it always cycle and not be completely random."

The current change on the other hand is problematic for several reasons besides oholseven's concern.

Even main server sometimes enter phases of low population. When a family struggles, males or elders sometimes sacrifice the reminder of their years and /die to try to be reborn as a girl. The last fertile mother might not have many minutes left when this action is taken, and the person who tries to save the family might end up in donkey town if the person doesn't reach her in time.

Also, will this not just re-introduce the old problem of runner babies? 
"Got this working so that every mother remembers a full list of their SIDS babies as long as the mother is alive. And you can never re-visit a mother that you've SIDS-died to."
But if you run, you can re-visit?

Possible solution: Make it so that you can never re-visit a mother that you've SIDS-died to if there is another available mother that you have not SIDS-died to. Otherwise, pick a random mother as before rather than sending people to donkey town. Tarr's suggestion might still be better, but this will allow us to cycle at least once if storing the cycle is hard to implement.
That way players know that if they return to a mother, there are no more available mothers and they should stop SIDing.

**Comment by jasonrohrer** [comment]
Yeah, I will patch this up.  I agree about the runner babies.  That did suck.

**Comment by jasonrohrer** [comment]
Okay, so now you cycle through, and it is punctuated by a temporary trip to d-town.

After you visit there, your SIDs list is cleared, and you can cycle back through again.  But the visit to d-town lets you know:  you have run out of mothers.

You can suicide in d-town by stepping on a snake or whatever, and then cycle through again.
