### ISSUE TITLE
Small Server Eve

### ISSUE THREAD

**Issue by oholseven** [jasonrohrer/OneLife#990]
Testing is proving that only one Eve slot is available now on small servers.  We used to be able to /die and become an Eve, for 2 Eve slots, sometimes 3 when an Eve was homesick or something.  Limiting it to 1 slot interrupts what that Eve is doing, if the player has to raise a baby or run this player to their base.  It prevents Eve-chaining to your own base if a fertile is on, which could be 20k away from the Eve who births you.  It's not fun, it limits amount of players who can be on the server doing their own thing.  One person per small server?  That player can lock out all others from rendering their places, by not raising them.  Needs a fix.

**Comment by SoloAceMouse** [comment]
Absolutely agree.

I may not play small-server, but this change makes having a small server base nearly impossible, which is a big part of the game for many regular players.

With the new /die -> DT change, a single player can hold the small server hostage and prevent people from playing at their base.

**Comment by ghost** [comment]
This update has been horrible. If you do /die and get sent to DT it also ruins your eve chain. Depending on how far away your town is, it could be lost forever.

**Comment by oholseven** [comment]
There's just nothing to cycle through on small servers.  Open up 4 Eve slots and let us cycle into Eve slots so we can still continue where we left off, instead of DT.

**Comment by MooseSeven** [comment]
Not only can you hold people hostage and prevent people from playing at their base, you can refuse to raise kids at all and lock everyone out of the game while you're a fertile Eve. This doesn't even have to be a malicious decision: If you're out milkweed hunting with a truck, thousands of tiles north or south, there's no reason to settle there. You can raise a kid there, but they can't walk back to civilization, they need a truck. In the past we could gently inform our kids that they should try to Eve or be born to someone else - but now the one fertile Eve is the key gate to play for everyone else.

**Comment by TheOriginalTea** [comment]
Playing on smaller Servers has been prior to this update a way to let out one's creativity and build their version of a perfect town, either in collaboration with other players or as peaceful neighbours. Eve Chaining was 'the' method to get back to one's town and continue building without having to wait around 20 minutes to be able to use the horse, truck, knife or carry the cut stones to continue the buildings or even walk 10k from the other players town to your own. 

Here are the main issues with this update using server 7 as an example, knowing that there are two highways connecting most of the towns : 
1. Players born to the one Eve on the server will have to walk 10k+ tiles to their town or construction site. Knowing that you need to be at least 13 to use the horse and 16 to use the Truck, a lot of the first minutes of the game will be spend walking, despite the access to a highway. By the time some players will be back to their site, they'll be either too old to continue building or will only have around 20 minutes to actually play this game. 
2. It had happened before that one Eve has been afk-ing multiple lifes in her base. Your playing session will be at the mercy of that player, holding that Eve Spot hostage. Needing to wait around 25 minutes to 'hopefully' get the next Eve spot and actually play, kills the fun of playing with other players on smaller servers. 
3. Being born to the Eve that is doing resource runs has been already a hassle before but now you're at the mercy of that player actually seeing/hearing you (because the truck sounds are ungodly loud), picking you up and stopping her resource run to get you back to her place fully fed just so you can walk another 5k to your own base. Being the Eve that has to babysit and carry people all around the server to their bases (again 10k+ for some) is halting her advancements of her playsession, knowing that she might have to redo the same hassle her next life from a different perspective. 

This change will either let a lot of people starve as babies because the Eve didn't want to pick them up, didn't see them or they didn't have the food to get to the town or will become the next 'Player-Delivery' or 'Walking' Simulator.

**Comment by SoloAceMouse** [comment]
OHOLseven:
> There's just nothing to cycle through on small servers. Open up 4 Eve slots and let us cycle into Eve slots so we can still continue where we left off, instead of DT.

If he's gonna change it, he should remove DT from the /die entirely, for both small and large server.

DT exists to cordon off people who make the game worse for others, not punish players for trying to keep families alive/supplied or small-server players from getting back to their base.

As Tarr said in his initial issue, just make it cycle every time and that change alone is enough. DT is unnecessary and counterproductive as a response to /die. I get that a million baby bones is a flavor fail, but this is fixed by making family selection simplified by eliminating the randomness and simply cycling mothers.

Please Jason, for the sake of both small and large server, remove the DT component from SIDS-ing. Mother-cycling is fine, but small-server players would benefit greatly from their eve-chains not being broken.

**Comment by jasonrohrer** [comment]
Yes, it sounds like this change really broke things on small servers.

I will fix it!
